### ISSUE TITLE
[common] 2 new fast magnet search sources

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#1001]
https://snowfl.com/AgpjqIDnytfobyYqiDyldCgUGsstCRriKf/<url encoded keywords here>/5EubkAeo/0/NONE/NONE/1?_=1676351580356

https://btdig.com/

**Comment by gubatron** [comment]
btdig.com done

**Comment by fahimanwer** [comment]
Same issue as always, BTdig.com is not accessible in most of the countries.

**Comment by fahimanwer** [comment]
<img width="1496" alt="Screenshot 2023-03-03 at 6 50 40 AM" src="https://user-images.githubusercontent.com/36186398/222607575-5d84c196-d3fa-4ba3-8b0b-391499636e1f.png">
