### ISSUE TITLE
[idea] SearchPerformer connection priority is based on search results clicked

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#1003]
When a search is performed, search requests are sent to all the different SearchPerformers for each search source supported, currently the order in which they are called is random (I think), and at some point they were invoked in a fixed order, we'd try to place them with those that would respond the fastest towards the start of the queue.

Instead of shuffling the order in which search performers are performed or putting them in a fixed order, they should be prioritized in terms of how they're delivering for the user.

Every click on a search result should add points to a weight associated with the search performer, and the list is re-sorted on the spot, ready for the next search.

# Where do I look at if I want to help tackle this issue?

We have some redundancy in the `SearchEngine` architecture [that should be easy to refactor](https://github.com/frostwire/frostwire/issues/1002), for now this re-weighing and sorting would have to be implemented (or at least applied) in two places

 - [`SearchEngine::getEngines()` for Android](https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/gui/SearchEngine.java#L115)
 - [`SearchEngine::getEngines()` for Android](https://github.com/frostwire/frostwire/blob/master/desktop/src/com/limegroup/gnutella/gui/search/SearchEngine.java#L260)
 
 Then `SearchEngine` should have a way to be notified by the `TransferManager` or somewhere a download starts, that the click came from a `SearchResult` from a specific search engine, hopefully `SearchResults` don't have to be refactored too, to include the `SearchPerformer` they came from... ugh.

**Comment by ABirHAsan123-beep** [comment]
#1003
