### ISSUE TITLE
App is sold in AppGallery

### ISSUE THREAD

**Issue by Lijukay** [frostwire/frostwire#1006]
Hey dev,

I am sorry to tell you, but I found your app in AppGallery and it is sold there by some unknown dev.
You can find it here:

https://appgallery.huawei.com/app/C108386769
I have contacted Huawei already and I hope they can help us asap.

**Comment by gubatron** [comment]
Thank you!

**Comment by gubatron** [comment]
It looks like they took it down, will try to list for free our official signed installer.
