### ISSUE TITLE
Torrents' links that failed to download, lost after update..

### ISSUE THREAD

**Issue by hosadokha** [frostwire/frostwire#1008]
I had so many entries that had error "Not enough peers (something like that)", 
but I intended for them to be kept as a list for reference..
However after an update, they are all erased, I cannot even find names or links..
I wish there were logs, or search history, or a category in "Library" for failed torrents!

**Comment by gubatron** [comment]
it's working as intented.
if it didn't find enough peers to even download the .torrent, there's nothing frostwire can keep and you should try to find torrents that are more popular.
