### ISSUE TITLE
FrostWire 6.9.5 for Win11 Pro Launches 100% Frozen

### ISSUE THREAD

**Issue by WonderWoman1977** [frostwire/frostwire#1010]
I am having problems getting FrostWire to run but I am on a Windows 11 Pro computer (desktop self built) and I have allowed it through the Firewall. I DL'd version 6.9.5 from GitHub which is a later build than the 6.13.1 recommended to the OP who is on Win10.

Every single time I launch FW it launches instantly frozen and 100% not functional and shows "disconnected". Nothing is clickable. It additionally launches giving a window that there is a newer version available and offers to take you to the website or ignore the newer version but that window also is frozen, not functional, not clickable. Additionally the "X" to close the program or the version notification windows are not functional. The only way to close the program is through the Task Manager.

FYI - I got that version through this link (it happened fast don't remember how that page came up - I was uninstalling the old version that I had installed because it too was having problems like this):

[https://blog.frostwire.com/2021/09/03/new-frostwire-6-9-5-for-windows-mac-and-linux/](url)

Not certain how to post feedback on this repository or even in general on GitHub but taking my shot at it.  Seeking feedback from anywhere I can find to post this issue for FrostWire because I cannot find any links to any sort of support.  I even tried the "Discord Chat" link from the FrostWire website and there's no Discord for it that it can connect to.

**Comment by gubatron** [comment]
Hi, that's a very old FrostWire.
**Please download and use 6.13.0**
https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-6.13.0-build-319/frostwire-6.13.0.windows.github.exe

**Comment by WonderWoman1977** [comment]
Since I haven't been getting many replies on this issue no matter where I posted my issue, I went ahead and uninstalled 6.9.5 and installed 6.13.1 which is giving the same problem.  It launches and is immediately frozen including when it launches it gives a "newer version available" notification box that is frozen also and just like previously stated, the only way to close that window and/or the program is to use the Windows Task Manager.  I am going to try the version you gave me the link to and see if that works.  I will post my results.

**Comment by WonderWoman1977** [comment]
Just installed your reccomended version and it too is launching frozen.

**Comment by gubatron** [comment]
please check in the installation folder if you have files that have a name similar to hs_error_xxxxx.log, they might help figuring out the crash.

if not, it always helps to delete the config folder and start FrostWire, that should do the trick.

The folder is at
%USERPROFILE%\.frostwire5

**Comment by WonderWoman1977** [comment]
Sorry for the double reply, but I just noticed your additional comment about deleting the config folder.  As you can see in the screenshot I provided in my previous email, there is no config folder listed in that location.  Is the folder located elsewhere?

 

Additionally, I don’t know if you are or aren’t seeing the notes I am continuing to post on GitHub but, I have already tried installing both the 6.13.0 and the 6.13.1 versions of the program after uninstalling the 6.9.5 version.  All versions are doing the same thing with launching frozen instantly.

 

Thank you…….

 

 

Alisa

**Comment by gubatron** [comment]
please try removing the ".frostwire5" folder inside your user folder

`%USERPROFILE%\.frostwire5`

**Comment by WonderWoman1977** [comment]
Removed, do you need me to either reboot the computer or just attempt to launch Frostwire now that the folder has been deleted?

**Comment by WonderWoman1977** [comment]
Hello again,

 

I apologize for taking so long to reply to you with the results after deleting the folder you told me to.  I did that and the first time it launched it took me through the setup and seemed to be functional.  I closed out of the program and relaunched it and once again it back to being 100% frozen just like I described. 

 

I think I figured out what was causing the program to freeze and wanted to provide you with the information so that you can note it.  I have a NAS drive which is where I store my downloads and where I map the Windows Downloads Library to.  My NAS drive is actively synced to my Google Drive.  I think that active syncing was probably the issue.  I think that for whatever reason the program’s seeding and downloading conflicts with the active syncing process for Google Drive.  When the program froze again as mentioned above, I decided to test my theory and went ahead and deleted that folder again to go through the setup process again.  This time I set the Torrent files location to the local second hard drive on my desktop computer.  I closed the program and relaunched it a second time and it remained working.  I will test it out over the coming days and reply back to you a week from now to give it some time, but sooner if the problem happens again.  One last question; I am on the version you suggested which is 6.13.0 and when I open the program I get a pop up stating that there’s a new version available which is posted on the website which is 6.13.1; should I upgrade to that one or stay with what I have?

Thanks,

 

Alisa

**Comment by gubatron** [comment]
wow very good detective skills.
i suggest you continue to download to a faster local disk and have some other mechanism to synchronize the local folder with a folder in your NAS.

please always update to the the latest version available, 6.13.2 should come out towards the second half of this month with lots of maintenance.

**Comment by WonderWoman1977** [comment]
I have worked on corporate IT level one helpdesk for 25 years because I enjoy solving problems and picking up on indicators that something more widespread might be starting to happen. This is why I was able to think through what was going on.I have not had an opportunity to try using the program just yet because I am working on a more frustrating and extremely aggravating problem. I have the entire Adobe suite of programs and I also use Microsoft office and I am on Windows 11 Pro. The problem I am experiencing is that these days Microsoft shoves down everybody’s throats in a mandatory fashion that they must use Microsoft accounts for their windows computers and they also force feed  OneDrive down everybody’s throats when you install windows because it is attached to Microsoft accounts and also it is forced down everybody’s throat if you have an office subscription. OneDrive has entwined itself deeply into the Adobe programs. There is no way to change the default location for any of the Adobe products for any projects you work on . They always default to looking into the users/username/OneDrive folder and even if you save a project elsewhere, it does not save that particular location as a default it keeps going back to the OneDrive.I have spent two days trying to sever the connection between the Adobe programs and OneDrive. I have , the link to OneDrive, I have uninstalled OneDrive I have moved everything out of the OneDrive folder into my basic username folder and deleted the OneDrive folder but every time I launch an Adobe program it re-creates a OneDrive folder and points the programs toward that location as the default save location . I have gone so far as to dig into the registry and through a keyword search for OneDrive ripped out everything destroying windows in the process which I accepted was a possibility when I started doing that.I am now trying to install windows from scratch, but doing it, or at least attempting to do it by  Creating a local not a Microsoft online account for the computer. Even completely turning off my router so that I do not have any Internet that is being seen by anything and even going into my UEFI and manually, turning off the Wi-Fi, because my motherboard was still seeing that there was Internet out there, I am dead in the water, and not able to get the windows installer to trigger off, allowing the creation of a local, not a Microsoft account.I am determined to make this happen. I am determined to install windows 11 Pro along with all of my Adobe programs all without any connectivity or reference to OneDrive. I currently have the same post up on two different forums one of which is the Microsoft Community forum, explaining what I am trying to do when that I am at a dead stop because I cannot trigger off the windows installer to allow me to create a local a Microsoft account . I am hoping to hear back from somebody on that for him or the other one sometime today.Wish me luck I’m going to need it along with a good stiff drink afterwards. Thank you so much for all of your help. I will post again when I have been using frostwire.On Apr 3, 2024, at 7:21 PM, Angel Leon ***@***.***> wrote:﻿
wow very good detective skills.
i suggest you continue to download to a faster local disk and have some other mechanism to synchronize the local folder with a folder in your NAS.
please always update to the the latest version available, 6.13.2 should come out towards the second half of this month with lots of maintenance.
