### ISSUE TITLE
search is not working

### ISSUE THREAD

**Issue by Destroyarr** [frostwire/frostwire#1011]
search is not working

<img width="871" alt="image" src="https://github.com/frostwire/frostwire/assets/9728018/0fd17486-ae18-4fc5-a81b-d69971e34193">

HELP !!!

**Comment by gubatron** [comment]
are you running the latest version?
are you perhaps behind a firewall?

**Comment by gubatron** [comment]
![Screenshot 2024-05-31 at 9 03 51 AM](https://github.com/frostwire/frostwire/assets/163977/526a5d62-0a4b-40ed-b3f7-443be2ed1865)
![Screenshot 2024-05-31 at 9 04 03 AM](https://github.com/frostwire/frostwire/assets/163977/2409a505-1aa4-4de7-af7b-27f0d843ca33)

**Comment by gubatron** [comment]
sounds like a likely cause (network interfaces switched)

settings are saved in different files inside the .frostwire5 folder.
