### ISSUE TITLE
FrostWire wiggles/shakes on macOS

### ISSUE THREAD

**Issue by ShaneBeee** [frostwire/frostwire#1013]
The bottom bar of FrostWire on macOS is having a little bit of a spazz attack..

https://github.com/user-attachments/assets/2f202efa-2b32-47de-9cf9-3d0ae3501314

version info:
<img width="912" alt="Screenshot 2024-07-27 at 6 28 05 PM" src="https://github.com/user-attachments/assets/415623fb-e29f-40d4-b3ab-81f4669508ee">

**Comment by gubatron** [comment]
Thanks for the awesome bug report ShaneBee.

I'm planning to update the Java Virtual Machine on the next update, perhaps this will fix it.

I have a question though, what happens if you slightly widen the size of the window? Seems like it's just trying to recalculate the components sizes and it may be hitting a precision error that makes it do that... or does that happen no matter what the window width is?

**Comment by ShaneBeee** [comment]
Hey, thanks for getting back, it appears no matter how I resize the window, it wiggles uncontrollably. 


https://github.com/user-attachments/assets/1fc3a121-6db7-4781-aee8-d59ef445e4c7

**Comment by EquipableMC** [comment]
I can vouch, the same thing happens on Windows. 

https://github.com/user-attachments/assets/46bc1bff-284a-4001-941b-505c93ebb47e

![image](https://github.com/user-attachments/assets/c8cf9c39-f702-4ea6-b263-92d61fecdb3b)

**Comment by gubatron** [comment]
Please try our new version to see if the problem goes away, we've included a newer java runtime machine

Mac Installer (x86_64)
https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-6.13.3-build-322/frostwire-6.13.3-x86_64.dmg

Mac Installer (arm64)
https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-6.13.3-build-322/frostwire-6.13.3-arm64.dmg

Windows Installer
https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-6.13.3-build-322/frostwire-6.13.3.windows.exe

**Comment by ShaneBeee** [comment]
sadly, still shaky shaky 

https://github.com/user-attachments/assets/90441dc1-4dbc-47c7-871d-4359c87bdaa6

**Comment by gubatron** [comment]
oh no, wish I could replicate this

**Comment by EquipableMC** [comment]
Hello! Sorry for the late reply. It is still shaky on windows as well

https://github.com/user-attachments/assets/11258712-2ba8-48df-bc8e-59807218786c

**Comment by gubatron** [comment]
Just found the bug!

It's the "Seeding" and "Not Seeding" indicator in the bottom status bar that's causing the issue.

I'm gonna fix it now.

In the meantime, the solution is to set your Bittorrent to Seeding and since you don't want to seed, just stop the transfers as soon as they end for now.

Thank you!

**Comment by gubatron** [comment]
https://github.com/user-attachments/assets/e35e97a8-8c12-4dec-a105-9189031df769

**Comment by gubatron** [comment]
Thank you for reporting the issue, it's been fixed for our next release.
Here is the code for the fix:
https://github.com/frostwire/frostwire/commit/66cd129650fa39e43ba82e191cdc41c1c5deb3fb

**Comment by ShaneBeee** [comment]
Yippee, thanks for the fix. Excited for that download ;)

**Comment by gubatron** [comment]
the official installer isn't out yet, but I can build one just for you, let me know if you're on a mac with intel cpu or arm  cpu (apple sillicon)

**Comment by ShaneBeee** [comment]
oh that would be nice thank you, Im on a silicon Mac

**Comment by frostwire** [comment]
Here's a signed and notarized by apple installer for arm64 chips
https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-preview-6.13.4/frostwire-6.13.4-arm64.dmg

CDHash=224628e70f4e9c928c320f0f4ff98c7642bd23fe
Signature size=8978
Authority=Developer ID Application: FrostWire, LLC (KET68JTS3L)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Sep 30, 2024 at 8:53:47 PM

**Comment by ShaneBeee** [comment]
awesome thanks. It works brilliantly.

**Comment by gubatron** [comment]
Forgot to mention we have another installer, for x86_64 here
https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-preview-6.13.4/frostwire-6.13.4-x86_64.dmg

**Comment by EquipableMC** [comment]
> Forgot to mention we have another installer, for x86_64 here
> 
> https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-preview-6.13.4/frostwire-6.13.4-x86_64.dmg

What about Windows?

**Comment by gubatron** [comment]
Full release with more upgrades coming out today!
