### ISSUE TITLE
Frostwire Plus Feature Request: Support video and music sites other than youtube.

### ISSUE THREAD

**Issue by RealJosephKnapp** [frostwire/frostwire#1016]
The YT-DLP program that telluride is based on is very versatile, and youtube is not the only video sharing site. Only supporting youtube in Frostwire Plus only serves the big tech monopolies.

I propose the YT-DLP be used to its full extent and the following websites be supported:

1. Youtube
2. Peertube
3. media.ccc.de
4. Soundcloud
5. Bandcamp
6. Bitchute
7. Dailymotion
8. Rumble
9. Brighteon
10. NicoNico
11. BilliBilli
12. Vimeo

As for playing the videos, it should be possible to play videos within the Frostwire Plus app, or to have the option to force the video to be sent to VLC Media Player, MPV Player or MX Player Pro instead of the official adware/spyware app.

**Comment by gubatron** [comment]
it already supports hundreds of sites, try pasting URLs from other sites into the search bar.
