### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [frostwire/frostwire#1023]
Dear @frostwire team, @gubatron @aldenml,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by gubatron** [comment]
Done
https://github.com/frostwire

**Comment by Neustradamus** [comment]
@gubatron: Good job!

Please add you in public (same for other team members):
- https://github.com/orgs/frostwire/people

**Comment by Neustradamus** [comment]
@gubatron: Good job! :)

Please add you in public (same for other team members):
- https://github.com/orgs/frostwire/people

In more, you can add verify domain name :)
- https://docs.github.com/en/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization

You can add social network links, etc.
