### ISSUE TITLE
Frostwire frostwire-6.13.4.windows Windows 11: Frostwire was unable to load. Please reinstall or download and install Frostwire again. 

### ISSUE THREAD

**Issue by mkmtrading** [frostwire/frostwire#1026]
Title says it all...

**Comment by gubatron** [comment]
Please install 6.13.5
Installers here, bundle free
https://github.com/frostwire/frostwire/releases/tag/frostwire-desktop-6.13.5-build-325

**Comment by mkmtrading** [comment]
Awesome, thanksOn Dec 12, 2024, at 9:51 AM, Angel Leon ***@***.***> wrote:﻿
Please install 6.13.5
Installers here, bundle free
https://github.com/frostwire/frostwire/releases/tag/frostwire-desktop-6.13.5-build-325

**Comment by mkmtrading** [comment]
[
![Screenshot 2024-12-12 113055 frostwire](https://github.com/user-attachments/assets/81ab28c0-456f-4220-ba39-71f90997f096)
](url)
Same problem, I wonder if I need to upgrade/downgrade Java on Windows 11?

**Comment by gubatron** [comment]
no, Frostwire comes with its own java so that you don't have to worry about that.

Is your CPU an x86_64 CPU?

**Comment by mkmtrading** [comment]
Yes it is

**Comment by gubatron** [comment]
testing...

**Comment by mkmtrading** [comment]
Ok so no stable 64 bit version available yet? 
No problem, let me know when you have a release candidate and I'll be happy to help beta test

**Comment by gubatron** [comment]
no, the opposite way, no 32bit version, and no arm version.

**Comment by mkmtrading** [comment]
any plans for 64 bit ARM version?

**Comment by gubatron** [comment]
only if the windows world is somehow upended by a wave of ARM processors, perhaps this will be the case, but so far too early for us to try and build everything for windows arm, it's just me at this point.
Already a nightmare with macos arm and old x86_64 there. It's been 4 years, and still the majority of macs are on x86. windows should take way longer with so much hardware fragmentation

**Comment by gubatron** [comment]
I just completely removed FrostWire via Add/Remove Programs from Windows (10 though), and installed again, no issues.

Might be a windows 11 issue, or a corruption in your installation folder.

I'd try to remove FrostWire completely from disk and start over with this installer
https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-6.13.5-build-325/frostwire-6.13.5.windows.exe

**Comment by gubatron** [comment]
we bought an used Lenovo laptop and we couldn't install Windows 11 on it (compatibility issues according to the windows 11 installer), wish I had a windows 11 machine to test man

Thanks for your understanding, and thank you for reporting this, so far nobody else has said anything.

**Comment by mkmtrading** [comment]
PS I did delete the %APPDATA% hidden .Frostwire folder etc but I also did install a Java update recently and I'm wondering if thats hosing things up on Windows 11

**Comment by gubatron** [comment]
whatever java installation you have FrostWire won't care, as FrostWire will extract a custom (smaller) java version that has only the packages needed by FrostWire, it's self contained.

**Comment by mkmtrading** [comment]
Just installed 6.13.5 on my old windows 10 laptop just fine
Thanks
