### ISSUE TITLE
[android] Delete files from 'My Files' - The number of files is not updated after the files are deleted

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#104]
Tested on: **Android 5.1, 5.0.2, 4.2
FrostWire for Android version 1.7.1 (Build 237)** 
Screen: **My Files**
Test: **Delete files from "My Files" 
Ref. MF-3**
Ticket on internal QA repo: https://github.com/frostwire/qa-android/issues/87#issuecomment-199646027

**Observations:**

To reproduce this issue:

1. Go to `My Files` and select one or more files to delete

2. Check the number of files reflected at the top of the screen (for example `My Documents (112)` and select the option to `Delete` the file(s) you selected on step number 1

3. Once the file(s) are deleted from the list you can notice the number at the top of the screen `My Documents (112)` hasn't been reduced. Only when you `Exit` FrostWire and re-open it again this number is updated.

**Comment by gubatron** [comment]
Thank you!

**Comment by muckachina** [comment]
Sorry, this is not working properly on FrostWire 1.7.2 (build 243) pre-launch

On Android 5.1 the files are not being deleted now and the app crashes after trying to delete a second file..

On Android 4.3 FrostWire the file is deleted and the number changes but the app crashes after deleting a second file.

I'll get a log for this

**Comment by muckachina** [comment]
Now the crashing issue is solved but there are more related things on this 'updating the number of files:

> After deleting an Audio file from ‘My Music’ section the number of audios is not updated on ‘My Files’ > ‘My Audio'

> Now new files are not being counted on ‘My Files’, for example, I delete a file and I have 47 audios, when downloading new audios I still have 47 on ‘My files’ although I can see the new files there, it doesn’t refresh neither when going to a different screen/section

**Comment by gubatron** [comment]
@muckachina  please give it a try now from master. It should update the header counts now.
