### ISSUE TITLE
[android] Download a file and see it on 'My Files' - The number of files is not updated after adding new files

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#106]
Tested on: **Android 4.4, 5.1 and 5.0.2 
FrostWire for Android version 1.7.1 (Build 237) Plus and Basic**
Screen: **Library**
Test: **See downloaded files on the Library, the number of files on the list should increase
Reference on QA: MF-2** https://github.com/frostwire/qa-android/issues/88

**Observations:**

To reproduce this issue:

1. Go to My Files and see the number of files on a particular list (for example Audio files = 15) remember this number

2. Search and download an audio file till gets 'Complete' or 'Finished'

3. Go back to 'My Files' and see the new audio file appears in the list, you should notice the number of files on that list is the same you saw at point 1. The number of files is not being updated after adding new files unless I 'Exit' FrostWire and re-open the app (neither when deleting files, this is related to issue https://github.com/frostwire/frostwire/issues/104)

**Comment by gubatron** [comment]
half way there with this one.

Note: remove listener passed from fragment all the way to delete action and attempt to do this with either an Intent Broadcast, or by message passing on the app's main looper (if that's even doable, for fun-exploration of android's api)

**Comment by gubatron** [comment]
@muckachina please test once again from trunk, I think this could be closed now.
