### ISSUE TITLE
[android] Notify when BitTorrent connection is Off on Settings and a new download goes to 'Paused'

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#108]
This enhancement hasn't been added yet on FrostWire 1.7.1 (build 237).

Suggested by Kademlia for FrostWire 1.6.5 - Referenced on QA: https://github.com/frostwire/qa-android/issues/68

**To reproduce:**

1.- Go to FrostWire Settings and turn Off BitTorrent connection status

2.- Go to Search and select a file to download from a Torrent source

3.- The transfer list will open and **the file will go to 'Paused' automatically without letting  users know that 'BitTorrent' Connection Status is 'Off' on Settings.**

**Comment by muckachina** [comment]
This issue has been solved with the new "improved connection status display at the bottom of Transfers" tested on FrostWire 1.7.2 (build 241).

Now a notification bar at the bottom of the screen will show if 'BitTorrent connection is off'.

See images at ticket https://github.com/frostwire/frostwire/issues/107

**Comment by muckachina** [comment]
mmm Sorry I'm re-opening till make sure these are the final images, I saw an email from @marcelinkaaa with additional suggestions.

**Comment by gubatron** [comment]
we can close this for now, we'll code @marcelinkaaa for a future release. Release early release often type of thing, and we haven't released in over a month now.
