### ISSUE TITLE
[android] CRITICAL: Audio downloads to SD Card (Android 6) not being scanned

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#111]
Steps to reproduce:

1. Install from source.
2. Change save location to "SD Card" root (I saw there already was a "FrostWire" folder)
3. Download an audio file from SoundCloud.
4. Play it, it will play.
5. The file is nowhere to be found in "My Files" nor in "My Music" even after a restart of the application.

CC: @aldenml 

Here's the only hint I saw after the download was completed, even though permissions were granted.
I'll try reinstalling and restarting the app right after permissions have been granted. I think I liked it better when the app would restart fresh after permissions were granted I've a feeling this is due to an inconsistent state. I'll revise the code on how permissions are granted, I'll need another pair of eyes with me. I can reproduce this every time, this bug is very severe and it's probably the one many users keep reporting saying they played a file but then it's not there anymore (even though the file has been saved to the SD card)
```
03-29 12:57:57.615  1925  3061 I ActivityManager: Start proc 22961:com.android.externalstorage/u0a39 for content provider com.android.externalstorage/.ExternalStorageProvider
03-29 12:57:57.648 12544 12913 E DatabaseUtils: Writing exception to parcel
03-29 12:57:57.648 12544 12913 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/fs_id from pid=22454, uid=10274 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
03-29 12:57:57.648 12544 12913 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
03-29 12:57:57.648 12544 12913 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
03-29 12:57:57.648 12544 12913 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
03-29 12:57:57.648 12544 12913 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
03-29 12:57:57.648 12544 12913 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by aldenml** [comment]
Ok, very good you can reproduce it. If you look close to the log you posted, this error is beyond our control, since the only way you can communicate with the providers is with the android API, and the process in which the android providers run is different than ours. They "should" have all permissions. Taking a look at it together with another issue related to the SD.

**Comment by muckachina** [comment]
@gubatron is this the last version out for users 1.7.1 (build 237) or the last build I've been testing 1.7.2 (build 241)? just to make sure... I'll check right now on build 241 which is what I've installed in all devices

**Comment by gubatron** [comment]
Fixing title of the post, this actually occurs on Android 6.0.
I've just tested on Katay's Sony, which is a 5.1 and it works perfectly fine.

**Comment by muckachina** [comment]
mmmm I don't have Android 6 devices :/

**Comment by gubatron** [comment]
So @aldenml 

`requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()`

If I check on the app's permission, I do see the SD Card permission set. I'll write a test that prints out what permissions are actually available to FrostWire and see if maybe all we have is `WRITE_EXTERNAL_STORAGE` and not the reading one.

As for `grantUriPermission()` that would be the next hint if I see that we do have both permissions.

I checked the code and we do ask for both permissions in the array passed to the permission request, but who knows if these two are to be asked separately, two dialogs.

**Comment by gubatron** [comment]
After testing and attempting to fix this issue, we've figured out:

1. Files are saved correctly by the SAF framework.
2. On some devices, the Media Provider cannot scan the folder because it needs system-level permission (`MANAGE_DOCUMENT`)

The final solution will be to have a custom provider that keeps track of the files on the FrostWire SD Card save folder. Our app will have no issues tracking when files have finished downloading, when files are removed (with our app), and perhaps everytime the app is started we can do a once-per-session scan in case users have added/removed files in the frostwire save folder with 3rd party apps.

We can now do this because we can  scan mp3s now without android's underlying media scanner.
