### ISSUE TITLE
[android] Repositioning tracks in Playlists does not work ($15 bounty)

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#116]
When you open any playlist and try to drag and drop tracks into different positions, the new position either does not take, on Sony Xperia Z5/ Android 6 it just hangs mid new position (sort of on top of two other tracks). User said it 'glitches'

**Comment by gubatron** [comment]
@votaguz can you help me with this one? [$15 bounty]

**Comment by votaguz** [comment]
Yes sir

**Comment by gubatron** [comment]
awesome!

**Comment by gubatron** [comment]
Start by taking a look at the PlaylistFragment and its adapter.
I know it has a class somewhere in there that takes care of the drag and drop and the reordering, might be something stupid related to the number of items it's expecting (offset)

**Comment by votaguz** [comment]
Still working on grid thing. But i will take a look.

**Comment by gubatron** [comment]
@votaguz what is the update on this?

**Comment by votaguz** [comment]
Still trying to figure out how Apollo inflate the container that tracks the movement because seems that is inflated with the incorrect dimensions, that is why when you try to putting again the list doesn't know how to reorganize the elements. I apologize for the delay.

**Comment by grzesiekrzaca** [comment]
https://github.com/frostwire/frostwire/pull/136

**Comment by gubatron** [comment]
Fixed by @grzesiekrzaca
