### ISSUE TITLE
[android] Option to search 'More by Artist' appears duplicated on all Playlist individual audio menu 

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#118]
This issue has been reported by @marcelinkaaa 

Tested on Android 5.1, 5.0.2 and 4.2 with FrostWire 1.7.3

**To reproduce:**

1) Go to 'My Music' > 'Playlists' and select Last Added'

2) Select one of the audios on the list till the menu is displayed

3) You will see the option 'More by artist' appears twice. (See image attached)

![screenshot_2016-04-20-17-29-31 1](https://cloud.githubusercontent.com/assets/1534723/14724573/0fa76046-07e5-11e6-85c2-a771c002ef1b.png)

**Comment by gubatron** [comment]
please try again and close if the applied fix was correct.

**Comment by muckachina** [comment]
Tested from git and I couldn't reproduce it :) thanks
