### ISSUE TITLE
[android-player] Remember randomly played songs.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#13]
Currently the player does not remember what song was played before in shuffle mode.
I'd be nice to implement a stack that gets popped to retrieve the last played audio file when the user hits 'previous' during shuffle mode. If user decides to go forward again, then the next song is again a random one.

**Comment by gubatron** [comment]
**There's now a $35 bounty on this issue**

**Comment by muckachina** [comment]
I tested in 2 devices right now build-532 and it seems to be working perfect for Playlists @votaguz :)

I still have to test this release in other devices and double check the behavior on "My Files > My Audios", the Shuffle option could be tricky there with files that are not within the same album/playlist although the back button seems Ok there too. So I'm closing here and I'll re-open it If I find a particular scenario where the "back action" in Shuffle mode fails no problem. 

Thanks! <3
