### ISSUE TITLE
[android] VPN interface binding / auto launch VPN 

### ISSUE THREAD

**Issue by gbdrbob** [frostwire/frostwire#132]
Android VPN connectivity is not reliable. Any device left in standby will eventually lose the VPN connection potentially compromising the privacy of the user.

I request a feature to bind frostwire to the VPN interface (tun0) so all transfers go via the VPN and no data is leaked if the VPN goes down. In addition it would be cool if frostwire could be set to connect to an android VPN profile or launch a VPN app (such as oprnvpn connect) upon opening frostwire.

**Comment by gubatron** [comment]
Please close this issue, and split it into 2 issues. Very cool ideas.
If you have the skills to try to attempt one we'd love to receive pull requests for each.
