### ISSUE TITLE
[android] Handpicked file selection screen - list order

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#134]
The current version orders the handpicked files from the largest to the smallest. This is great when the screen pops up for a YouTube download, but when opening for a .torrent package, it should be ordered alphabetically (numbers first, then letters) - otherwise it just looks wrong. 

![screenshot_20160517-133558](https://cloud.githubusercontent.com/assets/7243139/15407649/0112c7b8-1dda-11e6-8b59-36924258493d.png)

**Comment by gubatron** [comment]
good catch, will parametrize the ordering and remove sorting for the .torrent dialog.
