### ISSUE TITLE
[android] Default scrollbar in playlist songs list ($15 bounty)

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#137]
Default system scrollbar is used instead of the custom one (which is rendered but defunct)

Samsung galaxy S5 Android 5.0

**Comment by gubatron** [comment]
can you please paste a screenshot of how it looks on that Samsung Galaxy S5?

**Comment by grzesiekrzaca** [comment]
![screenshot_2016-05-23-09-42-20](https://cloud.githubusercontent.com/assets/2766994/15463704/602668a6-20cb-11e6-925c-b6ef7743953b.png)

**Comment by gubatron** [comment]
Great find!
@grzesiekrzaca  wanna fix it for another $15?
(I don't think I've yet received a Bitcoin address to send you a payment for the last patch)

**Comment by grzesiekrzaca** [comment]
Investigating

**Comment by grzesiekrzaca** [comment]
The amount of time wasted looking in DragSortListView for the problem... 
(ノಠ益ಠ)ノ彡┻━┻
#150

**Comment by gubatron** [comment]
Fixed and paid for, thank you @grzesiekrzaca! 

Story of my life too, it usually takes longer to understand the issue than to fix it.

![putin_goodjob](https://cloud.githubusercontent.com/assets/163977/15617989/94c4318c-2419-11e6-8b5e-d5aff08abefb.gif)
