### ISSUE TITLE
[android] Creating a new playlist does not refresh the list of playlists

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#145]
the change is invisible until the list is recreated (go away from My Music and go back) or a next playlist is added. (action) [state] : [ exisitng playlists ], (add playlist "new1") -> [ exisitng playlists ], (add playlist "new2") -> [ exisitng playlists + "new1" ]

**Comment by gubatron** [comment]
hmm, thought I had fixed this, will take a look, thanks.

**Comment by gubatron** [comment]
can't replicate

**Comment by grzesiekrzaca** [comment]
https://youtu.be/OchlvAVjaqc

**Comment by gubatron** [comment]
funny, I just tried to make a video to show you how I could not replicate it and now it's happening on my device too

**Comment by muckachina** [comment]
Replicated on build 253 - Android 6, 5 and 4.3

The Playlist only appears after exiting the carousel menu of 'My Music' and coming back
