### ISSUE TITLE
[android] Please check if NAT and UPnP are actually starting.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#152]
I've added more alerts to the filters, I've tried forcing it on the settings pack applied to the session and I don't ever get a portmap alert on BTEngine's Inner Listener.

```
        final SettingsPack sp = session.getSettingsPack();
        sp.setBoolean(settings_pack.bool_types.enable_upnp.swigValue(), true);
        sp.setBoolean(settings_pack.bool_types.enable_natpmp.swigValue(), true);
        sp.setBoolean(settings_pack.bool_types.announce_double_nat.swigValue(), true);
        session.applySettings(sp);
```

My `InnerListener`'s `INNER_LISTENER_TYPES` array looks like this:

```
private static final int[] INNER_LISTENER_TYPES = new int[]{TORRENT_ADDED.swig(),
            PIECE_FINISHED.swig(),
            PORTMAP.swig(),
            PORTMAP_ERROR.swig(),
            DHT_STATS.swig(),
            STORAGE_MOVED.swig(),
            LISTEN_SUCCEEDED.swig(),
            LISTEN_FAILED.swig(),
            EXTERNAL_IP.swig()
    };
```

@aldenml  last night you mentioned I should try turning on a debug flag on jlibtorrent, but I can't find how to do this on `session` nor on the `libtorrent` class. completely forgot how it was and not very easy to find.

**Comment by aldenml** [comment]
You mean logging? https://github.com/frostwire/frostwire/blob/master/common/src/main/java/com/frostwire/bittorrent/BTEngine.java#L166, just pass true and add the relevant constant to the filter (`PORTMAP_LOG`).

**Comment by gubatron** [comment]
Thanks!

**Comment by gubatron** [comment]
Sweet :)

```
I/BTEngine(29937): broadcasting search for rootdevice
I/BTEngine(29937): adding port map: [ protocol: tcp ext_port: 40849 local_port: 40849 ] 
I/BTEngine(29937): adding port map: [ protocol: udp ext_port: 40849 local_port: 40849 ] 
I/BTEngine(29937): found router at: fe80::6eca:8ff:fe0e:a120
I/BTEngine(29937): ==> get public IP address
I/BTEngine(29937): ==> port map [ mapping: 0 action: add proto: tcp local: 40849 external: 40849 ttl: 3600 ]
```

**Comment by gubatron** [comment]
Some interesting findings with respect to ports. At this point I'm trying to find what the actual port is it that the client would be seeding on.

**What the portmap log says in this instance**
```
I/BTEngine(12906): broadcasting search for rootdevice
I/BTEngine(12906): adding port map: [ protocol: tcp ext_port: 54517 local_port: 54517 ] 
I/BTEngine(12906): adding port map: [ protocol: udp ext_port: 54517 local_port: 54517 ] 
I/BTEngine(12906): found router at: fe80::6eca:8ff:fe0e:a120
I/BTEngine(12906): ==> get public IP address
I/BTEngine(12906): ==> port map [ mapping: 0 action: add proto: tcp local: 54517 external: 54517 ttl: 3600 ]
```
So port `54517` right?

**What BTEngine says it's listening on**
Then, since I never got the portmap alerts, I decided to create my `x.pe` parameters using the port returned by `BTEngine.getListenPort()` (which does change on every run too, so it's not something hardcoded), that port is different than the one we try to port map, `56094` in this instance:

```
I/MagnetUriBuilder(12906): creating magnet with:
I/MagnetUriBuilder(12906): 2602:30a:2c88:db10:c2ee:fbff:fe5a:c898%22 : 56094
I/MagnetUriBuilder(12906): 2602:30a:2c88:db10:557:246a:1f6f:442%22 : 56094
I/MagnetUriBuilder(12906): 192.168.1.158 : 56094
```

as a funny note, if we ask `BTEngine` for it's listen interfaces string (which comes out of the `SettingsPack`, we just get what was passed during setup, not the actual interfaces.

```
I/MagnetUriBuilder(12906): BTEngine.listenInterfaces: 0.0.0.0:0,[::]:0
```

So if we were to somehow get the port on a portmap alert, we should do remote tests to see which port works best, my logic says, the one on the portmap should be good for outside connections. Maybe the one returned by `session.listen_port()` is good for local transfers.

**Comment by aldenml** [comment]
Yes, `54517` is the port, but in which interface? You are getting different ports due to some unknown reason in your device (the phone I assume), that should not happen and it didn't happen in my device when I tested. Something wrong is happening here. The port mapped in the portmap is the one that it's working in the local port too. If `session.listen_port()` is different, that's not good.

I would start by figuring out whey aren't you getting the alerts and why it rebinds the port so fast that ends with an inconsistent state.

**Comment by gubatron** [comment]
I'm going to try and print the `session.listen_port()` when I get that portmap alert to see if at that point in time the ports match, and maybe there's some sort of session pause/resume that might be causing the inconsistency.

**Comment by gubatron** [comment]
so indeed, you're right.

Each interface is trying to bind to a different port.

```
I/BTEngine(30620): LogAlert:  listening on: [::]:54478 external port: 54478
I/BTEngine(30620): LogAlert:  listening on: 0.0.0.0:52351 external port: 52351
I/BTEngine(30620): LogAlert:  listening on: [::]:42791 external port: 42791
```
weirdly we see that double attempt on that `IPv6` address there, but right after I get this error message:

```
I/BTEngine(30620): LogAlert: cannot to bind to interface [:: 0] ":: : system": Address family not supported by protocol
```

And `session.listen_port()` gives us `54478`, the first one on the list.

However, the port mapping seems to be done with the other port 👀 
```
I/BTEngine(30620): PortmapLogAlert: adding port map: [ protocol: tcp ext_port: 42791 local_port: 42791 ]
I/BTEngine(30620): PortmapLogAlert: adding port map: [ protocol: udp ext_port: 42791 local_port: 42791 ]
```

--
**note and question**
I read that the IPv6 notation for <address:port> should be written like this `[address]:port`, i wonder if your magnet parsing patch took into consideration those squared brackets, see the log alerts, the messages seem to use the right notation. I'll be fixing my `x.pe=` values to look like this:

`x.pe=[fe80::6eca:8ff:fe0e:a120]:52351`

**Comment by aldenml** [comment]
what do you think....just kidding :D yes, it parse the endpoint taking care of the brakets, actually I submitted a PR(https://github.com/arvidn/libtorrent/pull/757) to fix a minor parsing bug there.

**Comment by aldenml** [comment]
btw, something is telling me that there could be a subtle bug in libtorrent

**Comment by gubatron** [comment]
I'm looking for a way to enumerate the listening interfaces.

There should be something in session like:

`session::getTcpEndpoints(std::vector<tcp::endpoint>& endpoints)`
`session::getUdpListeningPort(std::vector<udp::endpoint>& endpoints)`

and then you could grab from those the listening ports.

**Comment by gubatron** [comment]
btw, so I tested sending the magnet to frostwire desktop, which I suppose was built with the latest jlibtorrent that supports `x.pe=`, but I felt like it wasn't supporting it because it didn't matter what port I put on the `x.pe=` addresses, in both cases, I managed to download the torrent info, and then the transfer stayed at `0 Kb/s`, however, as soon as I paused the seeding client and seeded again (`SeedAction` in frostwire-android) the transfer would start immediatly.

**Comment by aldenml** [comment]
Well, at least you managed to download the magnet! right. Yes, the support in RC_1_1 is limited, but it's there. You just need to manage to add the peers part to the url in the params like in this test: https://github.com/arvidn/libtorrent/blob/RC_1_1/test/test_torrent.cpp#L237
