### ISSUE TITLE
[desktop/android] YouTube Playlist search results + YouTube playlists on the Music Player.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#159]
If a YouTube playlist is found as a search result, it could create a YouTubePlaylistSearchResult with YouTubePlaylistItems, these could in turned be used to create a special kind of playlist for the FrostWire playlist.

Such playlist would be made entirely out of the youtube urls, and the user wouldn't have to download the tracks, just play the playlist and stream it at will.

Optionally the tracks could be saved for offline consumption.

**Comment by fahimanwer** [comment]
I think this issue can be closed no sir?

**Comment by gubatron** [comment]
indeed, this no longer applies
