### ISSUE TITLE
[desktop/android] New Advanced Setting to not start BitTorrent engine unless VPN is active

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#166]
Per [suggestion on reddit](https://www.reddit.com/r/Bittorrent/comments/4n4vjw/how_to_prevent_accidental_starting_of_bittorrent/) of [/user/Tyisgom](https://www.reddit.com/user/Tyisgom)

**Comment by grzesiekrzaca** [comment]
Only the android part of the issue is done. Desktop is still in progress (see my slack message)
