### ISSUE TITLE
[android] Open a torrent file using FrostWire on an Android device

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#172]
To replicate:

> Use a File Explorer and select a .torrent file to open

> Check the options you get from Android to open/launch the .torrent file does not include FrostWire as a Torrent option.

![screen shot 2016-07-21 at 7 44 12 pm](https://cloud.githubusercontent.com/assets/1534723/17042538/6f767e6a-4f7c-11e6-8a1c-d9d6f1217d50.png)

**Comment by aldenml** [comment]
Should be fixed with https://github.com/frostwire/frostwire/commit/67bc9ba3ce064812c5f0addf53860df3e8149a40

**Comment by gubatron** [comment]
ping @muckachina

**Comment by muckachina** [comment]
I'll pull to check from git :)

**Comment by muckachina** [comment]
Awesome!

Finally :) this was a pretty old one, thanks!

**Tested FrostWire 1.7.8 (build 291) from git on Android 5.1, 6 and 4.2** and when selecting a .torrent file I get FW as a first option. The file launches the app and is fetched properly on Transfer list:

![screen shot 2016-07-27 at 2 15 12 pm](https://cloud.githubusercontent.com/assets/1534723/17186818/c5fa2034-5404-11e6-91fb-67d66d452d4a.png)
