### ISSUE TITLE
[android] Select Storage Location Lollypop in advance - system remember prior location but set Internal Storage

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#180]
**To reproduce:**

1) Make sure you are saving on a particular folder within the SD card or Internal Memory (here on SD card > :

![screen shot 2016-08-23 at 9 09 27 am](https://cloud.githubusercontent.com/assets/1534723/17893171/ae722b50-6912-11e6-8e39-9379f2d16aad.png)

2) Uninstall FW and Install it again

3) During the wizard process ("Welcome to FrostWire Plus" screen) do not change "Storage Path", leave it at Internal Memory:

![screen shot 2016-08-23 at 9 09 45 am](https://cloud.githubusercontent.com/assets/1534723/17893268/18c9dfca-6913-11e6-9a07-369c6f85e55d.png)

4) Once you open FW go to Settings and you should see the 'Select Storage Location' is pointing Internal memory (aka 'emulated/0') as it should be but if you select the 'Storage Location' it will open the last route where you were saving files with the prior version you uninstalled - Inconsistency-.

![screen shot 2016-08-23 at 9 10 07 am](https://cloud.githubusercontent.com/assets/1534723/17893398/927d8df8-6913-11e6-97d2-08fb70dabde3.png)
![screen shot 2016-08-23 at 9 10 17 am](https://cloud.githubusercontent.com/assets/1534723/17893414/9ab3012e-6913-11e6-82e0-eeb618571c20.png)

**Comment by gubatron** [comment]
now, on step 2) is where the issue is originated. If you uninstall it, I think we can't do magic to remember what the path was

**Comment by gubatron** [comment]
I thought this was happening after an upgrade

**Comment by muckachina** [comment]
I can't reproduce when 'updating' on the Android 5 and 6 I've here but a lot of users just get 'Error' when trying to download after update and they fix the problem by selecting the 'Storage Location' again in all Android 5 devices and giving permissions again via 'Storage Location' on Android 6...
