### ISSUE TITLE
[desktop] Move 'Starred' list within Playlist section ($50 bounty)

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#182]
Including 'Starred' list within the same block as 'Playlists' on desktop will help to keep similarities with Android, right now the way to 'Favorite' songs with a 'star' is via Playlist but this 'Starred' list is right between Books and Torrents creating an inconsistency to favorite and play songs.

The requirement is to move the 'Starred' label on Library:

![screen shot 2016-08-29 at 3 41 05 pm](https://cloud.githubusercontent.com/assets/1534723/18064820/1a358b34-6dff-11e6-92a5-edf5f5843832.png)

Within Playlists section on Library:

![screen shot 2016-08-29 at 3 41 15 pm](https://cloud.githubusercontent.com/assets/1534723/18064824/201753d4-6dff-11e6-9712-16dafdd11407.png)

**Comment by gubatron** [comment]
@votaguz I think you should try this one. Gotta make sure:
1. The playlist keeps the custom icon it has on the panel above.
2. That it can't be deleted, so everything usually happens on ehn the list's offset >= 2
3. Gotta make sure the popup menu on right click works as expected for all items.

**Comment by votaguz** [comment]
Here a pull request intended to solve this issue. 
https://github.com/frostwire/frostwire/pull/244/
