### ISSUE TITLE
[android/critical] App acting like a zombie

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#188]
The app is coming back to life after the last 2 releases.

Things that have been tried without success:
- Disabling all ads.
- Disabling PlayStore.
- Removed MobFox.
- Interrupting all threads.

Things that have changed:
- AppLovin library update, gotta try reverting to previous version to see if this is culprit.

When I wrote the routine to interrupt all threads, I managed to get a list of over 60 active threads at the last line of `MainActivity.onDestroy()`

```
I/MainActivity: interruptAllThreads(): threadGroup 'main'
I/MainActivity: interruptAllThreads(): 61 active threads.
I/MainActivity: interruptAllThreads(): 0 active thread groups.
I/MainActivity: interruptAllThreads(): Thread (#505) 'SystemTasksHandlerThread'
I/MainActivity: interruptAllThreads(): Thread (#504) 'OkHttp torrasave.download'
I/MainActivity: interruptAllThreads(): Thread (#501) 'OkHttp torrasave.download'
I/MainActivity: interruptAllThreads(): Thread (#4a0) 'hwuiTask2'
I/MainActivity: interruptAllThreads(): Thread (#43f) 'SearchManager-thread-idle'
I/MainActivity: interruptAllThreads(): Thread (#43d) 'SearchManager-thread-idle'
I/MainActivity: interruptAllThreads(): Thread (#43b) 'SearchManager-thread-idle'
I/MainActivity: interruptAllThreads(): Thread (#439) 'SearchManager-thread-idle'
I/MainActivity: interruptAllThreads(): Thread (#437) 'SearchManager-thread-idle'
I/MainActivity: interruptAllThreads(): Thread (#435) 'SearchManager-thread-idle'
I/MainActivity: interruptAllThreads(): Thread (#433) 'OkHttp FramedConnection'
I/MainActivity: interruptAllThreads(): Thread (#431) 'OkHttp FramedConnection'
I/MainActivity: interruptAllThreads(): Thread (#42e) 'hwuiTask1'
I/MainActivity: interruptAllThreads(): Thread (#425) 'OkHttp ConnectionPool'
I/MainActivity: interruptAllThreads(): Thread (#424) 'AppLovinSdk:postbacks:GT8R'
I/MainActivity: interruptAllThreads(): Thread (#422) 'Thread-1058'
I/MainActivity: interruptAllThreads(): Thread (#420) 'MusicPlayerHandler'
I/MainActivity: interruptAllThreads(): Thread (#41f) 'AsyncTask #9'
I/MainActivity: interruptAllThreads(): Thread (#41e) 'AsyncTask #8'
I/MainActivity: interruptAllThreads(): Thread (#41d) 'AsyncTask #7'
I/MainActivity: interruptAllThreads(): Thread (#41b) 'RenderThread'
I/MainActivity: interruptAllThreads(): Thread (#41a) 'AsyncQueryWorker'
I/MainActivity: interruptAllThreads(): Thread (#419) 'AsyncTask #6'
I/MainActivity: interruptAllThreads(): Thread (#417) 'Okio Watchdog'
I/MainActivity: interruptAllThreads(): Thread (#416) 'AsyncTask #5'
I/MainActivity: interruptAllThreads(): Thread (#414) 'TcmReceiver'
I/MainActivity: interruptAllThreads(): Thread (#413) 'ApplicationFocusChangeObserverHandler'
I/MainActivity: interruptAllThreads(): Thread (#410) 'SystemTasksHandlerThread'
I/MainActivity: interruptAllThreads(): Thread (#40d) 'Okio Watchdog'
I/MainActivity: interruptAllThreads(): Thread (#40c) 'ActivityRecognitionSampler'
I/MainActivity: interruptAllThreads(): Thread (#40b) 'DataCollectionHandler'
I/MainActivity: interruptAllThreads(): Thread (#40a) 'telemetry'
I/MainActivity: interruptAllThreads(): Thread (#407) 'ConfigBootstrapHandler'
I/MainActivity: interruptAllThreads(): Thread (#402) 'ConnectivityManager'
I/MainActivity: interruptAllThreads(): Thread (#401) 'cr.CleanupReference'
I/MainActivity: interruptAllThreads(): Thread (#400) 'AsyncTask #4'
I/MainActivity: interruptAllThreads(): Thread (#3ff) 'AsyncTask #3'
I/MainActivity: interruptAllThreads(): Thread (#3fe) 'Thread-1022'
I/MainActivity: interruptAllThreads(): Thread (#3fd) 'Chrome_DBThread'
I/MainActivity: interruptAllThreads(): Thread (#3fc) 'Chrome_ProcessLauncherThread'
I/MainActivity: interruptAllThreads(): Thread (#3fb) 'Chrome_CacheThread'
I/MainActivity: interruptAllThreads(): Thread (#3fa) 'Chrome_FileThread'
I/MainActivity: interruptAllThreads(): Thread (#3f9) 'Chrome_IOThread'
I/MainActivity: interruptAllThreads(): Thread (#3f8) 'Chrome_FileUserBlockingThread'
I/MainActivity: interruptAllThreads(): Thread (#3f7) 'AppLovinSdk:back:GT8R'
I/MainActivity: interruptAllThreads(): Thread (#3f6) 'OkHttp ConnectionPool'
I/MainActivity: interruptAllThreads(): Thread (#3f5) 'WifiManager'
I/MainActivity: interruptAllThreads(): Thread (#3f4) 'AppLovinSdk:main:GT8R'
I/MainActivity: interruptAllThreads(): Thread (#3f1) 'pool-1-thread-1'
I/MainActivity: interruptAllThreads(): Thread (#3f0) 'AsyncTask #2'
I/MainActivity: interruptAllThreads(): Thread (#3ee) 'Offers-thread-idle'
I/MainActivity: interruptAllThreads(): Thread (#3ed) 'AsyncTask #1'
I/MainActivity: interruptAllThreads(): Thread (#3eb) 'Picasso-refQueue'
I/MainActivity: interruptAllThreads(): Thread (#3ea) 'Picasso-Dispatcher'
I/MainActivity: interruptAllThreads(): Thread (#3e9) 'Picasso-Stats'
I/MainActivity: interruptAllThreads(): Thread (#3e7) 'Session-alertsLoop'
I/MainActivity: interruptAllThreads(): Thread (#3e5) 'Thread-997'
I/MainActivity: interruptAllThreads(): Thread (#3e3) 'Binder_3'
I/MainActivity: interruptAllThreads(): Thread (#3e2) 'Binder_2'
I/MainActivity: interruptAllThreads(): Thread (#3e1) 'Binder_1'
I/MainActivity: interruptAllThreads(): Thread (#1) 'main'
```

**Comment by gubatron** [comment]
Fixed it, the issue was `MusicPlaybackService`'s shutdown logic.

**Comment by aldenml** [comment]
I remember looking at the music player shutdown (on multiple occasions) and it looks to me like the right way to do it... but let's see.

**Comment by aldenml** [comment]
Also, if this is the root of the problem, it seems strange that on some phones the exit works.

**Comment by gubatron** [comment]
![success_baby](https://cloud.githubusercontent.com/assets/163977/18401351/5e1ef2d6-7697-11e6-9923-c917488010a5.png)

https://github.com/frostwire/frostwire/commit/6416ff4aa5fcc7876b08986141fbe0732bf2f916

**Comment by gubatron** [comment]
So this was the logic before:
```
if (goToIdle) {
            scheduleDelayedShutdown();
            mIsSupposedToBePlaying = false;
            updateRemoteControlClient(PLAYSTATE_STOPPED);
```

and then that `scheduleDelayedShutdown()`...

```
private void scheduleDelayedShutdown() {
        if (D) LOG.info("Scheduling shutdown in " + IDLE_DELAY + " ms");
        if (mAlarmManager != null) {
            mAlarmManager.set(AlarmManager.ELAPSED_REALTIME_WAKEUP,
                    SystemClock.elapsedRealtime() + IDLE_DELAY, mShutdownIntent);
            mShutdownScheduled = true;
        } else {
            mShutdownScheduled = false;
        }
    }
```

but when I checked the `IDLE_DELAY`

```
/**
     * Idle time before stopping the foreground notification (1 minute)
     */
    private static final int IDLE_DELAY = 60000;
```

so I thought of a hack where I made that non-final and set the delay to 1ms, but I rather leave it as is.
Another way could've been parametrizing the scheduledShutdown call.

**Comment by gubatron** [comment]
# You are right

Still not fixed.

# Shutdown sequence:

`Engine.instance().shutdown();`

Esto a su vez dice:

`service.shutdown();` // service : EngineService

Esa llamada dice:

`stopForeground(true)` // sácame del foreground, por ende, cualquier proceso de android puede interrumpir el ciclo de vida antes de que se llame el `.onDestroy`

y luego dice

`stopSelf()` // inicia el proceso para detener el servicio via IPC, lo cual deberia llamar el `onDestroy()`, pero esto no se hace directamente, dado que ActivityManager es otro proceso, que eventualmente termina siendo algo nativo y utiliza el token del servicio para matarlo (ActivityManagerNative::stopServiceToken())

En teoría `EngineService.onDestroy()` es lo último que se debe llamar en el servicio, y si se está llamando, menos mal.

Dentro de `onDestroy()` veo que:
- Se apagan los broadcast receivers.
- Se quitan las notificaciones permanentes
- Se detiene BTEngine

Y luego se dice: `mplayer.stop()`, `mplayer.shutdown()`.

Es aquí donde las cosas fallan. `mplayer` es un `ApolloMediaPlayer` y este intenta comunicarse con el servicio `MusicPlaybackService` por medio de una referencia estatica en `MusicUtils` que se llamaba `mService`. Como el nombre me parecía confuso, la renombre a `.musicPlaybackService`.
(como tenemos varios servicios me pareció mejor ser claro pq me estaba confundiendo)

En fin, el truco de la referencia estatica no funciona, pq al ser `null` no hay como decirle al player que se pare.

```
public void stop() {
        try {
            if (MusicUtils.musicPlaybackService != null) {
                MusicUtils.musicPlaybackService.stop();
            } else {
                LOG.warn("ApolloMediaPlayer.stop() couldn't get a hold of the music playback service.");
            }
        } catch (Throwable e) {
            e.printStackTrace();
        }
}
```

Entonces si estuvieras aquí que dirías:

- Vemos por qué se está haciendo `null` esa referencia?
- O hacemos la llamada a detener el servicio en un lugar donde sea imposible que sea `null`?
- Ninguna de las anteriores?

Creo que estar a la merced de que la referencia esté o nó es mal ócodigo.
Por otra parte, ahora que leí el código del `MusicPlaybackService` se que la forma de detener el servicio, es llamando un Intent al mismo con un comando de shutdown.

Sigo investigando y te cuento. Espero que el código mismo me muestre el camino adecuado para hacer esto lo mas fail proof posible.

**Comment by gubatron** [comment]
Oh, una idea que se me olvidó comentar, es que el halt-thread, antes de hacer el process kill, puede esperar a que todos los servicios cierren correctamente.

Sería bien bonito en shutdown tener algo tan sencillo como:

```
//pseudo code inside the final halt thread
List<Service> services = getServices(); //returns all of the services this app uses.
waitForServicesToShutdown(services); //it blocks here until it can confirm they're all dead.
android.os.Process.killProcess(android.os.Process.myPid());
```

Lo que tenemos ahora es un `Thread.sleep(2000)`, que está pidiendo a gritos que lo quitemos.

**Comment by gubatron** [comment]
Ended up implementing it like:

```
public void shutdown() {
        Offers.stopAdNetworks(this);
        //UXStats.instance().flush(true); // sends data and ends 3rd party APIs sessions.
        finish();
        finishAffinity();
        tellMusicPlaybackServiceToShutDown(MainActivity.this);
        Engine.instance().shutdown();
        // we make sure all services have finished shutting down before we kill our own process.
        new Thread("shutdown-halt") {
            @Override
            public void run() {
                waitWhileServicesAreRunning(MainActivity.this, MusicPlaybackService.class, EngineService.class);
                LOG.info("MainActivity::shutdown()/shutdown-halt thread: android.os.Process.killProcess(" + android.os.Process.myPid() + ")");
                android.os.Process.killProcess(android.os.Process.myPid());
            }
        }.start();
    }
```

where:
`private static void waitWhileServicesAreRunning(Context context, Class<?> ... serviceClasses)`

on the next iteration it will be like:
`private static void waitWhileServicesAreRunning(long timeout, Context context, Class<?> ... serviceClasses)`

to avoid waiting forever in case a bug is introduced in the future, and I'll put like a `5000 ms` timeout.

**Comment by aldenml** [comment]
I think I understand your idea, but it seems that you are hacking around the real issue of properly shutdown the app and stopping the services. I'm not convinced about any of this (it just doesn't look right).

- When `stopForeground(true)` is called, it's true that android can kill the process, but that's true for either `true` or `false`, it only gets less priority, and if android kills the process, it will not be restarted again (unless some receiver is left registered)
- Yes, the question is: Why and when `MusicUtils.musicPlaybackService is null`?
- Why are your calling `finishAffinity()`?

At the end, I never heard what the real issue is/was, why and how to replicate it.

**Comment by gubatron** [comment]
> Why and when MusicUtils.musicPlaybackService is null?

My guess was that this happened during one of the scheduled shutdowns. If it were for me I'd get rid of all that logic and just leave the service running whenever frostwire is running, I wonder what his motivations were to keep trying to shut the service down every 60 seconds unless there was playback.

So when the service is shutdown, if I understand correctly, it is unbound and the un-binding callbacks set the reference to null in like 130+ different places in the code base. So it's very likely you'll have that reference set to null.

Therefore I decided it was way more reliable to shutdown using an intent, the way the service was designed to be shutdown. I passed along a "force" boolean flag so that it will stop even if it's playing music (stops the music first)

> Why are your calling finishAffinity()?

I read this would kill all related tasks, in other words "tirando flechas", we can get rid of that call, it won't make any difference (except I see that there are warnings by ActivityManager that it's getting duplicate calls to destroy the same activity, might be due to this, or other .finish calls)

**Comment by aldenml** [comment]
Good, let's remove the call to `finishAffinity`, the rest is just replace apollo at some point.
