### ISSUE TITLE
[android] Search option on My Files

### ISSUE THREAD

**Issue by alejandroarturom** [frostwire/frostwire#19]
My Files folder looks just the same as Search files. So if you are like a newbie and you are trying to look for new content but on My Files folder (and not in FrostWire mainpage search), of course you won't see any results (you'll see a white screen). 

![screenshot_2015-12-05-21-29-01](https://cloud.githubusercontent.com/assets/13737135/11611044/b4dd95c2-9b97-11e5-98bc-fc54665eeac3.png)

What I want to mean is that both mainpage search and My files search look the same so a person that is starting using FrostWire could get confused. I think we need to have a message with a button or link on My Files that said something like this:

> Couldn't find any files on your device under 
> "<search keywords>", 
> 
> <[Search for "<search keywords>" on the Internet__]>

If you use FrostWire for first time and you go to My Files and try to look for files and not get any results, you are going to uninstall the app. Maybe we can give people this little information message.

**Comment by alejandroarturom** [comment]
Couldn't find any files on your device under 
<search keywords>, 

<[Search for '<search keywords>' on the Internet__]>

**Comment by gubatron** [comment]
CC: @marcelinkaaa

**Comment by marcelinkaaa** [comment]
@alejandroarturom I don't think this is a big issue here. We never really seen any complaints, no one I showed the app was confused either. There is a clear separation between the search page and My Files page and a clear hint stating what a user can do with the field. 

But I do see a possible enhancement that could be done in the future. Mainly displaying a message that something was not found in 'your' library and providing a user with a one click 'road' to search where they can download it again or for the first time if they only thought they had it. 
I'll add it to my list so we can discuss it here after bigger things are tackled. Thanks!

**Comment by gubatron** [comment]
I think we actually get a lot of complaints by confused people that say they can't find anything.
They might be on this screen.
