### ISSUE TITLE
[desktop/player] Display Lyrics if available on MP3

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#194]

**Comment by gubatron** [comment]
@grzesiekrzaca let's start with a utility method that returns a String with the lyrics if they're available in the ID3 tags, `null` if not. (No UI code for now)

**Comment by votaguz** [comment]
Hi guys i just created a pull request to ask for some guidance. 
Related Pull Request: https://github.com/frostwire/frostwire/issues/369
Thank you
