### ISSUE TITLE
SettingsPack.activeDownloads is not enable

### ISSUE THREAD

**Issue by alicemmm** [frostwire/frostwire#214]
when I set SettingsPack.activeDownloads(4) and SettingsPack.activeSeeds(4) ,It should be only downloading four tasks in one time ,but I can download more than 4 tasks. it is unused.

**Comment by aldenml** [comment]
Are you talking about `jlibtorrent` or `frostwire`?

**Comment by alicemmm** [comment]
it's frostwire

**Comment by alicemmm** [comment]
It's jlibtorrent.
