### ISSUE TITLE
[android] Inconsistent scrollbars

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#223]
This is related to the problem I found last time. 
#137 
![screenshot_2016-11-02-11-21-08res](https://cloud.githubusercontent.com/assets/2766994/19925443/42a2bbcc-a0f0-11e6-94c9-da9446ea99b6.jpg)
![screenshot_2016-11-02-11-21-16res](https://cloud.githubusercontent.com/assets/2766994/19925444/42a629a6-a0f0-11e6-9e5b-570880807269.jpg)

Also there is a gap between the list and the header.

**Comment by grzesiekrzaca** [comment]
Changing the name of the issue to reflect that the problem is more widespread across the application

**Comment by gubatron** [comment]
Let's make it so it uses the same scrollbar we have on Search.

**Comment by gubatron** [comment]
bump, any progress on this one?

**Comment by grzesiekrzaca** [comment]
#256

**Comment by gubatron** [comment]
Thank you so much @grzesiekrzaca !
