### ISSUE TITLE
[android] Gap between list content and header 

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#224]
![screenshot_2016-11-02-11-21-08res](https://cloud.githubusercontent.com/assets/2766994/19925443/42a2bbcc-a0f0-11e6-94c9-da9446ea99b6.jpg)

Galaxy S5 Android 6.0.1

**Comment by grzesiekrzaca** [comment]
The culprit is `id/profile_tab_carousel_shadow` found in `layout/profile_tab_carousel.xml`
the gap is `dimen/profile_photo_shadow_height` (10dp) it is supposed to use `?android:attr/windowContentOverlay` but that is nulled in the styles.
So should it be ripped out?

**Comment by gubatron** [comment]
@marcelinkaaa can you please take a look

**Comment by marcelinkaaa** [comment]
I would simply take it out. We are not using shadows in other places, and the gap looks awkward. I am taking look at it now. And see how it looks without.

**Comment by marcelinkaaa** [comment]
I pushed a commit without it. Looks much better. Thanks @grzesiekrzaca
There is also that weird looking thin line on the right... looking for it now.

**Comment by marcelinkaaa** [comment]
sorry, just noticed issue 223.
