### ISSUE TITLE
[android] Send to chromecast icon for music player

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#229]
![chromecast](https://cloud.githubusercontent.com/assets/163977/19938006/f9128f70-a0e8-11e6-9228-28eee02aabe9.png)

`+`

![chromecast_cast_button_icon](https://cloud.githubusercontent.com/assets/163977/19938010/002f8556-a0e9-11e6-92ce-3511620f527c.png)

`= ???`

**Comment by gubatron** [comment]
The preview screen could use this button as well

![screen shot 2016-11-02 at 10 49 20 am](https://cloud.githubusercontent.com/assets/163977/19938307/121f26a8-a0ea-11e6-8338-b930a5c6631a.png)

**Comment by marcelinkaaa** [comment]
So I hope you meant something like this. If so, the icons have been added in my last commit. 

Keeping cast in the action bar is a great option if we will be using it in more places - like the preview. We would have to remove the search icon form the action bar in the player - or move it to overflow. Search from the player itself is not a main action for the currently displayed content, so taking it out will be ok. And per guidelines we should only have 1-3 icons on the action bar. 

![cast_disabled](https://cloud.githubusercontent.com/assets/2339972/19944330/cf892852-a111-11e6-882a-4871dd6b1e50.png)
![cast_enabled](https://cloud.githubusercontent.com/assets/2339972/19944331/cf89b5ba-a111-11e6-9ef1-a7f36e98da9e.png)

**Comment by marcelinkaaa** [comment]
![cast_enabled_blue](https://cloud.githubusercontent.com/assets/2339972/19949328/699909c0-a127-11e6-8988-7ba5caeb0cf6.png)

**Comment by gubatron** [comment]
I love it, precisely what we need, and where we need to start.
I'd do the first and the third (blue when it's casting), which is consistent with other UI elements that have been selected.

**Comment by marcelinkaaa** [comment]
Changed the color of the active icon in a latest commit.

**Comment by gubatron** [comment]
@grzesiekrzaca do you have an Android TV or Chromecast device?
Perhaps you can help us with adding a "Send to Chromecast" to the player screen.

**Comment by gubatron** [comment]
@marcelinkaaa please remind me if these icons were already added to the repo. If not please do so we can close this ticket and open the next one.

Cheers!

**Comment by marcelinkaaa** [comment]
It's there... ic_menu_cast_active and ic_menu_cast

**Comment by gubatron** [comment]
Thank you!
