### ISSUE TITLE
[android] Search | My Files: radio buttons look update

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#230]
from:
![screen shot 2016-11-02 at 10 44 52 am](https://cloud.githubusercontent.com/assets/163977/19938179/a1decea2-a0e9-11e6-92dc-45a085d0a634.png)

to:
![screen shot 2016-11-02 at 10 45 03 am](https://cloud.githubusercontent.com/assets/163977/19938188/a80007c4-a0e9-11e6-9e9e-ce36c26293c3.png)

as designed by @marcelinkaaa 

Pending: Deciding whether to do this on the current code base, or to wait until material design support has been merged.

**Comment by gubatron** [comment]
@marcelinkaaa is the search fragment now material ready?

**Comment by marcelinkaaa** [comment]
I have made that in search, my files, as well as transfers but unfortunately I was not able to style them in the same manner in Apollo. I will take a look at it again, its nothing pressing. But if someone has some free time to help with Apollo let me know.

**Comment by aldenml** [comment]
ACK

**Comment by aldenml** [comment]
@marcelinkaaa can you put a picture of how it should looks in apollo? (I want to make sure it looks good) thanks

**Comment by marcelinkaaa** [comment]
I wanted to head in this direction ->
We could change the darker blue background later when we add the ability to scroll down and show/hide toolbar, this way as we hide the toolbar - the background color of radio buttons do not clash with the darker blue of the status bar. 

In Apollo - another thing that I tried to change and failed - but would look much better with the new highlight - is that it would be great if it would start the tabs from the left, currently they start from the center and the highlight does not look amazing with all the empty space on the left. 
See image 2 to see what I had in mind. 

![1 future_my_files_audio](https://cloud.githubusercontent.com/assets/2339972/25762481/18797182-319c-11e7-845b-ca9548d97a3e.png)
![2 future_my_music_last_added](https://cloud.githubusercontent.com/assets/2339972/25762483/187fecf6-319c-11e7-842a-13d8d45ec4d9.png)
![3 future_search_results_audio](https://cloud.githubusercontent.com/assets/2339972/25762482/187eb9b2-319c-11e7-8e39-18f15a752ba5.png)

**Comment by gubatron** [comment]
I love it on both
