### ISSUE TITLE
[android] Dynamic filtering for search results

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#239]
We've reached the conclusion that we can do a more powerful and flexible search if we have dynamic filtering criteria based on the current list view data.

The UI would be much simpler to implement, and it'd be up to the user how to add/remove filters.

Possible filtering criteria would be presented in a dynamic way after parsing the results as they come in.

The first and most powerful filters would be simple keyword filters, a "steve jobs search" with suggested filters out of things like: Download sources, Distinct Available File Sizes, File Name Patterns we can recognize among multiple results could be added or removed by the user with a single touch of a label-like button that gets created on the fly.

**Comment by gubatron** [comment]
When you have a chance @marcelinkaaa please upload the screenshots of your designs here

**Comment by gubatron** [comment]
![screen shot 2016-11-11 at 12 43 45 am](https://cloud.githubusercontent.com/assets/163977/20207955/f35e60d4-a7a7-11e6-8d57-6b82c8705f84.png)

**Comment by gubatron** [comment]
@marcelinkaaa a possible way to show more tags and suggest that we can have exclusion tags
![add-positive-filter-tags](https://cloud.githubusercontent.com/assets/163977/20208379/15410b2c-a7ab-11e6-9808-b3b7207ee207.jpg)
![add-negative-filter-tags](https://cloud.githubusercontent.com/assets/163977/20208385/1a6b39c4-a7ab-11e6-9c84-cc0a2ae3f17c.jpg)

(just imagine those are real pretty buttons :) )

**Comment by marcelinkaaa** [comment]
@gubatron That might work, or at least something very similar. 
I uploaded the zip folder with images on Slack yesterday, since you uploaded few here already. Hope everyone had a change to go though the mockup and share few questions/feedback if any. 

Now let's think how easy/difficult would implementation of relevant suggestions would be.

**Comment by gubatron** [comment]
already have the algo in my head, easy peasy.

Maybe you want to try coding a mock up of it in Java for shits and giggles, it goes a little something like this:

for each search result:
  break all the text related to the result into single words
  get rid of any repeated keywords
  filter out terms like "the", "it", ... (aka stemming)
  with a string->int map, add +1 to each word bucket

then sort the map in descending order, the most relevant words will be on top, for sure you will have the names of the sources there, perhaps we can put source names on a different bucket so we can let the keywords in the results bubble up, and we can separate the source related tags

this will also allow us to have more info (if we want to) on the filter screen, you'd see the filter tag looking like "obama (23)" meaning there are 23 results that you can filter in or out

**Comment by gubatron** [comment]
This is nicely moving forward, I just need one more non-UI piece of the puzzle to be finished and I'll start doing the UI experiments.

**Comment by gubatron** [comment]
update: I'm experimenting with one additional UI component to invite the user to start filtering.

it's a fixed panel that shows the most important tags, and the tags in it are interactive (before I go ahead and build a dialog)

**Comment by gubatron** [comment]
Closing this issue, opening a [new one](https://github.com/frostwire/frostwire/issues/484) now that we have some code actually working.
