### ISSUE TITLE
webgui or web api

### ISSUE THREAD

**Issue by 0vermind** [frostwire/frostwire#24]
Hi guys, first of all I would like to congratulate for the great open-source project.

Are there any plans to implement a web interface?
Is there some other way to use Frostwire as an headless client?

**Comment by gubatron** [comment]
We're planning on doing so for FrostWire 7.0 for desktop.
We're still not sure if we'd have a headless client though. 

It will all depend on how easy it will be to bridge the interactions between the HTML and our Java code, we'll be using a lightweight SWT based browser component to render/execute HTML/CSS/Javascript, most likely, initially it won't be headless but maybe that's the way it'll go. We also need FrostWire on the server for many different things, for now we work our way directly with [frostwire-jlibtorrent](https://github.com/frostwire/frostwire-jlibtorrent) which is how I'd recommend you use FrostWire's Bittorrent capabilities in a headless way, but you'll need to know Java and soon you'll also be able to use the api with javascript [work in progress].
