### ISSUE TITLE
[android] Settings material design make-over, Advanced Torrent Settings

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#242]
(Ticket in progress)

With the new material design we'll have main settings grouped by labeled sections

## Main Settings screen
 * Download Settings (_section label_)
   * BitTorrent Connection [off | on]
   * Select Storage Location
   * Wi-fi only (save bandwidth, applies also for cloud downloads)
   * Torrent Settings > (takes to torrent settings page)
 * Search Settings (_section label_)
   * Search Engines > (takes to search engines settings page)
   * Clear search cache
 * Remove Ads > (BuyActivity)
 * Notifications and other settings >
 * About (won't be a separate Activity, will be a settings screen)

## Torrent Settings screen
  * Advanced Torrent Settings >
  * Sharing & Privacy (_section label_)
    * Seed Finished Torrents [x]
    * Seed only on Wi-Fi [x]
  * Bandwidth usage (_section label_)
    * Enable DHT [off | on]
    * Max Download Speed
    * Max Upload Speed
    * Max Downloads
    * Max Uploads
    * Max Total Connections
    * Max Peers

## Search Settings screen
  * Search Engines
    * Select/Deselect All [x]
    * Use Archive.org [x]
    * Use BitSnoop [x]
    * Use ExtraTorrent.com [x]
    * ...
  * Clear search cache 

## Notifications and other settings screen
  * Notify if FrostWire is running
  * Show Transfers On Download Start
  * Show New Transfer dialog
  * Vibrate when download finishes
  * Haptic Feedback
  * Anonymous Usage Statistics

## Advanced Torrent Settings screen
  * TODO

**Comment by gubatron** [comment]
@marcelinkaaa if you have any screenshots that can reflect this, please add them here

**Comment by marcelinkaaa** [comment]
Here are few screenshots - some settings are not functional yet - after the changes in layout few things need to be reorganized in code as well. Just a draft, need help with setting up final approach to the transition. Explained in email. 

Toolbar missing in sub sub section - Torrent Settings. Need more padding and some styling changes on first page of settings, title on toolbar needs to change according to a page, etc. 
Tablet looks different with the use of "Headers" in xml. 
About Us - updated styles and added more links. 

<img width="564" alt="screen shot 2016-11-14 at 7 34 14 am" src="https://cloud.githubusercontent.com/assets/2339972/20272944/8c8d2788-aa5d-11e6-996f-ebbf30220a91.png">
<img width="564" alt="screen shot 2016-11-14 at 7 34 44 am" src="https://cloud.githubusercontent.com/assets/2339972/20272945/8c908ce8-aa5d-11e6-889a-2503746ab9dc.png">
![screenshot_20161114-112431](https://cloud.githubusercontent.com/assets/2339972/20272954/92e9f516-aa5d-11e6-982b-e0a1f6435d2e.png)
![screenshot_20161114-112436](https://cloud.githubusercontent.com/assets/2339972/20272964/9a1becea-aa5d-11e6-9f8f-3edc0ae6a4fa.png)
![screenshot_20161114-112440](https://cloud.githubusercontent.com/assets/2339972/20272969/9ca6ae3c-aa5d-11e6-8377-14ceffd26cf5.png)
![screenshot_20161114-112446](https://cloud.githubusercontent.com/assets/2339972/20272974/9e902dfe-aa5d-11e6-96f0-dbde832b489b.png)

**Comment by aldenml** [comment]
can you forward your email to me please? thanks

**Comment by marcelinkaaa** [comment]
yes. Just a sec.

**Comment by gubatron** [comment]
as this is implemented, we must not forget that if you go towards a `PreferenceFragment` based implementation, we should keep the ability we have today to be able to open any sub-screen from anywhere else in the app. We do this on a couple of occasions if I remember correctly, in some other cases we just ask the user if they want a setting to be changed (friendlier IMO), but when we do that, we're educating the user on the options available.

**Comment by gubatron** [comment]
btw @marcelinkaaa this screen doesn't reflect what we talked about

![screen shot 2016-11-15 at 12 19 42 pm](https://cloud.githubusercontent.com/assets/163977/20320114/f572cb4c-ab2d-11e6-90b8-5ea7718e6343.png)

Not sure if that's a side effect of how things look when you translate to the smartphone smaller screen.

I remember a very different screen that looks like the "Main Settings screen" as specified on this ticket.

**Comment by gubatron** [comment]
we want to keep stuff like this on the first screen, not sure why you added that extra step

![screen shot 2016-11-15 at 12 23 01 pm](https://cloud.githubusercontent.com/assets/163977/20320205/4f8153d8-ab2e-11e6-9979-5380e568ad99.png)

**Comment by gubatron** [comment]
notice how I added the comment in parenthesis "(section label)".
When we had our conversation, your screenshot showed those in aquamarine like color, like other android apps, screenshot on next comment

**Comment by gubatron** [comment]
![screenshot_20161115-122643](https://cloud.githubusercontent.com/assets/163977/20320615/a671cc3a-ab2f-11e6-9900-4ec19b02e630.png)

**Comment by gubatron** [comment]
Those "General", "Notifications" labels are what I mean by "section label".

This whole thing below should be the first screen that looks similar to the screenshot on my previous comment:
```
## Main Settings screen
 * Download Settings (_section label_)
   * BitTorrent Connection [off | on]
   * Select Storage Location
   * Wi-fi only (save bandwidth, applies also for cloud downloads)
   * Torrent Settings > (takes to torrent settings page)
 * Search Settings (_section label_)
   * Search Engines > (takes to search engines settings page)
   * Clear search cache
 * Remove Ads > (BuyActivity)
 * Notifications and other settings >
 * About (won't be a separate Activity, will be a settings screen)
```

**Comment by marcelinkaaa** [comment]
@gubatron, I guess, again, I understood you wrong. By what you wrote here you want something like this... with cache on the main screen? Remember we should prioritize the content. This set up makes the buying 'pro' version less prominent - on many screens it will fall below the fold. I had to add 'other' section label as the 'search' label was blending with other options. 
Let me know so we are finally on the same page :)

![future_settings_bandwidth_network 10](https://cloud.githubusercontent.com/assets/2339972/20352140/43bd0748-abe4-11e6-9337-fc6acfaf93a8.png)

**Comment by marcelinkaaa** [comment]
How about this - we would need to alter a bit layout for tablets and phones. But it should not be that big of a problem. 'General' label on the tablet could be changed. That first label is always open to the user. 
On the phone - purchasing the Pro version is more visible and upfront, and on the tablet its on the bottom but still clearly visible.

Move Wi-fi downloading over storage so its closer to bittorrent on/off. Both are about connections. 

![1](https://cloud.githubusercontent.com/assets/2339972/20353385/a9677642-abe8-11e6-8f91-6772a0684c57.png)
![2](https://cloud.githubusercontent.com/assets/2339972/20353384/a96333c0-abe8-11e6-879c-cd688704292e.png)

**Comment by gubatron** [comment]
Let's get started on the changes for smartphones (unless you can somehow do both at the same time), as the user base there is overwhelmingly bigger than that of tablets.

I like how you put the "Remove Ads" on the left hand side navigation for tablets.

I'd still keep the "General" label on the smartphone screen for UI consistency.
I don't have an issue moving "Wi-fi networks only" over "Select Storage Location", it also flows nicer since you have the two switches stacked up and you're more likely to use that setting than changing your storage location.

**Comment by gubatron** [comment]
@grzesiekrzaca BTW, I recently added a function inside UIUtils to detect if we're on a tablet or not, I noticed you added one boolean resource for that.

```java
// UIUtils.java
public static boolean isTablet(Activity activity) {
        DisplayMetrics metrics = new DisplayMetrics();
        activity.getWindowManager().getDefaultDisplay().getMetrics(metrics);
        float yInches= metrics.heightPixels/metrics.ydpi;
        float xInches= metrics.widthPixels/metrics.xdpi;
        double diagonalInches = Math.sqrt(xInches*xInches + yInches*yInches);
        return diagonalInches>=6.5;
    }
```

ideally you'd execute this only once.

**Comment by marcelinkaaa** [comment]
ok so to recap... you decided to go with what is on the attached image. For now not using headers.
![settings_final](https://cloud.githubusercontent.com/assets/2339972/20635819/78e4f3d8-b330-11e6-853f-ddaf5b4fdebf.png)

**Comment by gubatron** [comment]
correct, let's focus on getting this one done first.

Q: is this what you mean by "headers"?
![screen shot 2016-11-25 at 3 00 20 pm](https://cloud.githubusercontent.com/assets/163977/20635837/efc77ec8-b31f-11e6-9b1f-537a3ac6c15f.png)

(I was calling that "navigation")

**Comment by marcelinkaaa** [comment]
Yes. They group the settings and give you a more responsive design with left and right containers on tablets and larger devices.

**Comment by gubatron** [comment]
so just to make sure we're clear, let's focus on this first
![settings_final](https://cloud.githubusercontent.com/assets/2339972/20635819/78e4f3d8-b330-11e6-853f-ddaf5b4fdebf.png)

**Comment by marcelinkaaa** [comment]
ok. Sounds good. I know @grzesiekrzaca is working on the branch material-design-preferences from his own account... could we move the branch to master so its easier to work on it together?

**Comment by gubatron** [comment]
I think you mean "move the branch to origin" right? If so yes.

**Comment by marcelinkaaa** [comment]
Sorry, yes origin :)

**Comment by gubatron** [comment]
sure go for it!

**Comment by marcelinkaaa** [comment]
An update after few stylistic additions:
What we need:
1) I heard many times how complicated and messy the preference code is - lets clean it up now as we are refreshing the look. If @gubatron or @grzesiekrzaca can take a look over what could be made better/get rid of deprecated code that would be great. Look over anything I have done as well. 

2) The look is there. There is a new xml file with all the changes, added new material theme, and toolbar - so that we can reuse it more easily on nested preference screens and other activities. 
    
    a) The 'Wi-Fi networks only' setting need to be worked on according to issue #93  
![1](https://cloud.githubusercontent.com/assets/2339972/20779937/d5ef8eee-b745-11e6-8dd0-813b3540541e.png)
   
   b) As you can see in 2.png from the size of the actionBar and status bar color being black instead of blue... I was not able to add the new toolbar and add material theme to BuyAds activity on my own. 
![2](https://cloud.githubusercontent.com/assets/2339972/20780291/ded08d54-b747-11e6-99ca-b83f051d6c91.png)

    c) In Torrent Preferences we use preference title and preference summary (3.png red arrows are pointing to it), in most cases the summary simply repeats the title. 
I want the summary to state what is selected instead. 
So for ex. instead of Title: Max downloads - Summary: Max downloads it should say Title: Max downloads - Summary: Selected: 4. 
In case of 'Max download speed' the summary could read 'Selected: 210 (0 means unlimited)'
![3](https://cloud.githubusercontent.com/assets/2339972/20780363/4953c588-b748-11e6-82ae-8a1306183d09.png)

And I think that would be it for now. Let me know if you have any questions.

**Comment by grzesiekrzaca** [comment]
3) Yes repeating the title is redundant. Also, are we overhauling pickers themselves? Current pickers are flimsy (I'd add the ability to write the desired speeds instead of scrolling, and information of what unit is used)

**Comment by marcelinkaaa** [comment]
@grzesiekrzaca Yes I would prefer that a lot better when dealing with large numbers.

**Comment by grzesiekrzaca** [comment]
Even "small" are problematic -> try to set to a 100 -> 10 swipes. have fun
setting that to 500 or more (I assume those are KB)

**Comment by marcelinkaaa** [comment]
True. Lets do it. 
I assume KB too but I am not sure... always have it at 0. If it is we need to make sure to include units in the summary- 'Selected: 10000KB (0 means unlimited)'

**Comment by marcelinkaaa** [comment]
TODO update:
Assuming that all the functions work properly:

    1. Need to adjust the paddings of listView as well as Category Headers on API 16-19. Adjust Category Heading color and style.  This is a pending fix: https://github.com/frostwire/frostwire/compare/master...grzesiekrzaca:design-adjustment-across-APIs
    2. ‘Use 3G/4G for BitTorrent’ should be replaced by ‘WiFi Networks only’
    3. Upon turning BitTorrent off, add a snackbar with the message: “Disconnected from BitTorrent. All BitTorrent transfers have stopped.“
    4. Search: Design: update the background of the selected search engine and the background of the ‘select all’ option up top. Split ‘Select/Deselect All’ into ‘Select All’ and ‘Deselect All’.  This is a pending branch: https://github.com/frostwire/frostwire/pull/328 
We can adjust that later when we work on MyFiles multiple file selection set up in a similar way for consistency? But it does look a lot cleaner and would love to see it up and running.  
    5. Torrent Preferences: as agreed, we still need to replace the dialogs to the ones on the mockups. The Settings2 can be released without this change - and we can work on it after that as well. If we do that we should adjust the font size of the numbers in the dialog. After switching to material they look way too small. 
    6. Under the summary for Max Total Connections, Max Peers etc. I would add the word ‘Current’ before the selected number in the summary. What do you guys think? Also add (in Maximum download Speed and Maximum Upload Speed) the wording '0 means unlimited'. 
    7.  Few minimalistic design adjustments in ‘Remove Ads’ - I will do it. 
    8. At the very end, when all parts of app are updated, the toolbar and the status bar need to be adjusted to fit the material guidelines. Size, color. 

Mockup: https://xd.adobe.com/view/2accfaf0-9b5b-4b50-932d-7f806bcf8aae/

**Comment by grzesiekrzaca** [comment]
@marcelinkaaa 
Ad. 5)
I started work on those pickers:
https://github.com/grzesiekrzaca/frostwire/tree/material/custom_pickers
I made some assumptions (like auto opening of keyboard to enter the new value)
and just started styling (I have a hunch that it will be a blast as the default support styles looked bad on API <= 19)

**Comment by grzesiekrzaca** [comment]
2,3) On it.
6) Personally I think there is no need for the word "current". From the design guidelines:
>  For non-switch settings, secondary text should show the current status of a setting only.
Same with unlimited and 0. I think the user doesn't need to know that 0 means unlimited until he want's to change it (that info is in the new pickers) and "Unlimited" below the Setting title is enough.

**Comment by grzesiekrzaca** [comment]
#331

**Comment by marcelinkaaa** [comment]
@grzesiekrzaca 
6) Ok, I do agree with '0 means unlimited' - since we are using new dialogs and we clearly stated it there - there is no need to repeat.
As to the the word Current. If we keep it as you have it: you state '10 downloads' instead of '10', 'unlimited' instead of 0, then I am good with how it is as well. Feels good.

**Comment by gubatron** [comment]
what's the status on all of these items? and are these all the issues you believe are needed to finish this?

1. Padding adjustments on listViews and category headers for API 16-19
2. ‘Use 3G/4G for BitTorrent’ should be replaced by ‘WiFi Networks only’
3. Search engine background color when selected. #328 branch
4. Wording on torrent settings summaries (e.g. "Current ...") 
5. Few minimalistic design adjustments in ‘Remove Ads’ - I will do it. (is this related to settings? let's not get distracted from the task)

**Comment by marcelinkaaa** [comment]
1. branch started, needs review, Alden was looking over
2. needs yet to be done
3. @gubatron the branch is there, almost done. Please review the design as it is the style of multiple selection I would like to keep in My Files as well. 
4. Look above, solved for me, unless you have objections.
5. Doing now.

**Comment by gubatron** [comment]
![screenshot_20170123-101931](https://cloud.githubusercontent.com/assets/163977/22214661/b1423094-e155-11e6-8ddc-ccd8623ac48b.png)

**Comment by gubatron** [comment]
is there a wat to control those horizontal lines?

it's very confusing when you have a line between two settings, and then comes another section.

Horizontal break lines are used to separate sections almost everywhere, I wish I had for example a horizontal line instead between "Torrent Preferences" and "Other Settings".

The way it looks now, it's almost as if the title was "Torrent Preferences" and the "Other Settings" was the call to action. Also because the text is smaller, it's very confusing visually IMO.

CC: @marcelinkaaa

**Comment by gubatron** [comment]
Update: Merged 328 branch @marcelinkaaa 


1. Padding adjustments on listViews and category headers for API 16-19
2. ‘Use 3G/4G for BitTorrent’ should be replaced by ‘WiFi Networks only’
3. ~Search engine background color when selected. #328 branch~
4. ~Wording on torrent settings summaries (e.g. "Current ...")~
5. Few minimalistic design adjustments in ‘Remove Ads’ - I will do it. (is this related to settings? let's not get distracted from the task)

**Comment by gubatron** [comment]
For item 2, @marcelinkaaa do you want something like this?

```
Wi-Fi networks only
Do not download if Wi-Fi is not available, save data on my mobile plan
```

**Comment by marcelinkaaa** [comment]
@gubatron There is always a way to control the horizontal lines - but that requires styling hacks. I would, however, keep it the android way - cleaner and easier to maintain. I myself was never confused as to the layout, but I only asked 2 other people what they think. Don't have a study group. ;) We can have the group label words (blue text) all caps to make it more separate from the rest but I don't think it's necessary.

For item 2: was thinking -
'Wi-Fi networks only'
'Save data. Download only if Wi-Fi connection is established.' 
Sounds more positive then saying 'Do not'

**Comment by aldenml** [comment]
Sorry, but I needed to revert the latest commits from `master`, was not squashed and a some things well not coded properly

**Comment by gubatron** [comment]
gotcha. Let's leave as is for now (item sep/lines) and see if there's any feedback, it seems counter intuitive to me and Google hasn't been the best with UI, they've made plenty of mistakes, I like to go with common sense, you know me.

2. I'm on it unless you already did it.

**Comment by gubatron** [comment]
sorry about that @aldenml, I tested the branch, saw reasonable code and decided to merge, this task is getting ridiculously long, my thinking is let's just fix on top if there's something wrong. #breakingThingsButMovingForward

**Comment by aldenml** [comment]
@gubatron there is a threshold for that and I would say it's not close to it.

**Comment by gubatron** [comment]
Update (merge reverted)

1. Padding adjustments on listViews and category headers for API 16-19
2. ‘Use 3G/4G for BitTorrent’ should be replaced by ‘WiFi Networks only’
3. Search engine background color when selected. #328 branch
4. ~Wording on torrent settings summaries (e.g. "Current ...")~
5. Few minimalistic design adjustments in ‘Remove Ads’ - I will do it. (is this related to settings? let's not get distracted from the task)

**Comment by marcelinkaaa** [comment]
@gubatron  5. not really, send you a message about what I want to work on. Can be taken off the list.

**Comment by aldenml** [comment]
After talking to @marcelinkaaa and @gubatron, we agreed that we have reached the critical point in which we should move to the QA phase and start the process of removing the old `SettingsActivity`.

Issue update
1- fixed in 16, more testing is needed in 19
2- Left as the next(critical) task once we are using the new `SettingsActivity2`
3- Left as a task to work together with "My Files"

@muckachina my plan is that you should get all the support from @grzesiekrzaca and me to sort out the details during the tests. If you have other tasks in hand, let me know to adjust our schedule.

@marcelinkaaa I suggest you keep a close track of the missing parts in your internal list to be able to task them out once we finish the move.

@grzesiekrzaca please, until erika reports back review as much as possible the PR #330

**Comment by grzesiekrzaca** [comment]
1 - looks good on 16 but broken on 18 and 19

**Comment by muckachina** [comment]
I'll be on it the entire day today, I pulled yesterday night and the 2 Settings options are still there.

**Comment by muckachina** [comment]
Ok,

Till now everything is acting as usual with regular Settings, only 'Haptic Feedback' and 'Distraction Free Search (beta)' are no doing anything when selected. All prior issues on Settings persists too, only graphic changes.

**Comment by aldenml** [comment]
thanks for the update
