### ISSUE TITLE
[desktop] Playlist song -> right click -> Add to playlist -> should show "Starred" as an option

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#248]
![screen shot 2016-11-15 at 10 14 28 am](https://cloud.githubusercontent.com/assets/163977/20315780/62fddad8-ab1c-11e6-9ef0-31b6dd386244.png)

**Comment by gubatron** [comment]
CC: @votaguz

**Comment by unnivm** [comment]
Hello gubatron,

I can help in fixing this issue as I have more than 100 hours of development experience with "Frostwire". Basically I am a freelancer and for one of my client I had done lot of modification

Thanks,
Unni M

**Comment by gubatron** [comment]
CC: @votaguz 

Done.
