### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by gobne** [frostwire/frostwire#25]
Hi guys,
Is Frostwire ready for switching to ipv6? Or at least are there any plans to fully support it?

**Comment by gubatron** [comment]
There are several components that already support IPv6, one that is pretty important (the DHT) is almost there, there's work being done in libtorrent and almost merged, once there it makes it to jlibtorrent and we'll have IPv6 DHT routing.

**Comment by 0vermind** [comment]
that's a wonderful news!
