### ISSUE TITLE
[android] notification music playback controls are poor when notification cannot expand 

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#251]
Samsung S5 Android 6.0.1

Repro:
1) Have many permanent notifications 
2) Start music playback
3) Press the home screen button
4) See the notifications
Is:
![untitled](https://cloud.githubusercontent.com/assets/2766994/20345414/53843b0c-abf7-11e6-8891-31c28f5adaf1.png)
Expected:
Something better than forward track and close?

**Comment by gubatron** [comment]
I'll let Marcelina decide what else makes sense to add here.

I suppose there's plenty of room there to at least add a back and a pause button.

There's also the issue that it has a white background when in its simple form, and when expanded it has a black background, perhaps you also opened that ticket.

**Comment by marcelinkaaa** [comment]
I will look into the background color changes. 

So few options: 
Small player:
- we should at least have 1, 2
- in most players - clicking on 'x' pauses the song - and gets rid of the notification. It would be great if that 'x' was used the same way as long press on 'play' in the player - meaning it would stop the player entirely and exit the notification. 
- if we close the player by swiping the notification to the right of the screen, we could also do what is on screenshot nr. 3. Or replace the track back for 'heart' to favorite the song (if we have the data that would suggest that users like favoriting the songs on the player; its the action that is used often)

Big player:
- change the color of the background nr.4
- 5 is just something I seen once - I dont think its necessary so would stick with 4 unless its super easy to accomplish
- 6 - would prefer that one if we can prove that favorites is used widely by the users. 

1
![1](https://cloud.githubusercontent.com/assets/2339972/20351338/6e41f824-abe0-11e6-9dad-d87143f010b7.png)
2
![2](https://cloud.githubusercontent.com/assets/2339972/20351339/6e44c752-abe0-11e6-822a-9a37dc8dbf21.png)
3
![3](https://cloud.githubusercontent.com/assets/2339972/20351341/6e45d41c-abe0-11e6-85d2-b015e51b9595.png)
4
![4](https://cloud.githubusercontent.com/assets/2339972/20351343/6e478794-abe0-11e6-83c9-c1cb29f44695.png)
5
![5](https://cloud.githubusercontent.com/assets/2339972/20351340/6e45e952-abe0-11e6-950a-658e33c8869a.png)
6
![6](https://cloud.githubusercontent.com/assets/2339972/20351342/6e465a2c-abe0-11e6-8165-c7ba6ee13bdb.png)

**Comment by marcelinkaaa** [comment]
Hello. So upon looking a bit closer I noticed that there already is pause icon. There was a little mess in the sizes of the icons so upon suppling different sizes the pause because visible again and fully functional. 

![screenshot_20161116-215702](https://cloud.githubusercontent.com/assets/2339972/20374730/8e914d42-ac48-11e6-9991-7d85a642a1b6.png)
![screenshot_20161116-215726](https://cloud.githubusercontent.com/assets/2339972/20374731/8e91512a-ac48-11e6-904a-580cedf0689a.png)
