### ISSUE TITLE
[android] Lockscreen playback notification has no controls

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#252]
Samsung S5 Android 6.0.1

![device-2016-11-16-122508](https://cloud.githubusercontent.com/assets/2766994/20345556/fcc9826c-abf7-11e6-9270-118bfda346ca.png)

Ukryta zawartość = hidden content

**Comment by gubatron** [comment]
what do you suggest we do here?

Should we just make it unavailable when the screen is locked, thus protecting the user's privacy?

**Comment by gubatron** [comment]
CC: @marcelinkaaa

**Comment by grzesiekrzaca** [comment]
Well, I'd at least add the pause button - The music is still playing (So protecting the user's privacy by not displaying what is playing is weird). We need to unlock the screen to change that (and that's a hassle if someone has an elaborate swipe pattern).

**Comment by marcelinkaaa** [comment]
@grzesiekrzaca Check your settings. Some content like messages is hidden on lock screen for privacy. It could be similar with players. On my phones I am getting the standard player we have (although I agree the player itself could have more options - I will upload what I mean to your ticket about that).
![screenshot_20161116-073816](https://cloud.githubusercontent.com/assets/2339972/20347631/1a93df40-abd0-11e6-9aee-05eb399fae82.png)

**Comment by grzesiekrzaca** [comment]
Yeah, I guess it's the android version thing and they changed something in permissions again. I can see other players on my lock screen just fine. Which android do you have?

**Comment by marcelinkaaa** [comment]
HTC M8 and LG Nexus - both running Android 6

**Comment by grzesiekrzaca** [comment]
Hmm, weird. All other players (default Samsung one and MX Player)  have normal controls in the notification on the lockscreen but FW notifications have their contents hidden.

**Comment by marcelinkaaa** [comment]
I just downloaded bunch of other players and all of them are open on lockscreen including FW. 
Will ask others what they have. Maybe its phone related only or maybe something with permissions on our end?

**Comment by gubatron** [comment]
Thank you for noticing, suggesting and fixing this issue @grzesiekrzaca 
![thanks-bow](https://cloud.githubusercontent.com/assets/163977/20410964/c0b9be14-acdc-11e6-99e9-49c44dcdc830.gif)
