### ISSUE TITLE
[android] Expanded notification has different background color

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#253]
![screenshot_20161116-051046](https://cloud.githubusercontent.com/assets/163977/20346750/251e23e0-abbb-11e6-967b-c98c8a7a34ec.png)

![screenshot_20161116-051057](https://cloud.githubusercontent.com/assets/163977/20346754/2a54c7e2-abbb-11e6-9f37-ed43cf46e40d.png)

**Comment by marcelinkaaa** [comment]
Fixed. PR created. 

![screenshot_20161116-215726](https://cloud.githubusercontent.com/assets/2339972/20374671/25e6b700-ac48-11e6-8583-6662e98b4dc2.png)
