### ISSUE TITLE
[android] Transfer screen actionbar has action item that does nothing when there are no transfers 

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#264]
1a) Fresh install of the app
or
1b) Clear all transfers
2) Navigate to transfers screen
is:
The additional actions action item (3 dots) is visible on the actionbar but clicking it does nothing
expected:
It's shown only when there is an action to take.

**Comment by marcelinkaaa** [comment]
Yes. Do agree about that.
