### ISSUE TITLE
[android] Click 'Remove Torrent and Data' for a Torrent file with status 'Finished' or 'Seeding' - The file remains on My Files temporally 

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#274]
To reproduce this issue:

1)  Go to the Transfer list and select a Torrent file with status 'Finished' or 'Seeding'

2)  Click the option 'Remove Torrent and Data'

4)  Go to 'My Files > My Torrents' and you will see the file remains on the list of torrents

5) Try to select the file and FW will say: 'The file was deleted from the SD card, or the SD card you have inserted is a different one':

![screen shot 2016-07-25 at 5 28 37 pm](https://cloud.githubusercontent.com/assets/1534723/17118102/4a376bc8-528d-11e6-99a0-b6da94ed8453.png)

If you go to Storage Location you won't find the Torrent so it should be fixed refreshing My Files after canceling and deleting the data.

This issue is related to: https://github.com/frostwire/frostwire/issues/273

**Comment by gubatron** [comment]
this is one annoying bug. confirmed this today when testing the new feature to remove .torrent files when transfers start. The .torrent file isn't there but it keeps appearing on the adapter. gotta take a look at how .torrent files are fetched, if we have a custom table fetcher or something.

**Comment by aldenml** [comment]
Should be fixed with https://github.com/frostwire/frostwire/commit/624ccaf027e8e4715f73b4d2e94d1eab2e849120

**Comment by muckachina** [comment]
_Tested on FW 2.0.2-build-497 on android 6 and 7
Files saved within SD card and Internal Memory_

I cannot reproduce it again with the files I had in Transfer... The 'zombie' torrents that remained there before were from pretty old builds, I remember trying this in January https://github.com/frostwire/frostwire/issues/620 and I could see these 'zombies' around but since I don't have old data in Transfer for the latest builds I could say is fixed.

Closing here unless I can find a particular scenario where I can reproduce.
