### ISSUE TITLE
Compile time errors

### ISSUE THREAD

**Issue by unnivm** [frostwire/frostwire#29]
Today I downloaded the ;latest source code for frostwire-common  repository and set up in Eclipse IDE. with other dependent jar files. But I am getting compile time errors as. One such file is 

 com.frostwire.bittorrent.BTDownload.java -> 
private void serializeResumeData(SaveResumeDataAlert alert) {
        try {
            if (th.isValid()) {
                String infoHash = th.getInfoHash().toString();
                File file = engine.resumeDataFile(infoHash);

                Entry e = alert.resumeData(); // getting compile time error as this method is not available

                e.getSwig().dict().set(EXTRA_DATA_KEY, Entry.fromMap(extra).getSwig());

                FileUtils.writeByteArrayToFile(file, e.bencode());
            }
        } catch (Throwable e) {
            LOG.warn("Error saving resume data", e);
        }
    }

Please let me know if I need to download any other jar files

Thanks 

Unni

**Comment by gubatron** [comment]
`frostwire-common` has been phased out, it is now in this repository under the `/common/`
 folder.

are you trying to build for desktop or for android?

Have you tried to build from the command line using `gradle build` from the root folder?

**Comment by unnivm** [comment]
Hello Angel,

I am building for Desktop and added just now other dependencies (like
jaudiotagger, commons etc).

I am not building through Gradle. I have ported all the source code to my
Eclipse project folder. I have taken the latest jlib-torrent jar file as
well.

Is it mandatory to build it using "Gradle" ?

Now I have 3 compile time errors in my IDE.

Yours Sincerely,
Unni M





On Wed, Dec 23, 2015 at 9:16 PM, Angel Leon <notifications@github.com>
wrote:

> frostwire-common has been phased out, it is now in this repository under
> the /common/
> folder.
>
> are you trying to build for desktop or for android?
>
> Have you tried to build from the command line using gradle build from the
> root folder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frostwire/frostwire/issues/29#issuecomment-166927244>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by gubatron** [comment]
I suggest you use an eclipse/gradle plugin to simplify your development
process, otherwise you'll have to read how we've set up the build and
libpath on the gradle script and add all these dependencies manually in
eclipse.

http://twitter.com/gubatron

**Comment by unnivm** [comment]
The only error I am getting from jlibtorrent as couple of methods are not
matching. Btw, could you please tell me what are the jar files are required
for in Gradle other than the one mentioned in front page of
https://github.com/frostwire/frostwire/tree/master/desktop


Yours Sincerely,
Unni M

On Wed, Dec 23, 2015 at 9:36 PM, Angel Leon <notifications@github.com>
wrote:

> I suggest you use an eclipse/gradle plugin to simplify your development
> process, otherwise you'll have to read how we've set up the build and
> libpath on the gradle script and add all these dependencies manually in
> eclipse.
>
> http://twitter.com/gubatron
>
> On Wed, Dec 23, 2015 at 10:55 AM, unnivm <notifications@github.com> wrote:
>
> > Hello Angel,
> >
> > I am building for Desktop and added just now other dependencies (like
> > jaudiotagger, commons etc).
> >
> > I am not building through Gradle. I have ported all the source code to my
> > Eclipse project folder. I have taken the latest jlib-torrent jar file as
> > well.
> >
> > Is it mandatory to build it using "Gradle" ?
> >
> > Now I have 3 compile time errors in my IDE.
> >
> > Yours Sincerely,
> > Unni M
> >
> >
> >
> >
> >
> > On Wed, Dec 23, 2015 at 9:16 PM, Angel Leon <notifications@github.com>
> > wrote:
> >
> > > frostwire-common has been phased out, it is now in this repository
> under
> > > the /common/
> > > folder.
> > >
> > > are you trying to build for desktop or for android?
> > >
> > > Have you tried to build from the command line using gradle build from
> the
> > > root folder?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/frostwire/frostwire/issues/29#issuecomment-166927244
> > >.
> > >
> >
> >
> >
> > --
> > ---
> > If not played, Free Sudoku Android Game
> > <https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/frostwire/frostwire/issues/29#issuecomment-166929899
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frostwire/frostwire/issues/29#issuecomment-166932484>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by aldenml** [comment]
@unnivm what version of jlibtorrent did you copy

**Comment by unnivm** [comment]
Hello Alden,

The version I am using is jlibtorrent-1.1.0.15.jar

Yours Sincerely,
Unni M

On Wed, Dec 23, 2015 at 9:53 PM, Alden Torres <notifications@github.com>
wrote:

> @unnivm <https://github.com/unnivm> what version of jlibtorrent did you
> copy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frostwire/frostwire/issues/29#issuecomment-166935904>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by gubatron** [comment]
that's the one I was going to suggest
http://search.maven.org/remotecontent?filepath=com/frostwire/jlibtorrent/1.1.0.15/jlibtorrent-1.1.0.15.jar

**Comment by unnivm** [comment]
Let me try with this and shall update you.


Yours Sincerely,
Unni M

On Wed, Dec 23, 2015 at 9:56 PM, Angel Leon <notifications@github.com>
wrote:

> that's the one I was going to suggest
>
> http://search.maven.org/remotecontent?filepath=com/frostwire/jlibtorrent/1.1.0.15/jlibtorrent-1.1.0.15.jar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frostwire/frostwire/issues/29#issuecomment-166936517>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by unnivm** [comment]
I am still getting the same error with this version of jar file.

Yours Sincerely,
Unni M

On Wed, Dec 23, 2015 at 10:04 PM, unni mana <unnivm@gmail.com> wrote:

> Let me try with this and shall update you.
>
>
> Yours Sincerely,
> Unni M
>
> On Wed, Dec 23, 2015 at 9:56 PM, Angel Leon <notifications@github.com>
> wrote:
>
>> that's the one I was going to suggest
>>
>> http://search.maven.org/remotecontent?filepath=com/frostwire/jlibtorrent/1.1.0.15/jlibtorrent-1.1.0.15.jar
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/frostwire/frostwire/issues/29#issuecomment-166936517>
>> .
>>
>
>
>
> --
> ---
> If not played, Free Sudoku Android Game
> <https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>

**Comment by aldenml** [comment]
you should have another version of jlibtorrent in your classpath. Can you post the classpath of your eclipse project (.classpath file)?

**Comment by unnivm** [comment]
Yes that was right, there was a different version of jlibtorrent was there.
The previous one, Now this issue can be closed,

Thank you for your timely help and cooperation.

Yours Sincerely,
Unni M

On Wed, Dec 23, 2015 at 10:28 PM, Alden Torres <notifications@github.com>
wrote:

> you should have another version of jlibtorrent in your classpath. Can you
> post the classpath of your eclipse project (.classpath file)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frostwire/frostwire/issues/29#issuecomment-166944400>.
>



-- 
---
If not played, Free Sudoku Android Game
<https://play.google.com/store/apps/details?id=com.gamerfan.sudoku>
