### ISSUE TITLE
[desktop/(possibly common)] Issues saving tracker list when creating new torrent

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#294]
Create a torrent and add a tracker or trackers.
Start the transfer with that .torrent, then right click on the transfer and look at the trackers

I tried creating a torrent with `http://tracker.frostwire.com:6969/announce` twice, this is what I got

![screen shot 2016-12-12 at 12 03 16 pm](https://cloud.githubusercontent.com/assets/163977/21112537/5638be38-c063-11e6-8030-2e09a41fb116.png)
![screen shot 2016-12-12 at 12 00 03 pm](https://cloud.githubusercontent.com/assets/163977/21112538/563a8038-c063-11e6-984a-d7744b7366f1.png)

If I remember correctly, someone had reported something similar on the jlibtorrent issue tracker

**Comment by aldenml** [comment]
yes, same issue, I may have to hurry the next release of jlibtorrent

**Comment by gubatron** [comment]
confirmed that it's on the creation. Created the same torrent on another client, and I can see the tracker list fine on desktop.

Thanks.

**Comment by aldenml** [comment]
This particular issue is fixed in the next release of `jlibtorrent`, but I just found another one related to trackers and resume file.

**Comment by aldenml** [comment]
I fixed the new issue, this should be tested and closed in the next release.
