### ISSUE TITLE
[desktop] Frostwire VS qBittorrent Speed

### ISSUE THREAD

**Issue by 0vermind** [frostwire/frostwire#30]
Hi guys, we are another opensource project willing to contribute to frostwire project.
We tested Frostwire versus other clients using libtorrent core library. We tested Frostwire VS Qbitorrent speed. The two clients should perform identically on paper, but as our tests reveal this is not happening.
In the 50% of cases, Frostwire was slower than Qbittorrent.
We would like to know if your team is willing to address the issue in the future.
Keep the great work!

Here are the tests: https://docs.google.com/spreadsheets/d/1au_M1NJQTz8tr9asoQk5U6SVcq-_NJtxZFqfjO2exxs/edit?usp=sharing5
As You can see, all test in red background means that Frostwire was slower than Qbit.
All green lines are were Frostwire was faster :smile:
All test have a magnet link to reproduce the results.
p.s. ask me if yo need access to modify the datasheet.

**Comment by gubatron** [comment]
Cheer @0vermind thanks for the initiative of putting these tests together.

We work everyday to make jlibtorrent and FrostWire as fast as we can.

Did you perform the tests using the libraries, or simply using the final product?

Were the downloads done simultaneously? (meaning, did you have both QBittorrent and FrostWire downloading at the same time, or were you downloading first with a client, then waited and then the other downloaded)

Please tell us more in detail how the benchmarks were made, network conditions can vary, and the results can also be read as "50 of cases, FrostWiire was faster than QBittorrent" :)

It'd be cool if we worked together on designing a test that would just benchmark the core libraries, which would measure things like, the time it took to fetch a torrent on the dht, the time to start downloading, the number of peers connected, how much bandwidth was also spent on sharing pieces, perhaps during one of those downloads that either or was faster or slower than the other somebody came and sucked away upstream bandwidth that could've been used for control/protocol.

I think we need to think a bit harder how to make more objective tests.
A better test I think would be, we 2 .torrents that index the same 4GB file, the only difference in each torrent would be the tracker used, or perhaps we add a second file of just 1KB that makes these 2 torrents differ.

Then you grab 1 torrent and you give it to 20~50 QBittorrent peers and we test how fast is it for all those peers to become full seeds, and then the other torrent and we run FrostWire on them and make the same test.

**Comment by 0vermind** [comment]
Thanks @gubatron, our team is willing to help.
Tests were performed using the final product for desktop.
Of course there was no simultaneous downloads and only one client open per time.
Every tester downloaded the same magnet first with Frostwire, and then with qBitorrent.
So all environment conditions were the same, like line, torrent etc
Each team member tested twice and the only variable was the different client used. (time windows was the same for both tests)
> Please tell us more in detail how the benchmarks were made, network conditions can vary, and the results can also be read as "50 of cases, FrostWiire was faster than QBittorrent" :)

You are right, that another way to see it :P

> It'd be cool if we worked together on designing a test that would just benchmark the core libraries, which would measure things like, the time it took to fetch a torrent on the dht, the time to start downloading, the number of peers connected, how much bandwidth was also spent on sharing pieces, perhaps during one of those downloads that either or was faster or slower than the other somebody came and sucked away upstream bandwidth that could've been used for control/protocol.

We are also interested in these Info. Our next step will be testing the DHT in functionality and effectiveness in finding sources. We come from kademlia DHT, which is very efficient.
From Tests our team noticed that FRW is double effective in load sources than competitors. 
This advantage unfortunately is lost somehow, FRW does maintain them. 
In the log run (we should make more objective tests) FRW is always increasing sources constantly :smile: but is like it doesn't use them.
If you design specific tests we will make them.

**Comment by gubatron** [comment]
regarding the sources, perhaps it's something that we need to tune out, we def. need some help, so many things going on with the different OS releases that it's hard to handle for such a small team.

I'd like the tests to be done if possible in a completely controlled environment so things can be measured better, e.g. an unpublished .torrent to which we know the only peers are our computers.

Thank you.

**Comment by sam201401** [comment]
i am an enduser i wanted to use frostwire as client but i observe that frostwire is giving me only 500KiB/s
as average speed but qbitorrent is giving me 2MB/s averge speed (on same magnet link) 
my internet plan is 5 MB/s plan 
@0vermind @gubatron @frostwire  can u tell us why this is so

**Comment by gubatron** [comment]
@sam201401 you might want to check your Torrent settings, perhaps you need to adjust the number of connections.

Tests and patches are welcome. Thanks so much for interesting in the tunning aspect, perhaps you guys can find an even better set of options.

Please [take a look at this file](https://github.com/frostwire/frostwire/blob/master/common/src/main/java/com/frostwire/bittorrent/BTEngine.java#L427), this is where we setup the default values, perhaps you'd like to compare it with that of [QBittorrent's default settings](https://github.com/qbittorrent/qBittorrent/blob/master/src/base/preferences.cpp#L838), and then we can fix it so they're the same and we can make better comparison tests.

Perhaps you can write down their default settings and then send us a Pull Request after you make tests adjusting our default values.
