### ISSUE TITLE
[android/discussion] Towards material design, BrowsePeerFragment and ongoing work.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#304]
I believe we've started moving most activities so that they can make use of newer APIs by extending from `AbstractActivity2`.

So far I believe we have:
 - `SettingsActivity`
 - `BuyActivity`
 - `AboutActivity`

We need:
 - `WizardActivity` (should be easy peasy)
 - `MainActivity` (not so easy)

Once we have all of them going if nobody else is extending from the old `AbstractActivity`, we will remove it, and then rename `AbstractActivity2` to be the new `AbstractActivity`.

Once we have this, we should then proceed to replace all our current `ActionBar` based headers and use the newer and more flexible `Toolbar`, toolbar allows us to add custom views in XML and we can put them inside the activity layouts or view layouts, they're not some obscure component we have to hack the crap out of.

Once we have finished refactoring all this actionbar based code, then we should try to merge the code on master into @grzesiekrzaca's branch, I predict this will be very hard to make, but it should be possible. 

I believe the code in that branch can logically be seen in two efforts. 
There's been (or will be) behavior changes in terms of how we now get to the "checkbox mode". 

The user experience to bring the checkboxes in and out should be as follows:
- Upon long press
- Using the little checkbox item at the top (which could go away in a few months, we could for instance teach users that they can bring out checkbox mode with a long press, using a toast message 50% of the times they use the checkbox button, a nagging tip I think would eventually let them know the checkboxes also work like in most picture viewers and file browsers

and then there's the local filtering code, which went away from the old filtering search bar and moved onto the `actionBar`, I think this filtering code should be merged last, perhaps on another pull request, and ideally, that part of the code would now interact with what our new `MainActivity` which now would be extending the Material Design friendly `AbstractActivity` and its new `toolbar`

what do you guys think?

**Comment by aldenml** [comment]
I think the above is a very good outline of the next steps.

To repeat, the move to material with the new Toolbar is before anything else, starting from completing `SettingsActivity2`.

The migration of `MainActivity` can be done with the following steps:

- Inherit from `AbstractActivity2` and try to put the header from `MainFragment`s to achieve the exact feature and L&F we have right now. This is important in order to have an organized evolution of the UI.
- Migrate the "apollo" activities to use the `AbstractActivity2`.
- Change the L&F of the "main toolbar"

Then we can move to the implementation of the checkboxes and search input in the toolbar. This latest task is a good opportunity to revisit some architectural decisions.

**Comment by grzesiekrzaca** [comment]
Well if we touch MainActivity then maybe we could also think about making it lighter? One thing to try would be creating fragments as they are needed. Also just running a profiler and getting to know where the bottlenecks are. 

So I understand that the changes to My Files should wait before this (switching to `AA2`) is done? 

and another question: should I split the check logic and filtering logic into separate branches? Leave the old search box without the check box and remove the filtering from the ActionBar?

**Comment by grzesiekrzaca** [comment]
Also, I pushed changes to long press and the toast to my branch (added another toast when user long presses a ringtone).

**Comment by marcelinkaaa** [comment]
Sounds like a good plan! The AboutActivity and BuyActivity are fully transitioned. I just submitted a pull request to the WizardActivity. 

All we need now is making sure all the set up preferences in Settings work properly. 
I am giving this one to grzesiek, as I want him to see what we can do to clean the code up and he will be a much better judge of that. All layouts, design, etc. is there. Hopefully by early next week we shall have that done and we can fully focus on the MainActivity and Apollo (which I am guessing will be a lot of work as well)

**Comment by gubatron** [comment]
is there a branch where we can see the progress of `SettingsActivity2`?

**Comment by grzesiekrzaca** [comment]
#311
