### ISSUE TITLE
Set a time interval for downloading [Feature Request] [enhancement] 

### ISSUE THREAD

**Issue by eliaharm** [frostwire/frostwire#31]
Hello, i was looking for an Android torrent app that allows limiting download time between 12:00 am and 6:00 am because my ISP allowes unlimited quota duting that time. I think it should be an easy option to add and that many might benefit from it. 
Thanks and great application.

**Comment by gubatron** [comment]
If you turn off seeding, it will automatically pause (aka stop) right after the download is finished.
This also happens with HTTP downloads.

As for the idea to limit downloads between some time or another, for now all you have to do is very easy, your Android phone shows you what time it is on the top of the screen, just watch the times.
