### ISSUE TITLE
torrenthandle.movestorage deletes the ALL internal storage. if used with lolipopfilesystem.

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire#310]
i added log statement in delete function in lolipopfilesystem

and the last delete path was

`/storage/emulated/0`

**Comment by aldenml** [comment]
Thanks for the reporting, I will take a look at it.

**Comment by mianharisali** [comment]
@aldenml  thanks , it deleted all content on my mobile :( :(

**Comment by aldenml** [comment]
What was the save path of the torrent?

**Comment by mianharisali** [comment]
/storage/emulated/0/Torrents

and move location was 

/storage/emulated/0/New

**Comment by mianharisali** [comment]
no matter if we change the new location it always deleted the whole mobile content.

when i added log.d on 'file' location in "delete" function

no matter /storage/emulated/0 was always the last delete file.

**Comment by mianharisali** [comment]
android version = 7.1 
mobile = nexus 6p non rooted

Lolipopfilesystem with SAF.

**Comment by mianharisali** [comment]
1 more case.
lets say torrent path is 

/storage/emulated/0/Folder1/Torrent-Path

and we move the storage to another location

the delete function keeps on calling with paths like this

/storage/emulated/0/Folder1/Torrent-Path

/storage/emulated/0/Folder1

/storage/emulated/0

/storage/emulated

/storage

/

**Comment by aldenml** [comment]
wow..that's seems very problematic

**Comment by mianharisali** [comment]
these problem only occur if we move storage.
delete function works fine if we just delete torrent.

**Comment by gubatron** [comment]
q: is this a jlibtorrent issue? or a frostwire issue?

**Comment by mianharisali** [comment]
this issue is related to lolipopfilesystem or jlibtorrent.

**Comment by gubatron** [comment]
[Moved to jlibtorrent's issue tracker](https://github.com/frostwire/frostwire-jlibtorrent/issues/145)
