### ISSUE TITLE
[desktop] Browse All Downloads button

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#329]
Enhance promo display with a "Browse All Downloads" button that takes users to the FrostWire.com features page.

This has worked very well on Android and we'll be improving that page as well on frostwire.com

NOTE TO MYSELF:
![browse-all-downloads](https://cloud.githubusercontent.com/assets/163977/22117858/c71feb20-de32-11e6-9831-dbba24ea03b6.png)
 Use text "Browse All Downloads", instead of "All Free Downloads"

Thank you @marcelinkaaa

**Comment by gubatron** [comment]
![screen shot 2017-01-21 at 2 46 01 pm](https://cloud.githubusercontent.com/assets/163977/22178030/1b8a297a-dfe9-11e6-8cf7-35f1d7758bfc.png)

Check it out @marcelinkaaa  :)

**Comment by gubatron** [comment]
![screen shot 2017-01-21 at 2 52 41 pm](https://cloud.githubusercontent.com/assets/163977/22178035/477e48c2-dfe9-11e6-861b-ed314752a70b.png)

**Comment by marcelinkaaa** [comment]
Looks good. Browse all downloads sounds good. 
Will the button change sizes like on the last screenshot - looks a bit too large.

**Comment by gubatron** [comment]
im afraid it won't change sizes, but if you tell me what the minimum size should be I can pass those dimensions
