### ISSUE TITLE
[android] Settings > 'Use 3G/4G for BitTorrent' - Not working If I turn 'BitTorrent Connection' ON

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#340]
Tested with a SIM card for FrostWire 1.8.7 

Issue reference: https://github.com/frostwire/qa-android/issues/92 

**To reproduce**:

1) Go to FrostWire main menu Settings > Torrent Settings and un-select the option "Use 3G/4G for BitTorrent"

2) Make sure the BitTorrent connection is ON, if not then turned it ON

3) Disconnect your device from WiFi (leave only Data Plan active)

4) Search a file and start to download a TORRENT (no files from cloud), you will see the torrent goes to the Transfer list and start downloading although your Settings says "Do not use 3G/4G for BitTorrent downloads"

The last test Natalie and Alejandro did all files went to ‘Pause’ but after Exit and opening FW again all the files Resume and start downloading although there is no WiFi connection and 3G/4G is Off.

**Comment by grzesiekrzaca** [comment]
#338 and related #339

**Comment by muckachina** [comment]
Tested with a SIM card by @alejandroarturom  for FrostWire 1.8.8 - build 338 and is working properly now :)
