### ISSUE TITLE
[desktop] Testing Options > BitTorrent > Advanced > VPN-Drop-Protecction - Fails when connecting/disconnecting

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#355]
Tested from git - pre-release FrostWire 6.4.5 build 222

![screen shot 2017-02-22 at 7 33 40 pm](https://cloud.githubusercontent.com/assets/1534723/23239566/07b4bfb2-f936-11e6-9f3e-75a85ef81944.png)

> ‘**Resume**’ of Downloading files is not getting the Torrent again. I cannot reproduce the files ending in 'Error' but the **Seeds and Speed remain 0/0 and 0 KB/s** 

> ‘**Clear Inactive**’ is erasing the info of Files that were Seeding or Downloading too.

> FW crashes after trying to search and download files again on Windows. Log file already shared on Slack.

**Comment by gubatron** [comment]
Crash trace:
```
EDI=0x26d1e840 is pointing into the stack for thread: 0x26376c00


Stack: [0x26cd0000,0x26d20000],  sp=0x26d1e380,  free space=312k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jlibtorrent.dll+0xc96ff]
C  [jlibtorrent.dll+0x328c1]
j  com.frostwire.jlibtorrent.swig.libtorrent_jni.torrent_handle_status__SWIG_0(JLcom/frostwire/jlibtorrent/swig/torrent_handle;J)J+0
J 13957 C1 com.frostwire.jlibtorrent.TorrentHandle.status(Z)Lcom/frostwire/jlibtorrent/TorrentStatus; (50 bytes) @ 0x0304ec9c [0x0304eb90+0x10c]
J 13937 C1 com.frostwire.jlibtorrent.TorrentHandle.status()Lcom/frostwire/jlibtorrent/TorrentStatus; (6 bytes) @ 0x030a98a8 [0x030a9880+0x28]
j  com.frostwire.bittorrent.BTDownload.isFinished()Z+14
j  com.frostwire.gui.bittorrent.BittorrentDownload.isCompleted()Z+4
j  com.frostwire.gui.bittorrent.BTDownloadModel.getActiveDownloads()I+32
j  com.frostwire.gui.bittorrent.BTDownloadMediator.getActiveDownloads()I+7
j  com.limegroup.gnutella.gui.GUIMediator.getCurrentDownloads()I+4
j  com.limegroup.gnutella.gui.StatusLine.updateBandwidth()V+29
j  com.limegroup.gnutella.gui.StatusLine.access$000(Lcom/limegroup/gnutella/gui/StatusLine;)V+1
j  com.limegroup.gnutella.gui.StatusLine$2.refresh()V+15
j  com.limegroup.gnutella.gui.GUIMediator.refreshGUI()V+29
j  com.limegroup.gnutella.gui.RefreshTimer.refreshGUI()V+3
j  com.limegroup.gnutella.gui.RefreshTimer.access$000(Lcom/limegroup/gnutella/gui/RefreshTimer;)V+1
j  com.limegroup.gnutella.gui.RefreshTimer$1.actionPerformed(Ljava/awt/event/ActionEvent;)V+4
j  javax.swing.Timer.fireActionPerformed(Ljava/awt/event/ActionEvent;)V+34
j  javax.swing.Timer$DoPostEvent.run()V+74
J 4661 C1 java.awt.event.InvocationEvent.dispatch()V (69 bytes) @ 0x031f255c [0x031f2470+0xec]
J 4808 C1 java.awt.EventQueue.dispatchEventImpl(Ljava/awt/AWTEvent;Ljava/lang/Object;)V (149 bytes) @ 0x0327ab4c [0x0327a3d0+0x77c]
J 4287 C1 java.awt.EventQueue$3.run()Ljava/lang/Void; (60 bytes) @ 0x0305fc1c [0x0305fbc0+0x5c]
J 4286 C1 java.awt.EventQueue$3.run()Ljava/lang/Object; (5 bytes) @ 0x0315fe60 [0x0315fe40+0x20]
v  ~StubRoutines::call_stub
V  [jvm.dll+0x15a6e5]
V  [jvm.dll+0x2204fe]
V  [jvm.dll+0x15a77e]
V  [jvm.dll+0x10ac3f]
C  [java.dll+0x102f]
J 4806 C1 java.awt.EventQueue.dispatchEvent(Ljava/awt/AWTEvent;)V (80 bytes) @ 0x0327bc08 [0x0327ba00+0x208]
J 1289 C1 java.awt.EventDispatchThread.pumpOneEventForFilters(I)V (295 bytes) @ 0x0322bd90 [0x0322b700+0x690]
j  java.awt.EventDispatchThread.pumpEventsForFilter(ILjava/awt/Conditional;Ljava/awt/EventFilter;)V+35
j  java.awt.EventDispatchThread.pumpEventsForHierarchy(ILjava/awt/Conditional;Ljava/awt/Component;)V+11
j  java.awt.EventDispatchThread.pumpEvents(ILjava/awt/Conditional;)V+4
j  java.awt.EventDispatchThread.pumpEvents(Ljava/awt/Conditional;)V+3
j  java.awt.EventDispatchThread.run()V+9
v  ~StubRoutines::call_stub
V  [jvm.dll+0x15a6e5]
V  [jvm.dll+0x2204fe]
V  [jvm.dll+0x15a77e]
V  [jvm.dll+0x15a906]
V  [jvm.dll+0x15a977]
V  [jvm.dll+0xfed1f]
V  [jvm.dll+0x17d210]
V  [jvm.dll+0x17da8a]
V  [jvm.dll+0x1c2506]
```

@aldenml Q:
The code in Java land (common) `BTDownload.isFinished()` is a single line that makes use of `th.status().isFinished()`

```java
public boolean isFinished() {
        return th.isValid() && th.status().isFinished();
}
```

jlibtorrent says something interesting though:
```
/**
     * `status()`` will return a structure with information about the status
     * of this torrent. If the torrent_handle is invalid, it will throw
     * libtorrent_exception exception. See torrent_status. The ``flags``
     * argument filters what information is returned in the torrent_status.
     * Some information in there is relatively expensive to calculate, and if
     * you're not interested in it (and see performance issues), you can
     * filter them out.
     *
     * @return the status
     */
    public TorrentStatus status() {
        return status(false);
    }
```

if the documentation is correct, the code in FrostWire's java land should short circuit before calling `th.status()` to avoid the throwing of that `libtorrent_exception`

If I remember correctly, the session should still be valid, as all I do is `pause()` it, I don't end it/destroy it. My guess so far is that I need to revise the logic of that `refresh()` to account for this possibility, but it'd be interesting to understand the crash in C++ land.

**Comment by grzesiekrzaca** [comment]
The Finished torrent are set to paused because in cpp part all torrents get `set_session_paused(true)` which causes `torrent::do_pause` when the `session` (through `BTEngine`) is paused. So the library would need to be changed to account for finished state and not touch it.

**Comment by grzesiekrzaca** [comment]
CNR on the crash (master, windows 10):
-Have the option On and VPN On, go to search screen, add something, transfers are open with that position added
-Have the option On and VPN Off, go to search screen, add something, transfers are open with alert window about VPN 
-Have the option On and VPN On, go to search screen and turn off VPN, add something, transfers are open with alert window about VPN

**Comment by muckachina** [comment]
@grzesiekrzaca  Here the initial steps to reproduce the issues:

**ISSUE #1 - Files not downloading after 'Resume'**

1) Make sure VPN-Drop feature is Off and a VPN is connected

2) Start downloading few torrents and make sure they go to transfer and start getting progress

3) Go to FrostWire main menu Tools > Options > BitTorrent > Advanced and turn ON the VPN-Drop feature

4) Check the files on Transfer keep downloading and the VPN-Shield-dot turns green

5) Turn OFF the VPN Service on your device

6) Go to FrostWire Transfer list and check all files are now 'Paused'

7) Try to 'Resume' any of the files. FrostWire will ask If you want to "Disable VPN-Drop protection" > say Yes

8) You will see the files on Transfer that were 'Downloading' are not getting progress and remain 0/0 KB/s


**ISSUE #2 - Clear Inactive deletes files that were Downloading/Seeding**

1) Make sure VPN-Drop feature is Off and a VPN is connected

2) Start downloading few torrents and make sure they go to transfer and start getting progress, wait till some of them remain 'Seeding'.

3) Go to FrostWire main menu Tools > Options > BitTorrent > Advanced and turn ON the VPN-Drop feature

4) Check the files on Transfer keep downloading and the VPN-Shield-dot turns green

5) Turn OFF the VPN Service on your device

6) Go to FrostWire Transfer list and check all files are now 'Paused'

7) Try to 'Resume' any of the files. FrostWire will ask If you want to Turn Off the 'VPN-Drop' protection > Select Yes

8) You should see files on Transfer with status 'Downloading' and other 'Seeding', then Select the button 'Clear Inactive' at the bottom of the Transfer list

9) You will see how files with status 'Seeding' and 'Downloading' disappear from the Transfer list


**ISSUE #3 FrostWire Crash**

1) Repeat all the steps on Issue #1 or #2

2) Go to Search screen and perform a search, you will see how FrostWire crashes

The great news is I tested from git and I couldn't reproduce any of these issues again on Windows any more :D I'll pull and test on Mac after lunch.

**Comment by muckachina** [comment]
Seems to be working properly on Mac too!! :) I've to test a bit more, updating ExpressVPN software right now.

**Comment by gubatron** [comment]
awesome, I think this feature will make it to our next desktop release then.

**Comment by aldenml** [comment]
and what was the root of the crash?

**Comment by gubatron** [comment]
I believe it was an unexpected state of the bittorrent engine.
We had a BTEngine.instance().restart() there, greg changed it to .resume() (from paused()) and the crash went away.

**Comment by grzesiekrzaca** [comment]
I think we should be very wary of .restart(); It's not used in the project and that one second wait time is not great.  With the problems with setting up Clion I wasn't testing if it's a problem from stop() while in paused state or with that wait time beeing too short.

**Comment by aldenml** [comment]
The _root_ of the problem is that `SessionManager#restart()` destroy and deletes the internal `libtorrent` session (that's by design). Once the internal native session is destroyed, all torrents are destroyed, and you end up with a set of torrent handlers with expired weak references (by design too). If you protect all calls to `status()` with `is_valid()` you will not have the crash.

Now, I do think `stop()`, `start()`, `restart()` should be used (at the expense of more mutability) since a lot of networking (DHT, LSD, name resolution, etc..) could still be working if only `pause()`, `resume()` is used. Also, a have some doubts on the interface binding if not restart is done, and what happens if more than one interface is Up.

**Comment by grzesiekrzaca** [comment]
```
public boolean isFinished() {
        return th.isValid() && th.status().isFinished();
}
```
&& is logical so it should not evaluate `th.status().isFinished()` if `isValid()` returned `false`, right?
Can `isValid()` return `true` if it is not valid due to session beeing destroyed?

**Comment by aldenml** [comment]
If they are in parallel, yes. The UI refresh runs in a different thread than the internal `libtorrent` one, and the destroy is async.

**Comment by muckachina** [comment]
I cannot reproduce any of these issues on FrostWire 6.4.7:
