### ISSUE TITLE
[android/music player] Equalizer option menu bug 

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#357]
Jan 24 2016

Tested on: **Samsung S3 Android 4.3, SGH-T399 4.2.2**
FrostWire for Android **version 1.7.0 (build 232) Basic & Plus**
Screen: **Player menu** 
Test: **Test player menu equalizer"**
**Ref. P-M4**

**Observations:**

The equalizer is not being displayed when playing a song.

--
March 02 2016

Updating issue for FrostWire 1.7.1 (build 237) now tested on Lollipop devices too:

The Equalizer of the device (no a FW integrated equalizer) is displayed only on devices that has Audio Settings option...

So, the issue here is the 'Equalizer' option of FrostWire should appear inactive if the device does not offer that setting, otherwise it seems FW offers an Equalizer that does not work.
--

See `AudioPlayerActivity.java`
https://github.com/frostwire/frostwire/blob/master/android/apollo/src/com/andrew/apollo/ui/activities/AudioPlayerActivity.java#L321

https://github.com/frostwire/frostwire/blob/master/android/apollo/src/com/andrew/apollo/ui/activities/AudioPlayerActivity.java#L393
--
Aug 3 2016
This issue persists on FrostWire 1.7.9 (build 293)

An 'Equalizer' option is displayed only on Android 4.2.2 device and on Android 6 and 5 the option is not displayed even if I install an app that offers 'Equalizer'.
--
Feb 23 2017

This issue persists on FrostWire 1.8.9 - build 242.

On Android 4.2 and 4.3 go to:

My Music > Album / Artists / Recent > Select a song > display the list of songs > click at the top right menu > Equalizer
This option is not opening the Equalizer on the device.

On Android 5 and 6:

Equalizer option is not available although I installed an Equalizer app on the device.

CC: @votaguz

**Comment by votaguz** [comment]
https://github.com/frostwire/frostwire/pull/358

**Comment by aldenml** [comment]
To close when tested in QA

**Comment by gubatron** [comment]
@muckachina please test this one

**Comment by muckachina** [comment]
Sorry I'm late testing this one, I saw it last Monday... is Fixed!! :D 

Tested on **Android 4.2** with an equalizer by default and the option appears on the menu as it was before. The equalizer opens with no issues.

On **Android 5 and 6** I installed an external equalizer-app and the option appeared on FW file-menu and the equalizer opens working properly with FW player. 

Thank you thank you!
