### ISSUE TITLE
[android/player] Add Chromecasting support

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#362]
We already have the drawables for this:
`ic_menu_cast` 
![ic_menu_cast](https://raw.githubusercontent.com/frostwire/frostwire/master/android/res/drawable-hdpi/ic_menu_cast.png)
and 
`ic_menu_cast_active`
![ic_menu_cast_active](https://github.com/frostwire/frostwire/blob/master/android/res/drawable-hdpi/ic_menu_cast_active.png?raw=true) 

We will make the cast icon available on the action bar of the player window, like this:

![cast_available](https://cloud.githubusercontent.com/assets/2339972/19944331/cf89b5ba-a111-11e6-9ef1-a7f36e98da9e.png)

![cast_enabled_blue](https://cloud.githubusercontent.com/assets/2339972/19949328/699909c0-a127-11e6-8988-7ba5caeb0cf6.png)

(Not sure yet, but maybe it will be a good idea to have a third icon that is displayed while the connection is being established, I've seen this on iOS apps like Google Music during the seconds it takes to start casting)

After we've managed to add this to the player screen, we'll also add it to the preview screen (for both audio/video casting)

**Comment by trollmad3** [comment]
Is there a way to add Chromecast to this? I can't find any tutorials to do this.

**Comment by gubatron** [comment]
I believe we had a contributor try to do this in the past, the process I
believe wasn't as straightforward as we wished

https://developers.google.com/cast/docs/developers

**Comment by trollmad3** [comment]
that seems very hard to do.
