### ISSUE TITLE
[android] ImageViewerFragment

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#368]
### Interactions:
- If you touch the image, it goes full screen.
- If you are on full screen and you touch it it goes back to initial state.
- If you touch or drag up the "I" (information) icon, you get more information. Touch the icon again or drag the drawer back down to hide it.

### Missing in screenshot

Somewhere on the information section we should have an icon for sharing.
We will rename the "Send/Upload" action to "Share". (This is like this today because "Share" in the past meant sharing with other FrostWire instances on the local network)

![future_my_files_images_image_preview_name](https://cloud.githubusercontent.com/assets/163977/23440419/19275e92-fdd9-11e6-987d-a356a9ccd9a6.png)
![future_my_files_images_image_preview_all_info](https://cloud.githubusercontent.com/assets/163977/23440425/2149d5e6-fdd9-11e6-93f2-d3cd99c3acf3.png)

**Comment by aldenml** [comment]
I like this

**Comment by gubatron** [comment]
@marcelinkaaa has started working on this.

CC: @votaguz @grzesiekrzaca

**Comment by aldenml** [comment]
@marcelinkaaa are you working this in another branch? using `ImageViewerFragment`?

**Comment by marcelinkaaa** [comment]
I removed my branch. It was just a test branch. I could not fully understand the current code, how, at this moment, do we show the image files, and how do we open them with outside app. 
So no branch now.

**Comment by aldenml** [comment]
The current image preview is just a simple `openFile`, the rest is coming from the default app that handle the images.

**Comment by gubatron** [comment]
@marcelinkaaa we now have a layout for grid image adapter views, this guy has the background ImageView to show the picture, then, since these need to be checkable, we have an overlay with the checkbox, and optionally the file size that you added to that same layout.

To use this layout, I created a `View` class called `CheckableImageView` which hides away all the logic on how the checkbox layer is shown or not, it takes different click listeners (long click, click).

You basically want to see on `FileListAdapter` the `getView()` method, if the adapter is being used for a `ListView` it uses the `AbstractListAdapter`'s `getView()` logic, otherwise it calls a method that initializes the `CheckableImageView`, in this method you can see how we show the images.

**Comment by gubatron** [comment]
# TODO
 * Faster image loading for higher resolution images
 * Make the size of the play overlay button on video thumb parametrizable.
 * Make videos playable on a single touch if touched on the thumbnail.
 * When videos are in selection mode, hide overlay images on top of the thumbnail
 * Rest of the fragment's layout showing file properties.
