### ISSUE TITLE
[desktop] Create Torrent Dialog > Specify Piece Size

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#372]
Enhance the Create Torrent Dialog to have the following Capability (like in uTorrent)
![screen shot 2017-03-01 at 10 12 31 pm](https://cloud.githubusercontent.com/assets/163977/23493866/3f065cc8-fecc-11e6-843c-4771d5eda853.png)

The section that says "Tracking" in the current dialog should be renamed to:
"Torrent Properties"

and the "Piece size: <drop down>" should be towards the bottom, with the label aligned to the left on the left column, and the drop down as wide as it needs to (but not wider) and aligned to the left.

![screen shot 2017-03-01 at 10 14 12 pm](https://cloud.githubusercontent.com/assets/163977/23493926/a35c90b6-fecc-11e6-8923-8a773c3ec723.png)

Do you want to do this @votaguz ?

**Comment by votaguz** [comment]
👍

**Comment by aldenml** [comment]
👍

**Comment by votaguz** [comment]
Pull Request #373
