### ISSUE TITLE
[android] Add Telugu translation (75 million speakers)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#377]
Volunteers wanted to translate FrostWire to the Telugu Indian language, preferably native speakers.

This is the file to translate.
https://github.com/frostwire/frostwire/blob/master/android/res/values/strings.xml

**Comment by alejandroarturom** [comment]
On it today.

**Comment by gubatron** [comment]
![love the smell](https://user-images.githubusercontent.com/163977/39678475-c690cf58-514a-11e8-9c88-1b2594152c94.gif)
