### ISSUE TITLE
[android] My Music: Screen rotation bug

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#384]
To reproduce:
1. Go to my music.
2. Rotate screen
3. All contents dissapear.
4. Rotate back and try to switch tabs, tabs behave weird.

Not sure if this happened after material design work or after cleanup.

**Comment by gubatron** [comment]
@votaguz you said you wanted a ticket, perhaps you can take a look and figure out what's the problem.

**Comment by votaguz** [comment]
This bug is fixed in commit https://github.com/frostwire/frostwire/commit/05949b68ea06cbfc569b98d51e44a2751866f8fa

**Comment by gubatron** [comment]
![love the smell](https://cloud.githubusercontent.com/assets/163977/23738067/12688532-0454-11e7-8438-6a17611aa91a.gif)
