### ISSUE TITLE
[android] Player > Long press on Song > Menu has no icons

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#387]

**Comment by marcelinkaaa** [comment]
I will look at it again today, but I had a hard time with finding a right way to do this as I said before. This happens in other sections of My Music as well, on long press. Context menu as stated do not support icons. https://developer.android.com/reference/android/view/ContextMenu.html

**Comment by aldenml** [comment]
Done with https://github.com/frostwire/frostwire/commit/46f2ab824f250cfd4ee3eda9f56d224ad5989816

@marcelinkaaa I need you to take care of the icons, see https://github.com/frostwire/frostwire/commit/46f2ab824f250cfd4ee3eda9f56d224ad5989816#diff-06a97ed34f25645106d0de9a97651e43R237
