### ISSUE TITLE
[android] add selected background to My Files selection mode

### ISSUE THREAD

**Issue by marcelinkaaa** [frostwire/frostwire#408]
When in selection mode, anywhere in the app we should apply the same styling. In Settings -> Search engines we are using a light grey background for the selected items. I wanted to add the same to My Files -> Select All mode. 

I tried and failed. Can someone help? It's probably super simple. 

![checks](https://cloud.githubusercontent.com/assets/2339972/24334545/3ca764de-1229-11e7-8631-aef355ade7c6.jpg)

**Comment by aldenml** [comment]
I'm afraid it's not super simple

**Comment by marcelinkaaa** [comment]
@aldenml @gubatron  I do want the design to remain consistent in selection mode in different parts of the app, but after a day spent on trying to do this, I am giving up for now. Any pointers, clues on how to proceed?
I was able to make it happen by adding v.setSelected(true) to onFileItemClicked(View v), in order to activate the background selector but there was still few issues, like the listView being recycled and the selected background being applies to multiple list items as you scroll. Or the checkbox being set up separately in view_selectable_list_item and the background not being added under the checkbox. 
The main issue though is with recycled views. As I am applying the selectable background to a view which is later reused by another item. And I am not sure how to make sure that the actual position is remembered. There are few similar issues people experienced but I was not able to successfully apply what I learned from their cases in FW. Would love your help.

**Comment by gubatron** [comment]
in order to avoid any issues with the recycled views I suppose you gotta do your background change on the adapter's `getView()`, that's where I'd change the background, depending if the current view in the list view being returned is selected or not.

**Comment by aldenml** [comment]
Test with master (https://github.com/frostwire/frostwire/commit/14662bade365c176fbd99466d8e04652c05bf207) and close if it's the expected
