### ISSUE TITLE
[android] hide favorite icon from the toolbar when the option is not active. My Music.

### ISSUE THREAD

**Issue by marcelinkaaa** [frostwire/frostwire#412]
Currently when player is not active and user is browsing My Music in tabs like Artists, Albums, Songs the favorite icon is in the toolbar but is not active. If you can not favorite something, the option should be hidden.

**Comment by gubatron** [comment]
https://github.com/frostwire/frostwire/commit/d6feab6f74c737a526b31f266bfaeacd69aa318d
