### ISSUE TITLE
[android] Inconsistent results from Bitsnoop

### ISSUE THREAD

**Issue by frostwire** [frostwire/frostwire#42]
Inconsistent results between individual audio results and .torrent results. (e.g. A single torrent result appears with 20 sources)

It's yet to be determined if this bug is just the behavior of the app when not connected to WiFi.
More testing to be done.

**Comment by frostwire** [comment]
@kad3mlia  please let us know here more as you test if we'll be able to close this or not without any fixes.

**Comment by kad3mlia** [comment]
Tested on Samsung S4/Android 5.0.1 with no SD Card. Downloading to Internal.
Sony Xperia Z2/ Android 5.1.1. Downloading to SD Card.
Happens only with BitSnoop only, but other sources might need more testing. Torrents from Kat, BTJunkie & TorLock did not have any issues.

When selecting a full torrent package for download, the file is marked in Search as downloaded, but does not show up in Transfers & the .torrent file does not download.
If a handpicked file from either Audio or Video from the same torrent package is marked for download, it works fine adding to Transfers and Downloading.
Flipping screen does not help. Changing to 'Downloading' & back to 'All' does not help. Going back to Search and back to Transfers does not solve the problem either.

Reported by multiple users as well.

**Comment by aldenml** [comment]
This should be fixed with https://github.com/frostwire/frostwire/commit/99d4b32abbde876cfa01761778ae4ea69f1f9038 and https://github.com/frostwire/frostwire/commit/61525e3a3d183ab7464405c1e0df141035d6b8a1

Now what I can see is that in the cases the torrent fails to downloads, is because torcache lacks the file (and it's fails consistently from single files and torrents).

**Comment by gubatron** [comment]
After some testing on Wi-Fi and Mobile only I had no issues with the transfers, all started.

### Another issue
However I will report a new issue I found regarding with Bitsnoop search results, sometimes you see individual search results and 0 torrent search results, which makes absolutely no sense initially, will have to see what the current logic is, again, this is unrelated.
