### ISSUE TITLE
[desktop] zooqle source icon

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#429]
zooqle_source.png for new zooqle search on desktop.

**Comment by gubatron** [comment]
see zooqle.com
![screen shot 2017-04-19 at 8 25 59 am](https://cloud.githubusercontent.com/assets/163977/25185166/dc89f7ec-24d9-11e7-82a5-c1b9c2110bf8.png)
![screen shot 2017-04-19 at 8 25 52 am](https://cloud.githubusercontent.com/assets/163977/25185167/dcadd248-24d9-11e7-98c6-a4b3e147e8ac.png)

**Comment by aldenml** [comment]
this is done
