### ISSUE TITLE
[android] SD Card storage support for Lollypop (Android 5.x users)

### ISSUE THREAD

**Issue by frostwire** [frostwire/frostwire#43]
Seeing if we can work/hack around the limitations added when interacting with files thanks to the insane [SAF](https://developer.android.com/guide/topics/providers/document-provider.html) architecture/api, which thankfully went away in Android 6.0, they came back to their senses.

The hardest part, at least we thought it was the hardest, was bridging the advanced native file access done by jlibtorrent given that you can't just do `new File()` on sd card folders and you have to go through all these abstractions to get a writeable file handle we eventually can give to the jlibtorrent layer.

Now we're dealing with HTTP transfers and we figured that there's no formal "Move" operation with SAF, so we're looking at some workarounds.

**Comment by frostwire** [comment]
[Branch for SAF](https://github.com/frostwire/frostwire/commits/saf)

**Comment by frostwire** [comment]
CC: @kad3mlia this affects your phone.

**Comment by frostwire** [comment]
### Related

@aldenml 

Were some HTTP changes merged, supposedly this wasn't happening in 1.6.8, it's happening on the current build from master on @kad3mlia Sony `5.1.1`

```
E/FW.HttpDownload( 5612): Error downloading url: http://xxx.xxx
E/FW.HttpDownload( 5612): java.io.FileNotFoundException: /storage/sdcard1/Android/data/com.frostwire.android/files/FrostWire/TorrentsData/file.xyz: open failed: EACCES (Permission denied)
E/FW.HttpDownload( 5612): 	at libcore.io.IoBridge.open(IoBridge.java:465)
E/FW.HttpDownload( 5612): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
E/FW.HttpDownload( 5612): 	at com.frostwire.util.http.OKHTTPClient.save(OKHTTPClient.java:107)
E/FW.HttpDownload( 5612): 	at com.frostwire.util.http.AbstractHttpClient.save(AbstractHttpClient.java:163)
E/FW.HttpDownload( 5612): 	at com.frostwire.util.http.AbstractHttpClient.save(AbstractHttpClient.java:158)
E/FW.HttpDownload( 5612): 	at com.frostwire.android.gui.transfers.HttpDownload$1.run(HttpDownload.java:213)
E/FW.HttpDownload( 5612): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/FW.HttpDownload( 5612): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/FW.HttpDownload( 5612): 	at java.lang.Thread.run(Thread.java:818)
E/FW.HttpDownload( 5612): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
E/FW.HttpDownload( 5612): 	at libcore.io.Posix.open(Native Method)
E/FW.HttpDownload( 5612): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
E/FW.HttpDownload( 5612): 	at libcore.io.IoBridge.open(IoBridge.java:451)
E/FW.HttpDownload( 5612): 	... 8 more
```

**Comment by kad3mlia** [comment]
Sony Xperia Z2/ Android 5.1.1
Currently downloading to SD Card works fine on build 226 & 228. No issues.
Nonetheless, I have once opened 228 and could not download from BitTorrent or Cloud onto SD Card. Angel connected it to computer and saw the Permission Denied error. 
I have then uninstalled 228 completely & installed 226. Everything was fine. Then updated to 228 and I no longer have permission issues. 
I have tried Exiting, reinstalling 228 from scratch (deleting all FrostWire files and folders, as well as uninstalling the app), everything worked fine again. Cannot reproduce the Permission Denied state.

**Comment by aldenml** [comment]
@gubatron none from the SAF branch is in master (maybe a faulty build was installed)

**Comment by gubatron** [comment]
Let's revisit the state of affairs with SAF in 2018, see if this can be closed.

**Comment by master255** [comment]
Some Android devices are not able to create directories on external cards.
All Android devices do not support sparse mode on external cards.
All Android devices support the transfer of applications to an external sd card with support for sparse mode.
I hope I've reduced your time.
