### ISSUE TITLE
[android] No more lag starting a torrent transfer when we automatically switch to "Transfers"

### ISSUE THREAD

**Issue by frostwire** [frostwire/frostwire#44]
When user starts a torrent transfer, the Transfer's display is opened and it can take several seconds to show that the transfer has been added.

**Comment by frostwire** [comment]
I've started an [ android-stub-transfer branch](https://github.com/gubatron/frostwire/commits/android-stub-transfer-2016-jan-03)].

I've made some modest optimizations like moving the TransferFragment's onTime() non UI update related code into a background task to minimize the locking time of the UI thread.

Similar work should be done on every other "onTime()" function in the code base if the UI thread is being blocked.

## Approach to problem

I've created a Stub Torrent Transfer object that gets added to the TransferManager on an internal list.
Whenever we perform an onTick, we ask the transfer manager to check for any stubs it might have, if a corresponding transfer hasn't been added, the List adapter will populate an entry on the list view, whenever we find a corresponding transfer the TransferManager makes sure to clear the stub.

Status, almost there, was very sleepy doing this the last time I touched the branch a couple nights ago.

**Comment by aldenml** [comment]
@gubatron onTime() is meant to be executed in the main UI thread and should not span any background task. Regarding the stub idea, if we have some architecture weakness (that I'm sure is the root of the problem) we should fix it. Please, don't merge this branch without further review.

**Comment by gubatron** [comment]
CC: @alejandroarturom I think you will smile next time you try FrostWire. Thank you for insisting on getting this fixed.
