### ISSUE TITLE
[desktop/osx] Cmd+A on application's text fields not selecting all

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#474]
Thanks @marcelinkaaa for reporting this.

**Comment by aldenml** [comment]
I'm changing the scope of the issue to all text fields in the application

**Comment by gubatron** [comment]
hopefully a single fix for all the app :)

**Comment by gubatron** [comment]
Notes as I investigate.

Started off at `GoogleSearchField` which is a `SearchField`, in its init method I found a call to
`ThemeMediator.fixKeyStrokes(this)`, which is called for many different text fields across the application.

`ThemeMediator.fixKeyStrokes(JTextComponent textField)` looks as follows:

```java
public static void fixKeyStrokes(JTextComponent textField) {
        if (OSUtils.isMacOSX()) {
            fixKeyStroke(textField, "copy", KeyEvent.VK_C, 0);
            fixKeyStroke(textField, "paste", KeyEvent.VK_V, 0);
            fixKeyStroke(textField, "cut", KeyEvent.VK_X, 0);
            fixKeyStroke(textField, "caret-begin-line", KeyEvent.VK_LEFT, 0);
            fixKeyStroke(textField, "caret-end-line", KeyEvent.VK_RIGHT, 0);
            fixKeyStroke(textField, "selection-begin-line", KeyEvent.VK_LEFT, KeyEvent.SHIFT_DOWN_MASK);
            fixKeyStroke(textField, "selection-end-line", KeyEvent.VK_RIGHT, KeyEvent.SHIFT_DOWN_MASK);
        }
    }
```

I have to test in windows or linux to see if this bug exists, if not, this if might be the culprit.

`ThemeMediator.fixKeyStroke(JTextComponent textField, String name, int vk, int mask)` looks like this:

```
java
private static void fixKeyStroke(JTextComponent textField, String name, int vk, int mask) {
        Action action = null;

        ActionMap actionMap = textField.getActionMap();
        for (Object k : actionMap.allKeys()) {
            if (k.equals(name)) {
                action = actionMap.get(k);
            }
        }

        if (action != null) {
            InputMap[] inputMaps = new InputMap[] { textField.getInputMap(JComponent.WHEN_FOCUSED), textField.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT), textField.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW) };

            for (InputMap i : inputMaps) {
                i.put(KeyStroke.getKeyStroke(vk, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask() | mask), action);
            }
        }
    }
```
(it could use an optimization on that map lookup :))

it seems to search all the available action keys for the action key `name` passed.
These are all the actions available as far as the debugger told me in runtime:
![screen shot 2017-06-13 at 8 45 59 am](https://user-images.githubusercontent.com/163977/27088668-8d403b44-5015-11e7-8690-e2c49e142cff.png)

Luckily there's a `select-all` I'm going to be testing, I only saw it after I started writing this.

will test. (Talking about problems always helps)

**Comment by aldenml** [comment]
at `49`, that `fixKeyStroke` code is very very old :)

**Comment by gubatron** [comment]
it's working on my mac, on both the search field and in the torrent creation dialog's tracker textfield, which was where I needed it the most. gotta keep testing.

**Comment by muckachina** [comment]
I can select the entire list with 'Command + A' on Mac SIERRA and Yosemite (even on version 6.5.1-build-238), when did you include this fix?

**Comment by aldenml** [comment]
maybe it was the java update that we use internally
