### ISSUE TITLE
[android] 'Stop and Delete Data' from Transfers does not delete .torrent file

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#48]
**Tested on** 
FW Basic 1.6.8 build 227, Samsung S4/Android 5.0.1 with no SD Card. Downloading to Internal, Folder Downloads & default.
FW Plus build 226 & 228, Sony Xperia Z2/ Android 5.1.1. Downloading to SD Card & Internal default locations

**Behavior**
Choosing 'Stop and Delete Data' from Transfers does not delete .torrent file

**Steps to Reproduce**
1. Tap Download on anything from BitTorrent 
2. Go to Transfers
3. Tap on actively downloading file & select 'Stop and Delete Data' >  tap OK on 'Are you sure you want to cancel this download (downloaded data so far will be erased)?

**Additional Observations**
1. The same thing happens on both phones
2. The same thing happens when downloading to SD Card or Internal Memory
3. Cloud Downloads delete correctly

**Comment by gubatron** [comment]
Duplicated, coping this description to Issue #41
