### ISSUE TITLE
[android] Search Filtering and Dynamic Filter Suggestions Checklist

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#484]
* Add a dismissible tip for first time users when a tag is first applied (in the works)
 * ~Make entire panel scrollable~
 * ~Bug with file extensions suggestions~
 * ~After the screen is rotated the tags stop responding to onClick, look at `onResume()`~
 * ~Filter out tags longer than 20 characters~
 * ~ActionBar filter button should not behave on a media type basis, should be consistent with the global behavior of the `KeywordFilterDrawerView` which shows global suggestions. Note: In the beginning suggestions were shown only for the current selected tab, but the experience was way too confusing, so we switched to global suggestions~
 * ~Make sure ActionBar filter button is shown `onResume` for the `SearchFragment`, going to the Android home and back can make the button dissapear~
 * ~Last refactor is not refreshing adapter when removing applied tags. Test by filtering, changing media type, then trying to remove applied tags.~
 * ~Add a dumb-proof way to dismiss the drawer. Right now user can touch the search results in the back or they can gesture the drawer away, but these two might not be obvious.~
 * ~Hide "Clear Filters" unless filters have been applied~

**Comment by muckachina** [comment]
Just in case... The issue with source filters is not included here and persists on build 401:

"Not only Sources appear within the Filter by Source"

![screen shot 2017-06-27 at 8 50 01 am](https://user-images.githubusercontent.com/1534723/27594508-f4497de2-5b27-11e7-8876-7e4475ee0262.png)

**Comment by muckachina** [comment]
Never mind... Sources & Channels then
