### ISSUE TITLE
[Android] Adding Frostwire to F-droid

### ISSUE THREAD

**Issue by jerryn70** [frostwire/frostwire#499]
It will be great if frostwire is available on fdroid .  Iam using github apk's so i will not getting update notification from play store and there is no update check option in frostwire also. So adding to f-droid.org will be great for us those who are not using play store

**Comment by gubatron** [comment]
great suggestion! the more distribution channels we have the better, we will look into this

**Comment by gubatron** [comment]
Looks like their [submission queue](https://f-droid.org/forums/forum/submission-queue/) page is down :(

**Comment by alejandroarturom** [comment]
We can try to add it here: https://gitlab.com/fdroid/rfp/issues

**Comment by gubatron** [comment]
I believe we won't meet their Inclusion Policies, at least I don't have the time to create a build script that removes all the stuff they want removed.

https://f-droid.org/wiki/page/Inclusion_Policy

**Comment by jerryn70** [comment]
@gubatron Then what about adding self-update support for github apk's ?

For example, upon opening the app frostwire it automatically checks for updates, and if found then it asks whether to ignore / update or remind later, after this there is no additional action required by the user.

Check this: https://github.com/javiersantos/AppUpdater

**Comment by NA0341** [comment]
F-Droid -» Reminder to update repo data! =)

**Note:** This app will no longer be updated, its repo disappeared.

Sounds like they still think it's under frostwire_android.

Thank You!

**Comment by gubatron** [comment]
For network security all updates are only announced to the user and they're voluntary.
For example, Auto-update features enabled courts to shutdown the limewire network.
All users on FrostWire Plus get an update message whenever we have a stable release.
