### ISSUE TITLE
[android] Show no more than one ad per every one successful download

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#50]
We've had some users complaining they are seeding too many ads on top of things not working and erroring out/not progressing. I imagine this must be quite frustrating to see ads all the time and not get anything in return, sort of speak.

How to fix: I would see an additional condition that checks a number of completed downloads. 
After second file is added to Transfers, check if at least one completed. If not, don't show the ad. 
After 4th is added to Transfers & no ads were shown, check if at least 1 completed. If yes, show the ad. If no, don't show the ad. 
After 4th is added to Transfers & one ad was shown, check if at least 2 completed. If yes, show the ad. If no, don't show the ad. etc

The logic would basically show no more than one ad every one successful download AND at most every second addition to Transfers. 

Hope that makes sense.

**Comment by gubatron** [comment]
they can always turn off the ads...
I think this is overkill.

http://twitter.com/gubatron
