### ISSUE TITLE
[android] When opening My Music for the first time it should show "Last Added" tab, after that the application should remember

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#51]
If you've never played a song and the first thing you did was to download a song, the first time you open the Music Player you will see an empty list because you've never played anything.

At this moment you should be displayed the "Last Added" tab.

Then, from there on, we should keep track of what was the last tab touched on an internal setting variable (See `PreferenceUtils.java` which is where it seems apollo keeps its preferences, there seems to be something related `setStartPage()`).

Classes to look at inside `android/apollo`:
`ProfileActivity.java`, `PagerAdapter.java`, `MusicBrowserPhoneFragment.java`

CC: @votaguz @alejandroarturom (@arubinofaux wanna do some android?)

$15 bounty for merged pull request to be paid in Bitcoin at the exchange rate of the day on Bitven.com

**Comment by marcelinkaaa** [comment]
@gubatron so its not that you want the "Last Added" tab to be always first when My Music is opened for the first time, right? What you want is for it to be first when you just go to My Music without playing or downloading anything or just downloading something. If you played some of your content and then you open My Music for the first time you would expect to see Recent tab? 

Just wanted to clarify as I already have it set up so it always opens to the Last Added tab and later on remember which tab you were last. But I dont really know how to do the other part. Let me know.

**Comment by gubatron** [comment]
>so its not that you want the "Last Added" tab to be always first when My Music is opened for the first time, right
yes, just the first time.

once you start playing stuff you should see Recent, or whatever last tab you left selected before you leave My Music.

**Comment by gubatron** [comment]
@marcelinkaaa check inside the apollo folder `PreferenceUtils.java`

**Comment by marcelinkaaa** [comment]
I got it already and changed it to page 0 - which is Last Added as a Default Page. Than the code remembers what was your last tab. This is done. 

However how about this scenario - you first get the app installed and go to my files, for ex, playing one of  your current songs you already had - thus opening the player, after that you go back to navigation (without being in My Music) and select My Music for the first time - should it still show you recent? Or no matter what you did before the first page you see should be Last Added?
