### ISSUE TITLE
[common] Pixabay search

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#538]
Millions of creative commons images.

**Comment by aldenml** [comment]
done with https://github.com/frostwire/frostwire/commit/ad6cd4bd69991b4565e6178c2d9e7df8b3ac8ebc, https://github.com/frostwire/frostwire/commit/17e3f4ee0e671609e15e6df48ca52aa59ab91de3 and https://github.com/frostwire/frostwire/commit/19075c86176f08970cee6b478f27186f80505bec
