### ISSUE TITLE
Application not responding after installation on macOS 10.12.5 (16F73)

### ISSUE THREAD

**Issue by berezovskyi** [frostwire/frostwire#539]
When I run it from the command line and interrupt after it hangs, it outputs the following:

http://ec2-54-191-37-103.us-west-2.compute.amazonaws.com/black.png?crash=1&os=mac&appkit=150483&ver=10579&ldebug=0&signal=2&backtrace=__CFRunLoopServiceMachPort%0A__CFRunLoopRun%0ACFRunLoopRunSpecific%0A-%5BNSConcreteTask%20waitUntilExit%5D%0A_ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initINS_11__wrap_iterIPKcEEEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESC_SC_%0A

The site serves some strange MyProg.exe but virustotal thinks there is nothing bad with it. All this seems a bit fishy, guys :)

But I thank you in advance for help!

**Comment by gubatron** [comment]
the link you put there simply shows a 1x1 black pixel... hmm

**Comment by gubatron** [comment]
also what site are you talking about serves "MyProg.exe" ? can you give us a link?
