### ISSUE TITLE
[android] annoying back to back display of Interstitials

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#571]
Revision of Interstitial displays.
For some reason, it can happen that interstitial displays are somehow queueing one after the other.

I've gotten 2 or 3 back to back, pretty annoying.
Marcelinkaaa said she got 9 the other day, unacceptable.

There's also an issue where the ads are shown even outside of FrostWire, this one might be easily fixed by cancelling the display if somehow it can be detected the app is not being actively shown.

Help needed while I finish the other branch if you have some time @aldenml

**Comment by marcelinkaaa** [comment]
Ahh sorry not 9.... I usually see 2 ads back to back - sometimes I see 3 ads which make me click 9 times on 'x' to close them. As each ad has 2 parts and then there is a 'Support FrostWire' screen.

**Comment by gubatron** [comment]
oh, I heard 9, my bad.
