### ISSUE TITLE
[android] Advanced Torrent Transfer Screens

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#581]
Last set of mockups. September 6th 2017
It'd be great if we could have a branch with the most important screens before Sept 20th. 2017

0. All Transfers
![0 transfers_all_downloads](https://user-images.githubusercontent.com/163977/30138470-c6b12746-9325-11e7-847a-eeefdc01880f.png)

1. Transfer Details
![1 transfer_detail_details](https://user-images.githubusercontent.com/163977/30138484-e16fac24-9325-11e7-8107-c4c63eddff1d.png)

2. Transfer Details Top Options
![2 transfer_detail_details_top_options](https://user-images.githubusercontent.com/163977/30138489-e48faa4e-9325-11e7-8903-67cad3a8bb94.png)

3. Transfer Details Files
![3 transfer_detail_files](https://user-images.githubusercontent.com/163977/30138501-ebb93a88-9325-11e7-87f6-bef96e7eb378.png)

4. Transfer Details Files
![4 transfer_detail_trackers](https://user-images.githubusercontent.com/163977/30138503-ee74f4c4-9325-11e7-9188-5a1cf107da90.png)

5. Transfer Details Peers
![5 transfer_detail_peers](https://user-images.githubusercontent.com/163977/30138508-f4663294-9325-11e7-934c-d498f698cd70.png)

6. 3. Transfer Details Pieces
![6 transfer_detail_pieces](https://user-images.githubusercontent.com/163977/30138515-fb66f074-9325-11e7-912a-57529bfa1dc9.png)

**Comment by gubatron** [comment]
@marcelinkaaa  please submit a PR to get this started. I've no clue what's the branch

**Comment by marcelinkaaa** [comment]
Submitted WIP branch for initial review.
