### ISSUE TITLE
[android/code review] MainApplication.onCreate() optimization/crash protection

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#589]
I think we need to take a good look at this method and see:
* what is indispensable so we don't throw a Runtime error and screw up the launching process
* what can be done in parallel, looking at the Debugger, `onCreate()` is executed on the `main` thread

```java
try {
            //android.os.Debug.waitForDebugger();
            PlayStore.getInstance().initialize(this); // as early as possible

            ignoreHardwareMenu();
            AbstractActivity.setMenuIconsVisible(true);
            installHttpCache();

            ConfigurationManager.create(this);

            Platforms.set(new AndroidPlatform(this));

            setupBTEngine();

            NetworkManager.create(this);
            Librarian.create(this);
            Engine.instance().onApplicationCreate(this);

            ImageLoader.getInstance(this);
            CrawlPagedWebSearchPerformer.setCache(new DiskCrawlCache(this));
            CrawlPagedWebSearchPerformer.setMagnetDownloader(new LibTorrentMagnetDownloader());

            LocalSearchEngine.create();

            cleanTemp();

            Librarian.instance().syncMediaStore();
        } catch (Throwable e) {
            throw new RuntimeException("Unable to initialize main components", e);
        }
```

**Comment by gubatron** [comment]
for instance:
```java
Librarian.instance().syncMediaStore();
```

I believe that one could easily be moved to another thread, if there's a lot of DB records there this could be IO intensive, perhaps there's no need to keep the start up waiting.

**Comment by gubatron** [comment]
```java
PlayStore.getInstance().initialize(this); // as early as possible
```

should this one be a deal breaker? perhaps we simply disable app store purchase functions if this fails.
Also, I think we shouldn't even be calling this if we're not running the Google Play version of the app.

**Comment by gubatron** [comment]
```java
installHttpCache();
```
this one already runs in parallel.

**Comment by gubatron** [comment]
```
Platforms.set(new AndroidPlatform(this));
```

def. a deal breaker. I wonder if this is the culprit for the crashes in Oreo when it's calling `buildFileSystem()`

```java
if (Build.VERSION.SDK_INT >= VERSION_CODE_LOLLIPOP) {
            LollipopFileSystem lfs = new LollipopFileSystem(app);
            PosixCalls w = new PosixCalls(lfs);
            w.swigReleaseOwnership();
            libtorrent.set_posix_wrapper(w);
            //LibTorrent.setPosixWrapper(new PosixCalls(lfs));
            fs = lfs;
        }
```

**Comment by gubatron** [comment]
```java
setupBTEngine();
```

not the slowest but there's IO involved, perhaps it can be sent to a background thread?

**Comment by gubatron** [comment]
```java
ImageLoader.getInstance(this);
```

this one looks expensive, but I suppose it's necessary to have it ready for all the image loading that's about to happen.

**Comment by gubatron** [comment]
these two have disk IO, file stats and they seem like they could be moved to a parallel thread
```java
CrawlPagedWebSearchPerformer.setCache(new DiskCrawlCache(this));
CrawlPagedWebSearchPerformer.setMagnetDownloader(new LibTorrentMagnetDownloader());
```

**Comment by gubatron** [comment]
```java
LocalSearchEngine.create();
```

this one creates a thread pool, looks expensive and perhaps could be moved to the background as well.

**Comment by gubatron** [comment]
```java
cleanTemp()
```

could involve heavy IO if dealing with cleaning big files, I say let's move it to the background too

**Comment by aldenml** [comment]
I read something about Oreo being more strict in doing unbuffered IO to the file system, `setupBTEngine` eventually triggers the read of `libtorrent` settings file.

btw, `syncMediaStore` is in another thread already.

I think we should create a more robust setup using `ThreadPolicy` in `Debug` to actually fix bugs, not only moving them to a parallel thread

**Comment by gubatron** [comment]
my concern is also making the app start faster in the eyes of users (re: moving stuff to the background if possible)

**Comment by gubatron** [comment]
I've yet to learn what those ThreadPolicies can do, just read about LAX, but still have to read more to fully understand what they're for.

**Comment by aldenml** [comment]
I just found that we indeed do all sort of unrecommended things in this method.I can't just move all to a background thread because that could create issues of setup (time creation) with other components.

**Comment by gubatron** [comment]
have we done all that we can by now in this respect? or still more work to be done?
