### ISSUE TITLE
[android/UX] No more accidental scrolls when browsing search results or my files

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#590]
Not sure why I haven't brought this up before, but I've always found it really annoying when browsing my files that I accidentally touch the scrollbar on the side and I end up all the way down and then I have to scroll up to get back to where I was.

I've never had such issue with other apps and when I checked Google Photos, this is what they do, they have one big button that can be used as the scrollbar. I wonder if there's a simple way to style our scrollbar to not be so tall, and be a little wider and visible, or if you think that we should have the same Google-ish control they use on Google Photos

![scrollbar-google-photos](https://user-images.githubusercontent.com/163977/30806221-22b96b30-a1b2-11e7-9e11-4fa863525ac0.png)

**Comment by marcelinkaaa** [comment]
Yes, especially for a grid like this where you don't have one entry taking entire row it would be beneficial. I myself never really had that problem but it could be simply how I am holding my device. 

So question:
Any tips on how current scrollbars work? There is a different scrollbar for My Files -> anything from audio to docs, then the scroll bar for torrents seem to be fed differently in My Files as well. For now I know we can do it with simple styles and I was able to change it but the style seems to be overwritten few seconds later by what we currently have in My Files and Search etc. 
Just a bit confused as to how all of it is set up in the app. 

Will look at it in detail tomorrow morning but if you have tips @gubatron let me know.

**Comment by gubatron** [comment]
Please remember to send the PR for this. I think it's almost done no?

**Comment by marcelinkaaa** [comment]
It was, I was playing with the scroll thumb design for the fast scroll, but wanted to finish the changes to the transfer detail branch we talked about yesterday. I will create a pull request for the fixed scroll bar with the original thumb soon and will change the thumb after that, just so you have it sooner.

**Comment by marcelinkaaa** [comment]
Submitted, but I can not find a way to apply the same logic to ApolloFragment as similarly to SearchFragment it already has an setOnScrollListener. Any ideas?

**Comment by gubatron** [comment]
not sure if in apollo fragment we had this issue as much, I'll test and submit another ticket
