### ISSUE TITLE
[desktop/linux] FrostWire - Manjaro

### ISSUE THREAD

**Issue by liberodark** [frostwire/frostwire#593]
Hello,

Have a problem on linux for launch frostwire !

HOSTNAME IS pc-pc
Starting FrostWire...
Java exec found in PATH. Verifying...
Suitable java version found [java = 1.8.0_144]
Configuring environment...
Loading FrostWire:
Error: Unable to access jarfile frostwire.jar

******************************************************************
Something went wrong with FrostWire.
Maybe you're using the wrong version of Java?
(FrostWire is tested against and works best with with Sun's JRE, Java 1.7+)
The version of Java in your PATH is:
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

Cordialy

**Comment by liberodark** [comment]
SH is not fully corrected

**Comment by gubatron** [comment]
are you using `./frostwire.sh` ?
Weird that it's not finding the $CLASSPATH correctly.

**Comment by gubatron** [comment]
Are you running from the .tar.gz? I cannot replicate the issue on the latest Ubuntu
![screen shot 2017-09-29 at 9 03 35 am](https://user-images.githubusercontent.com/163977/31022163-349f17be-a4f5-11e7-98f7-d0f605dc6fc8.png)

**Comment by gubatron** [comment]
let me try a Manjaro VM, thanks for updating the title.

**Comment by gubatron** [comment]
is that Manjaro 17.0.5? 32 or 64bit?

**Comment by liberodark** [comment]
17.0.5 XFCE 64 bit but im work on deb version.
And don't unterstand for what no have jar file on ubuntu version.

Cordialy

**Comment by gubatron** [comment]
ok, I'll try the .deb version on Manjaro, it will take me a while to figure it out, not sure if Manjaro uses `apt` or `dpkg` for .deb handling.

(BTW: deb version always works fine on Ubuntu, we build it in Ubuntu)

**Comment by liberodark** [comment]
lol not im work on pkgbuild :D

**Comment by liberodark** [comment]
Is a sh file is not correct for arch / manjaro

**Comment by gubatron** [comment]
ha, sorry, it will be my first time ever on Manjaro (or any arkbuild)

If I understand correctly pkgbuild needs sources no? maybe that's why the .deb isn't working for you, which is why I thought you were working with the .tar.gz file, you just untar and run.

**Comment by gubatron** [comment]
otherwise you will need the .deb sources

**Comment by liberodark** [comment]
all is work but is not launch the sh try not great command
