### ISSUE TITLE
[android] 'Feedback/rate message' on Search screen - Should not appear right away

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#595]
Tested on FrostWire 1.9.9-build-450

The feedback message is showing off right away when launching the app and there is a 'logic' behind that is not working since the message should appear after using the app for a while.

Reported by @Paulinka

**Comment by gubatron** [comment]
This should be fixed with https://github.com/frostwire/frostwire/commit/28e6c4fbb75e3ff3a67ec8e75f2e73b5ba42c872

**Comment by muckachina** [comment]
Not getting the rate message when installing FW from scratch, only when launching the app and a prior version was installed.
