### ISSUE TITLE
[android] Search results scroll position lost after opening an audio/video preview

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#611]
@muckachina reported:

Tested on FrostWire 1.9.9-build-452

To reproduce:

Make a search and wait till the search stops

Go down on the list of results under the audio or video label

Select a file to preview from the bottom of the list

Go back to the list to preview for example the next file and you will see how FW jumped to the beginning of the list.

Let me know If you won't consider this an issue, I know the app indicates the last previewed file changing the color of the letters but some users complain about this 'annoying jump'.
--

Maybe @alejandroarturom could take a look at this as a beginner level fix.
In some other places, perhaps right there in search, we do keep the scrollbar position somehow, if we do, this is a sign of an existing bad design in the way we handle this.

**Comment by marcelinkaaa** [comment]
Is this still happening? Works fine on my devices on Android 8 and 6.

**Comment by muckachina** [comment]
Still happens here on build 463 @marcelinkaaa I'll try from git just in case.

**Comment by gubatron** [comment]
@marcelinkaaa if you want to warm up with Android/Java, I'd recommend you take on this issue.
Seems to be a good one to refresh and it's in the UX area.

**Comment by marcelinkaaa** [comment]
@gubatron  will try but on all of my devices and emulators, this bug does not happen. So I can not reproduce. 
@muckachina what devices do you have that it happens on?

**Comment by gubatron** [comment]
actually it didn't happen to me any more. Will close then!

**Comment by muckachina** [comment]
@marcelinkaaa  @gubatron Tested on **FW 2.0.2-build-506** and I still can reproduce this on one **Android 6 - LG device** but no on Android 7 nor the newer LG with Android 6 so it seems this affects some models.

Please confirm here If want to keep it closed so I'll comment and close it on android-qa list.

**Comment by gubatron** [comment]
I cannot replicate in any way on Android 7.
