### ISSUE TITLE
[android] implement com.android.billingclient:billing:1.0

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#615]

**Comment by gubatron** [comment]
was this implemented already? I  know there was a big refactor there a few months ago

**Comment by aldenml** [comment]
no, far from it, it's a risky big refactor

**Comment by gubatron** [comment]
ok, it looks like the logic on how the Offers are initialized now (not after an upgrade, not after a first install) seems to have the complains from paying users gone. Will close this then until they make it mandatory.
