### ISSUE TITLE
[android] Set proper "empty" string for RecentFragment. 

### ISSUE THREAD

**Issue by votaguz** [frostwire/frostwire#639]
Currently **Recents** fragment when empty is showing the following message: 
```To copy music from your computer to your device, use a USB cable.```
Instead of It should show : 
```Songs you have added over the last month will be shown here.```

Some updates in [`ApolloFragment.onLoadFinished`](https://github.com/frostwire/frostwire/blob/master/android/apollo/src/com/andrew/apollo/ui/fragments/profile/ApolloFragment.java#L444) method are needed in order to fix the issue.

**Comment by gubatron** [comment]
please prefix ticket titles correctly

**Comment by gubatron** [comment]
also add an explanation to what you mean, to people not working on this it's not easy to understand this.
