### ISSUE TITLE
[android] BitTorrent turns itself on after connecting to Wi-Fi

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#64]
Replicated multiple times on Sony Xperia Z2/ Android 5.1.1
I have disabled BitTorrent when on mobile data. When phone connects itself to any wi-fi network, the BItTorent turns on, automatically.

This does not happen when:
- switching wi-fi networks
- turning mobile data on and off
- turning BitTorrent off while and wi-fi and then turning wi-fi off

Only thing that triggers it in my experience is connecting from no wi-fi to wi-fi and it does not matter if DHT is on or off and if Using BitTorrent on 3G/4G is on or off.

BTW - You have to exit and enter the screen again - the slider will not move from off to on with you looking at it. I guess it needs to refresh.

**Comment by gubatron** [comment]
this sounds like the expected behavior.
