### ISSUE TITLE
When opening torrent site link from within client, add possibility to choose browser

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#65]
User feature request:

"Can you please add the facility for users to choose which browser they want to open links for torrent details, etc. in rather than just using the system default. As many users may be logged-in to their default browser, thereby providing details of their identity, by having no choice but to use that browser it negates them using a VPN for privacy to a very large extent. "

**Comment by gubatron** [comment]
Does anybody have an idea of how to even do this?
