### ISSUE TITLE
[android] My Files title and label lists does not match properly

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#665]
**Tested on Android 6 and 7
FrostWire 2.0.2-build-497**

There are different scenarios where the menu labels does not work properly. Here some examples to reproduce:

**Example 1:**
 
1) Go to Transfer list and start Seeding a file
2) Go to My Files > My Torrents and start going up and down across the list of torrents
3) FW Tabs menu will suddenly jump to 'My Audio' showing me the list of Audios with 'My Audios' title but Tab 'My Torrents' highlighted:
 
![screen shot 2018-02-28 at 12 07 24 pm](https://user-images.githubusercontent.com/1534723/36851232-c4cd0364-1d36-11e8-900e-7e2ba5901e6b.png)

**Example 2:**

1) After going to My Files and select a list keep FW running for several hours 
2) Go to the app again and select a different label on My Files
3) You will see the label selected shows the correct list but the title of the list does not match with the label selected:

![screen shot 2018-03-01 at 9 51 41 am](https://user-images.githubusercontent.com/1534723/36851209-b6bed4aa-1d36-11e8-8c3e-9ded2890fb98.png)

**Example 3:**
 
1) Go to Transfer list and select the option 'Remove Torrent and Data' for a file
2) Go to My Files and you will see there is no title for the list selected by default:

![screen shot 2018-02-28 at 12 19 46 pm](https://user-images.githubusercontent.com/1534723/36851349-031a64e0-1d37-11e8-9a9a-d930d7a4ade3.png)

 I'll be adding additional scenarios If found it.

**Comment by gubatron** [comment]
I'll need your help with this one @aldenml, I know it's boring, but it's very likely to occur and screw the experience and I'm sure you'll be able to fix it way faster than me

**Comment by gubatron** [comment]
I believe this one will be gone after some updates on `MyFilesFragment.updateHeader()` I just commited @muckachina

**Comment by gubatron** [comment]
@muckachina can you check if this still happening on the last builds

**Comment by muckachina** [comment]
I can't reproduce this issue anymore since build 503.

Tested again on build 504 and I can see how the labels refresh every time I select them.

**Comment by muckachina** [comment]
There is another issue related to this fix (reported by @marcelinkaaa ) I could reproduce after several clicks --> The number of files on the list sometimes doesn't appear

To reproduce:
1) Start clicking different labels till you notice one of the titles appear but not the number of files on the list

![screen shot 2018-03-07 at 2 26 05 pm](https://user-images.githubusercontent.com/1534723/37114250-cc49bfcc-2215-11e8-99f6-8a59a27fb3d7.png)

Here only happens when going pretty fast across the labels after 8 or 10 clicks, on Marcelina's device it happens when you goes through the labels slowly.

**Comment by gubatron** [comment]
Will see what I can do about that. For  now I'll say "it's not a bug, it's a feature"

We present the count as soon as it's available, that's why you don't see the count, but this allows us to change the title to the type as soon as possible, and then when the background finishes the counting process we update the count portion of the title.

There must be something happening that the count doesn't end and report back properly.

I'll give it another look.

**Comment by muckachina** [comment]
Alden said it's on his list so I re-opened it here.

**Comment by aldenml** [comment]
@muckachina it should be fixed with https://github.com/frostwire/frostwire/commit/e01f9efc00715796b96ecb739fadf02b7eec3628

**Comment by muckachina** [comment]
Closing here, I cannot reproduce on FrostWire 2.0.3-build-521 neither on android 5.1, 6 nor 7
