### ISSUE TITLE
[android] NordVPN and ExpressVPN not detected on Android 8 

### ISSUE THREAD

**Issue by marcelinkaaa** [frostwire/frostwire#680]
I have been testing vpn detection on the Pixel phone with Android 8. Both NordVPN and ExpressVPN were not recognized as on. Other devices I have detected both fine. 

![screenshot_20180314-161232](https://user-images.githubusercontent.com/2339972/37433869-3c211db2-27a3-11e8-9ce8-88fd625dad69.png)
![screenshot_20180314-161345](https://user-images.githubusercontent.com/2339972/37433870-3c376d6a-27a3-11e8-9ceb-79309a7c7064.png)

**Comment by muckachina** [comment]
FrostWire 2.0.2-build-508 and 510 does recognize ExpressVPN and NordVPN on my android devices.

Also NordVPN tested since build 504 and it is working there.

What build were you running here?

**Comment by gubatron** [comment]
yeah, the issue seems to be on Android 8, I can't reproduce on 7.

**Comment by muckachina** [comment]
I tested on Android 8 this morning after the Samsung update and FrostWire 2.0.2-build-512 recognizes ExpressVPN and NordVPN here @marcelinkaaa 

Give it a try to the latest build and let me know.
