### ISSUE TITLE
[web/support] meta og:title conflict in FrostWire's Knowledge Base

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#686]
Looks like the template is entering the title twice in there. Let's make sure we keep one, and that it is the right one so if/when these articles are shared in social media they appear with the right title, and not all with the same title. (I'd keep the first one and would add a **suffix** `- FrostWire's Support Knowledge Base`)

![screen shot 2018-03-21 at 2 30 56 pm](https://user-images.githubusercontent.com/163977/37735780-add40980-2d14-11e8-9f1b-4bca31242faf.png)

**Comment by marcelinkaaa** [comment]
Should be fixed.

**Comment by muckachina** [comment]
that was fast :P Thanks!
