### ISSUE TITLE
[android] My Files > Videos should be displayed with a grid.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#73]
**This issue has a $50 bounty**

**Comment by marcelinkaaa** [comment]
Let's add that this would require a change in the way we select the files. As of right now we have a checkbox located next to a file for easy selection of given files. We would need to implement a long press for multiple selection for example or use checkboxes in a different way.

**Comment by gubatron** [comment]
yup. either that, or a small checkbox on a corner. But I like better the long press that brings out a thick border around the images.

**Comment by gubatron** [comment]
for now, I'd split that feature as another issue, as it's not worth the $50 for whoever decides to implement this one. and it'd only publish that new bounty once we're getting close to merging a patch with grid display.

**Comment by gubatron** [comment]
[Moved here](https://github.com/frostwire/frostwire/issues/228)
