### ISSUE TITLE
 Logo design for merkato

### ISSUE THREAD

**Issue by leonardoderoy** [frostwire/frostwire#738]
Hello! @frostwire

I'm a graphic designer and I like to support your project because I'm all about cryptocurrency so I really liked this project, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by gubatron** [comment]
Thanks for your initiative, but we're very happy with our current logo.

Perhaps you can help us design a mascot to show when there's no search results, we need something like that. As an example, think of Chrome when a page cannot be opened, they have a Dinosaur as a mascot, what would FrostWire's mascot look like for such error message screens?
