### ISSUE TITLE
how to get a youtube download url bypass IP access restrictions

### ISSUE THREAD

**Issue by kaiweizhang** [frostwire/frostwire#74]
when i use the YouTubeExtractor of frostwire to get the youtube download url,but i can't be used by other ip(youtube return 403).I have found some other website can get the url by web server,also the url includes ip param,but their can be use to download everywhere.I wonder how they do it.can you give me some solution,thanks!

**Comment by gubatron** [comment]
Please open another ticket written with correct punctuation.

Before you submit it, please read it out loud to make sure it makes sense.
