### ISSUE TITLE
[android] Mini Player does not display after being stopped and use "add to queue" action

### ISSUE THREAD

**Issue by votaguz** [frostwire/frostwire#740]

**Comment by gubatron** [comment]
@marcelinkaaa does it even make sense trying to make this happen?

If the player is stopped, as in full stop, it should disappear. If you add a song to the queue, the player is not active until the user decides to play a song.

**Comment by marcelinkaaa** [comment]
Yes, however: Currently when you open the app for the first time and go to My Music - then add a song to the queue without playing it the mini player appears so we can see the queue. 
We can then play some songs and decide to close the player completely. If in the same session we go back to My Files and add another song to the queue - this time the mini player will not appear. Before the player was also not active and the mini player appeared. So yes, I would add this.

What happens now in that second scenario is that although the mini player does not appear when adding a song to queue on My Music, when a user exits My Music the mini player is there. So adding the song to a queue did trigger the mini player just not on My Music.

**Comment by gubatron** [comment]
Just tested this again, instead of "Stopping", I paused, then tried to play a file (on Basic) and had a crash, might be unrelated. Will check for next release.
