### ISSUE TITLE
[common] write test to make sure FrostWire will not crash on startup with corrupted .torrents

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#75]
The test should.
1. Fetch and save a .torrent file inside the `libtorrent/` folder.
2. shutdown frostwire.
3. add random data to corrupt the .torrent inside the `libtorrent/` folder.
4. start frostwire, frostwire should not crash.

**Comment by muckachina** [comment]
I cannot reproduce this crash even after changing .torrent files within libtorrent/ folder that's why I haven't wrote before.

I'm still trying to get the bad_alloc crash that users experience when updating FW.
