### ISSUE TITLE
[desktop/windows] Save folder cannot be named "incomplete"

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#772]
this will cause issues when moving incomplete files, at least in Windows we could see today.
Thanks Steve Cody for reporting this bug.

**Comment by gubatron** [comment]
CC: @muckachina 
In case you get someone with this issue downloading YT video files, this might be one of the reasons why "Moving Incomplete" error might appear, working on a solution.

**Comment by muckachina** [comment]
Wow this is interesting... I'll check it today, I couldn't reproduce this issue yet but I've at least 2 reports from users, although I'm not sure how the word 'incomplete' could have that effect and not other words, I know the problem could happen when the download takes too long to download or the internet connection is interrupted for seconds.

**Comment by gubatron** [comment]
I could not replicate the issue on Mac, I've to test in windows, putting the folder
"c:\users\gubatron\incomplete" and also try with "Incomplete" (capital I)

my guess is that FrostWire can't find the incomplete folder, or can't move to the same folder and the file gets deleted or can't be written onto itself when it's time to move it.

**Comment by gubatron** [comment]
crazy edge cases

**Comment by muckachina** [comment]
Good news! I asked a user for the specific route where he's trying to save files and he's using this on Windows:

_C:\Users\kshau\Music\Incomplete_

This is one of the scenarios where the app cannot save the files 'Music' folder is a protected folder on Windows, I tested without the folder 'Incomplete', saving directly on 'Music' and the file on FrostWire just went right away to status 'Finished without saving the download (empty progress bar):

![screen shot 2018-08-02 at 3 12 29 pm](https://user-images.githubusercontent.com/1534723/43605719-48f6943a-9667-11e8-91cd-59c2a3db021d.png)

**Comment by muckachina** [comment]
To replicate on Windows 10:

1) Go to FrostWire main menu Tools > Options > BitTorrent and click the button 'browse' to change the 'Default Save Folder' location

2) Select the route C:\Users\main_user\Music\ as the folder where your files will be saved and apply changes.

3) Go to Search screen and make a search.

4) Start downloading an audio file for example and you will see how the file goes to Transfer list as 'Finished' but never downloaded.

**Comment by gubatron** [comment]
could not replicate on my windows 10 instance.
downloaded audio and video fine without the "Error: move incomplete" issue.

However, in some instances, the estimated size was much smaller and you'd see the transfer show 100%, but still downloading, this is a separate YouTube issue though.

**Comment by muckachina** [comment]
Are you testing on a VM or physical device?

**Comment by muckachina** [comment]
Now it has worked with 2 different videos from YT on both Windows 8 and 10.... perhaps it's something related to the files instead of FW??

**Comment by muckachina** [comment]
Finally reproduced with some files from Archive.org :) on desktop
```
INFO: Could not rename [/Users/username/FrostWire/Incomplete/11. NameOfFile.flac] into [/Users/username/FrostWire/Torrent Data/disc1/11. NameOfFile.flac]
```
The same file on Android just goes to Transfer list as "Complete" but never downloads properly:

```
08-14 11:04:58.964 1633-2420/? E/MediaScannerJNI: An error occurred while scanning file '/data/media/0/FrostWire/TorrentsData/11.NameOfFile.flac'.
```

**Comment by aldenml** [comment]
@muckachina what's your evaluation of the archive.org fix?

**Comment by muckachina** [comment]
I tested on Mac SIERRA and Windows 10 from git and I cannot find other files with similar errors. The original files "Stream only" doesn't appear within Search results anymore.

Still have to pull and test on Android. I also asked one of the users that reported a similar problem on FW chat If the issue was related only to these files from this source.
