### ISSUE TITLE
[android] Missing Music Player Polish Translations

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#778]
```
Language file: ./res/values-pl/strings.xml
94% completed 
Missing elements: 

<string name="now_listening_to_no_artist_available">#NowPlaying \"<xliff:g id="title">%1$s</xliff:g>\" on #FrostWire</string>
<string name="delete_files_title">Delete files</string>
<string name="page_last_added">Last Added</string>
<string name="empty_playlist">This playlist is empty.\n\nClick here to learn how to add songs.</string>
<string name="are_you_sure_delete_files_text">Are you sure you want to PERMANENTLY DELETE the selected files from your device?</string>
<string name="frostwire_player">FrostWire Player</string>

```

Ping @kad3mlia

**Comment by kad3mlia** [comment]
<string name="now_listening_to_no_artist_available">#TerazSłucham \"<xliff:g id="title">%1$s</xliff:g>\" na #FrostWire</string>
<string name="delete_files_title">Usuń Pliki</string>
<string name="page_last_added">Ostatnio Dodane</string>
<string name="empty_playlist">Ta playlista jest pusta.\n\nKliknij tutaj aby dowiedzieć się jak dodać piosenki.</string>
<string name="are_you_sure_delete_files_text">Czy na pewno chcesz NA ZAWSZE USUNĄĆ wybrane pliki z urządzenia?</string>
<string name="frostwire_player">Odtwarzacz FrostWire</string>

**Comment by gubatron** [comment]
Merged here
https://github.com/frostwire/frostwire/commit/9fec6e703065f9cf10bd55e9fb5f19e2e44de6e3

Thanks!!!!
