### ISSUE TITLE
[all] TLS 1.3 + support

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#790]
Per advanced torrent user feedback on reddit as a reason to switch on Mac.

```
TLS 1.3 support, apparently utorrent for mac is unable to support anything beyond TLS v1
```

**Comment by gubatron** [comment]
(perhaps we already have this)

**Comment by aldenml** [comment]
we support it already, via the latest version of openssl, but I guess this is only http connections we are talking about
