### ISSUE TITLE
Does Frostwire store a unique instance/user GUID locally anymore? 

### ISSUE THREAD

**Issue by WaffleTownDoggo** [frostwire/frostwire#800]
Hi all, looking to see whether a GUID is stored locally by frostwire anymore. It used to be stored in the frostwire.props file, but hasn't been stored there in some time. Any users/devs know whether any unique user/machine/instance guid is stored locally?

**Comment by aldenml** [comment]
iirc, we don't have any unique guid anymore for our desktop app, we have it for android, but not used (probably to be removed in the near future)
