### ISSUE TITLE
Languages: English (United Kingdom) & English (Canadian)

### ISSUE THREAD

**Issue by alejandroarturom** [frostwire/frostwire#818]
Should we delete those languages files (EN_GB & EN_CA)? The difference is not really much, unless we change some vocabulary words or some auxiliary verbs. @gubatron on desktop and @aldenml  on apollo

**Comment by gubatron** [comment]
If this is for android, go ahead and delete.
On desktop, I'd say no because people will complain about the flag being shown in the status bar.
