### ISSUE TITLE
[android] Lingering "Saving to Internal Memory" message

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#825]
Tested on Android 8 and 6 - FrostWire 2.0.9-build-563

To reproduce:

1. Go to Transfer list and click on the message "Saving to Internal Memory... available SD card"

2. Change Storage Location route to "SD card"

3. When going back to Transfer screen you will notice the message "Saving to Internal Memory" is still there (screen not refreshing)

![saving-to-internal-memory](https://user-images.githubusercontent.com/163977/45788780-cb041400-bc39-11e8-8d52-8be99e63d6b1.png)

**Comment by gubatron** [comment]
@marcelinkaaa I believe you might have an SD card capable device, also I think this ticket is right up your alley

**Comment by marcelinkaaa** [comment]
So don't know how to fix it. I understand what is going on and how the code is set. So do you have any pointers? 

1) In TransfersFragment we are calling public void initStorageRelatedRichNotifications(View v) to set which notification to show. 

2) We call:
if (sdCardDir != null && com.frostwire.android.util.SystemUtils.isSecondaryExternalStorageMounted(sdCardDir) &&
                !TransferManager.isUsingSDCardPrivateStorage() &&
                !internalMemoryNotification.wasDismissed())

3) to show internalMemoryNotification.setVisibility(View.VISIBLE);
4) and internalMemoryNotification.setOnClickListener(v1 -> showStoragePreference()); so user opens the storage picker. 
5) then in StoragePicker.java we set
        activity.startActivityForResult(intent, SELECT_FOLDER_REQUEST_CODE);
6) and in MainActivity.java we call: protected void onActivityResult

The issue: 
- The internal memory notification is not hidden when a user clicks on it to change to sd card and comes back to transfers, or when a user changes to SD card > goes to My Music or Settings > then go back to transfer screen. 

- The internal memory notification is hidden when a user clicks to change sd card > goes to any other Fragment as My Files, Search, and then goes back to Transfer Screen. 

So opening another activity and coming back to Transfers does not refresh the info and the notification stays, opening another fragment and coming back to Transfers does. 

Any tips on how to force a refresh? @gubatron

**Comment by gubatron** [comment]
so, when you come back to TransfersFragment, where is that `initStorageRelatedRichNotifications` being called?

ideally the fragment is restored/re-created and that check should be done and if the if on `2.` is not true, we should do: `internalMemoryNotification.setVisibility(View.GONE);`

**Comment by gubatron** [comment]
<img src=https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif>
