### ISSUE TITLE
XXE in UpdateMessageReader.java via Man-in-the-Middle (MitM)

### ISSUE THREAD

**Issue by ProDigySML** [frostwire/frostwire#829]
# The Issue

An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred

The following code snippets display the usage of `XMLReader` without securely disabling entities:

https://github.com/frostwire/frostwire/blob/7414e3be2ef5ced88a775df7831b7ae382fcf966/desktop/src/com/frostwire/gui/updates/UpdateMessageReader.java#L306

An attacker can Man-in-the-Middle (MitM) the HTTP call to the URL below:

https://github.com/frostwire/frostwire/blob/7414e3be2ef5ced88a775df7831b7ae382fcf966/desktop/src/com/frostwire/gui/updates/UpdateMessageReader.java#L43

# Remediation

https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet

**Comment by trollmad3** [comment]
I don't see this being a issue. There is no login for the frostwire site, but you could steal there cookies.

**Comment by gubatron** [comment]
the issue is a man in the middle attack, where somehow they could serve malicious XML and have FrostWire parse a malicious update URL. But I believe this shouldn't be the case as now the update URL is HTTPS based

**Comment by gubatron** [comment]
I also believe in recent updates [we changed the XMLReader](https://github.com/frostwire/frostwire/commit/fbab7d57b5e385812a77a9fa234b8c6e0b4a491b#diff-6a59654283f3bf41ce87f143dd152ffe)  with the one recommended for JDK12, perhaps the new one `SAXParserFactory.newDefaultInstance().newSAXParser().getXMLReader()` doesn't have the XXE issues.

**Comment by trollmad3** [comment]
@gubatron if the update URL is HTTPS base, will this issue still exist?

**Comment by gubatron** [comment]
I think it's significantly harder, but then again, we changed the XML Reader class for a new one that comes with Java 12.

I'm gonna go ahead and close this.
