### ISSUE TITLE
[desktop/windows]Internet Explorer

### ISSUE THREAD

**Issue by trollmad3** [frostwire/frostwire#831]
We should try to avoid using internet explorer as it is a _very_ outdated browser and a lot of people have it installed. I was trying to look in the code to see how I could change it, and I have no idea.

**Comment by gubatron** [comment]
frostwire does not use IE, it simply opens urls using your default web browser.

**Comment by gubatron** [comment]
If Opera is your default browser and you're seeing IE being opened, then please tell us exactly on what actions you see this behavior, is it with every URL you open in FrostWire? perhaps something needs to be updated in the way FrostWire asks the operating system to open a browser.

Are you on windows 10?

**Comment by trollmad3** [comment]
I am on windows 10. Opera is my default browser and whenever frostwire is done installing a update it would open IE then it goes to the URL: http://www.frostwire.com/download/?os=window&from=launcher&installedVersion=
