### ISSUE TITLE
[desktop] Java 8 -> Java 12 migration

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#835]
This is gonna be a long one.

**Comment by gubatron** [comment]
Progress...
![Screen Shot 2019-03-20 at 5 50 28 PM](https://user-images.githubusercontent.com/163977/54726427-b5b06980-4b38-11e9-8e0e-71e78fa49c11.png)

So far, search, download, playback, library working smoothly.

Gotta package the open jdk runtime next for Mac and Windows

**Comment by gubatron** [comment]
## Progress building a custom JRE using jlink


```bash
if [ -d frostwire-jre.nozip ]; then rm -fr frostwire-jre.nozip/; fi

jlink --no-header-files --no-man-pages --compress=1 --add-modules java.base,java.compiler,java.desktop,java.instrument,java.management,jdk.management.agent,java.naming,java.prefs,java.scripting,java.sql,jdk.jdwp.agent,jdk.net,jdk.unsupported,jdk.security.auth,jdk.pack --output frostwire-jre.nozip
```

If we tar and lzma it

```bash
tar cvf frostwire-jre.nozip.tar frostwire-jre.nozip
lzma -k -z -9 -e --threads=4 -v frostwire-jre.nozip.tar
```

18Mb compressed JRE file (for MacOS so far)
```bash
ls -lth frostwire-jre.nozip.tar.lzma 
-rw-r--r--  1 gubatron  access_bpf    18M Apr  9 10:28 frostwire-jre.nozip.tar.lzma
```

**Comment by frostwire** [comment]
All major issues solved for windows build, wrapping up build scripts and getting ready for testing.

![Screen Shot 2019-04-24 at 9 31 05 AM](https://user-images.githubusercontent.com/1341376/56672626-fb021280-6673-11e9-9baa-3d3f05ac5ae4.png)

**Comment by gubatron** [comment]
[First Windows installer with JDK 12 support is ready.](https://github.com/frostwire/frostwire/releases/tag/frostwire-desktop-6.8.0-build-278-BETA)

Linux's installer is JDK 12 compatible but requires OpenJDK-11 only for now since Ubuntu doesn't yet provide openjdk 12.

Now working on Mac's .app and .dmg is the next challenge.
