### ISSUE TITLE
[desktop] FrostWire for Desktop can't detect latest version of PIA on Windows.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#836]

**Comment by gubatron** [comment]
The solution is to get the interface ID for PIA and then check the active routes and see if it's there.

**Comment by gubatron** [comment]
by parsing the output of `netstat -nr` possibly using regex.

**Comment by aldenml** [comment]
more likely is a minor variation on the description string https://github.com/frostwire/frostwire/blob/master/desktop/src/com/limegroup/gnutella/gui/VPNs.java#L84

**Comment by gubatron** [comment]
what I've noticed is that the ID of the network adapter listed for PIA appears as one of the active network adapters once the PIA connection is established.

**Comment by gubatron** [comment]
oh I see, forgot that we get that through libtorrent, yes, they did change the name :)

That's gonna make it a lot easier.

Thanks so much @aldenml 

Miss you buddy.

**Comment by gubatron** [comment]
yes, it worked!

9441601a86b2598ee3d751f9c716b0d0be95b378
