### ISSUE TITLE
[Question] How to upload torrent?

### ISSUE THREAD

**Issue by trollmad3** [frostwire/frostwire#840]
Sorry for asking such a dumb question, but how would I upload a `.torrent`? Is there any way or was this option removed?

**Comment by gubatron** [comment]
there has never been an option to "upload a .torrent"

You can create .torrent files (which have magnet links)

You have to upload a .torrent using your browser or email to wherever you need to upload it.

Or you can paste a magnet link wherever you need to share it.

Hope this helps.
