### ISSUE TITLE
[www] website currently having issues / CSS, CDN

### ISSUE THREAD

**Issue by jjgalvez** [frostwire/frostwire#841]
I know this isn't the best place to post this so I apologize in advance, I just couldn't find anyplace, and thought I would at least let you know. Your website is having style issues this morning  and is not rendering correctly.

**Comment by gubatron** [comment]
you're the second person to report although we cannot replicate.

thanks for reporting this.

**Comment by gubatron** [comment]
please give it a try again and let us know if it continues.

If you could send us a screenshot, or the output of the browser's console to know exactly which resource is failing it'd be awesome

**Comment by jjgalvez** [comment]
Still not seeing the styling. I'm attaching both a firefox and a chrome image of the website. Hope it helps


![chrome](https://user-images.githubusercontent.com/5430012/57963536-7b263b80-78f3-11e9-99d8-03725ea7b4cf.png)
![firefox](https://user-images.githubusercontent.com/5430012/57963538-7d889580-78f3-11e9-8736-95d4f63139d5.png)

**Comment by jjgalvez** [comment]
Also not sure if i matters but this in on Arch Linux 
firefox version 66.0.5
chrome version 74.0.3729.157
Happy to get you any other info if it helps

**Comment by jjgalvez** [comment]
don't know if this helps but Chrome shows a single error
![Screenshot from 2019-05-17 22-46-47](https://user-images.githubusercontent.com/5430012/57963671-c3465d80-78f5-11e9-961a-9c54a75c7414.png)

**Comment by gubatron** [comment]
can you try opening this from that same browser, let me know if you get a 404 or some other error

https://static.frostwire.com/vink/css/versions/frostwire.28.css

**Comment by jjgalvez** [comment]
no 404 error, but I do get an encoding error
![Screenshot from 2019-05-18 17-09-41](https://user-images.githubusercontent.com/5430012/57975017-cd1c9f00-798f-11e9-8227-09b111adef45.png)

**Comment by jjgalvez** [comment]
again not sure if it helpful but this is what I'm seeing in the web console 
![Screenshot from 2019-05-18 17-11-55](https://user-images.githubusercontent.com/5430012/57975029-24bb0a80-7990-11e9-8767-2503a157f80b.png)

**Comment by gubatron** [comment]
it's as if there was an issue wirh the gzipped css file.
either something wrong with s3/cloud front http headers or your browser having issues with them, most likely something in our end, but perhaps you may have something funky with your gzip settings

**Comment by gubatron** [comment]
i also have that svg encoding warning on all browsers but when I open that css page, my browser unzips it and shows it fine for me.

can you try opening the page on a private/incognito tab or clear your web browsing cache and restart your browser?

**Comment by jjgalvez** [comment]
I'm getting the same error in a private window. I also tried it on my Android cell phone just to make sure it wasn't my computer and I am getting the same error

**Comment by gubatron** [comment]
i wonder of it has something to do withthe region of the world on which you are hitting the CDN. I'll invalidate the CDN endpoint for that file and make sure that it's served with the righ headers

**Comment by gubatron** [comment]
## Update:

### I've made sure the CDN path to `/vink/css/versions/frostwire.28.css` on static.frostwire.com has been invalidated.

![Screen Shot 2019-05-19 at 3 23 32 PM](https://user-images.githubusercontent.com/163977/57988321-17625680-7a4a-11e9-9910-d3b1f4bce2d8.png)

### I've also made sure the file has the proper metadata `Content-type: text/css` and `Content-encoding: gzip`

![Screen Shot 2019-05-19 at 3 20 07 PM](https://user-images.githubusercontent.com/163977/57988324-20532800-7a4a-11e9-88ba-aa4d4c45ae5d.png)

### Please clear Site Cookies and Cache Data for frostwire.com, this is how you can do it in Firefox
![Screen Shot 2019-05-19 at 3 24 34 PM](https://user-images.githubusercontent.com/163977/57988342-424caa80-7a4a-11e9-8a01-46237f971c05.png)


### All HTTP headers after the refresh on a Private Tab looked perfect
![Screen Shot 2019-05-19 at 3 28 23 PM](https://user-images.githubusercontent.com/163977/57988376-cb63e180-7a4a-11e9-8b5e-89ed6d813656.png)

**Comment by jjgalvez** [comment]
Fixed, I just reloaded the page and its working

**Comment by gubatron** [comment]
Awesome!

Thank you so much.

If you have a US mailing address, please send an email with it to gubatron@gmail.com, would love to send you some Frostwire stickers
