### ISSUE TITLE
cant run frostwire 

### ISSUE THREAD

**Issue by dddeveloperrr** [frostwire/frostwire#850]
Hello
when i want to run frostwire (java -jar frostwire.jar), i get this error message:

os.name="Linux"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.frostwire.gui.theme.ThemeMediator (file:/home/farhad/snap/firefox/common/Downloads/frostwire-6.8.3.amd64/frostwire.jar) to method java.awt.Toolkit.setDesktopProperty(java.lang.String,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of com.frostwire.gui.theme.ThemeMediator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:33)
	at com.limegroup.gnutella.gui.Main.main(Main.java:64)
Caused by: java.lang.UnsatisfiedLinkError: no jlibtorrent in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:806)
	at java.base/java.lang.System.loadLibrary(System.java:1909)
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:27)

**Comment by gubatron** [comment]
are you by any chance running on a 32-bit cpu?
FrostWire is now only 64-bit compatible.

**Comment by bumm13** [comment]
I get a similar error on a 64-bit cpu:

Starting FrostWire...
Java exec found in PATH. Verifying...
Suitable java version found [java = 11.0.5]
Configuring environment...
Loading FrostWire:
os.name="Linux"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.frostwire.gui.theme.ThemeMediator (file:/usr/lib/frostwire/frostwire.jar) to method java.awt.Toolkit.setDesktopProperty(java.lang.String,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of com.frostwire.gui.theme.ThemeMediator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
FrostWire version 6.8.3 build 291
OpenJDK 64-Bit Server VM Private Build 11.0.5 Oracle Corporation

**Comment by gubatron** [comment]
@bumm13 can you tell us more about your Linux environment, see if we can try and replicate the issue. Your output doesn't show any errors, these are warnings we see in all operating systems when the app starts, we see no "Exceptions" being thrown like OP's.

**Comment by mailinglists35** [comment]
is there any chance the 32bit version to get security only updates? I have a 32 bit windows machine that is impossible to convert to 64 bit :(
