### ISSUE TITLE
[common/search] Add TamilRockers and VPN to torrent search sites as many of them are banned 

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#851]
Can you guys please add TamilRockers and mask the torrent search engine urls via proxy. So that it can be available in every country.

**Comment by gubatron** [comment]
no bandwidth for this one, feel free to submit a pull request that only touches this.

Basically implement a new search performer in `common/` and then plug it into the Search Engine classes for both desktop and android. Which reminds me I'd love to refactor the search engine class into common and have it in a single place sometime this year.

**Comment by fahimanwer** [comment]
Can we add proxy to the search engine so that we can have much more better result from any country? I have implemented proxy on my webview application and it is working fine.

**Comment by fahimanwer** [comment]
I am also learning java and android development, and I really want to thank you guys for creating an open source project like this. I know its not the correct place to thank u guys.

**Comment by gubatron** [comment]
great news, the best way to learn in my experience is to try doing things with the technology, it'll force you to ask a lot of questions and try things.

**Comment by gubatron** [comment]
not implementing this one, that tamilrockers site, at least the one I found looks too sketchy
