### ISSUE TITLE
[desktop/critical] torrents upload/seed despite setting set to not seed

### ISSUE THREAD

**Issue by iostonykraft** [frostwire/frostwire#852]
While downloading a torrent, the torrent starts seeding despite setting set to not seed. This only occurs while downloading and not after its finished.

**Comment by gubatron** [comment]
that's how the bitcoin protocol works, not a bug, a feature.
During download you must exchange pieces, it's part of the protocol.

You're only considered a "Seed" once you have 100% of the torrent pieces.
