### ISSUE TITLE
Android Q file size 0 byte

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#853]
In Android Q the file size is 0 byte. But when I checked the folder I found the same file the .bin extension at the with actual file size.

**Comment by fahimanwer** [comment]
![Screenshot_2019-12-18-13-36-02-730_com android fileexplorer](https://user-images.githubusercontent.com/36186398/71067878-623c7c00-219b-11ea-812c-d74ebf9729b4.jpg)
Here is the proof and the torrent file I am downloading is any video.

**Comment by fahimanwer** [comment]
@gubatron @aldenml please have a look on this issue. I am unable to download anything in my android 10 device.

**Comment by gubatron** [comment]
hmm. not sure what if the .bin file extensions are considered by android or frostwire as video files, I've to check the code.

Please make sure you're running the latest version of FrostWIre and make sure you give it all the permissions it asks to access your files.

Here's our latest build from 2 days ago, please try it and let me know if you still have issues
https://github.com/frostwire/frostwire/releases/download/frostwire-android-2.1.8-build-610/frostwire-android-release-2.1.8-b610-plus.apk

**Comment by fahimanwer** [comment]
Sure, I will let you know.

**Comment by fahimanwer** [comment]
It is still happening. Steps to produce the error. The size of the bin file is exact as the size of the file. It is just adding bin extension at the end of the file. If I remove bin the video is playing. 
File I am downloading: magnet:?xt=urn:btih:b39e512780a98d3cfd8fc16b41a01d3ce17db779&dn=The.Blacklist.S07E10.HDTV.x264-SVA%5bettv%5d&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80&tr=udp%3a%2f%2fopen.demonii.com%3a1337&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2fexodus.desync.com%3a6969&x.pe=106.208.197.7:56943&x.pe=[2401:4900:1313:1e55:4833:d39d:f4ba:d777]:56943
Image proofs
![Screenshot_20191229-144436_ES_File_Explorer_Pro](https://user-images.githubusercontent.com/36186398/71554769-c4259d00-2a49-11ea-845b-293498e5adcb.png)
![Screenshot_20191229-144422_ES_File_Explorer_Pro](https://user-images.githubusercontent.com/36186398/71554770-c4259d00-2a49-11ea-94e5-17ca947243e0.png)
![Screenshot_20191229-144347_FrostWire_Plus](https://user-images.githubusercontent.com/36186398/71554771-c4be3380-2a49-11ea-8804-b3ea1f83f621.png)
![Screenshot_20191229-144334_FrostWire_Plus](https://user-images.githubusercontent.com/36186398/71554772-c4be3380-2a49-11ea-9af1-02f49f7a2f09.png)
![Screenshot_20191229-143601_Files](https://user-images.githubusercontent.com/36186398/71554773-c4be3380-2a49-11ea-829b-c491a5b66480.png)

**Comment by gubatron** [comment]
deleted the last comment because you posted a link to what seems to be copyrighted content.

However, everything seemed fine, it's just that .BIN files are ambiguous, they could be anything binary, that's why when you remove the .BIN and you keep the .mkv it works, .mkv is a known video format.

**Comment by fahimanwer** [comment]
@gubatron sorry for that, but the problem is still there, when i try to download any video file it creates two file with the same name and one with the bin extension the orignal file is always 0 byte, I always have to remove the bin extension, in order to view the file.

**Comment by gubatron** [comment]
confirmed, this is now on my priority list.
Have already taken a few steps towards a fix.

**Comment by fahimanwer** [comment]
It is happening with the zip files too.

**Comment by gubatron** [comment]
Thanks for that detail, will test with .zip files as well

**Comment by gubatron** [comment]
@aldenml sorry to bother you but I've exhausted all my "grep" and googling powers to figure why this might be happening, perhaps explaining I'll figure it out.

Whenever I do a partial download on android, when the torrent is finished and the list of paths is about to be scanned, say I picked only one file, I tend to see 3 files, the file in question and the two surrounding files which I believe are there for seeding purposes, I believe we called these "part files". 

Here's the weird part, the scans are consistently failing and when you look at the files with the Android Device File Explorer, it seems like the actual file that you want has a ".bin" suffix in the name, and what should be the part file and doesn't have the ".bin" suffix is sized 0.

Here's a couple of screenshots, it happens with any mime type:
![Screen Shot 2020-02-17 at 3 45 39 PM](https://user-images.githubusercontent.com/163977/74690654-1a3ad500-519d-11ea-8b65-019464ca8bd0.png)
 
![Screen Shot 2020-02-17 at 3 45 29 PM](https://user-images.githubusercontent.com/163977/74690666-2757c400-519d-11ea-923a-ce5a5177e0b0.png)

I wonder if you remember specifying ".bin" as the extension of the part files, or if this is something that got added to libtorrent in recent versions,  I can't find anything in google

**Comment by gubatron** [comment]
... noticed "finalCleanup()" wasn't called upon finishing... testing fixes.

**Comment by gubatron** [comment]
Some progress, now if you pick 3 files, it will scan 2...

https://github.com/frostwire/frostwire/commit/90f65dd1a2304023cad8e858a0ded9602256f6fc

taking a look at how BTDownload.getIncompleteFiles() works, seems a bit weird what's happening when it looks at the numbers in terms of progress per file, vs actual file sizes on disk.

I wonder if "progress" only considers what's been downloaded for the session, which would make the calculation not be very good if you paused, shutdown and came back.

**Comment by aldenml** [comment]
@gubatron this looks strange to me, I recall having those contiguous files as something from the past, with the parts files, all that was "fixed", and nothing has changed, look here for the naming of it https://github.com/arvidn/libtorrent/blob/57cd2882d471a6eb40090ddce325ac00392be133/src/storage.cpp#L95

Is the same behavior in `frostwire-desktop`? What about other clients?

**Comment by gubatron** [comment]
it's not the same on desktop, it's only on android that it's adding the ".bin" (just checked a few minutes ago by pausing a torrent download and checking the folder)

Checking `storage.cpp`

A million thanks for taking a look

**Comment by gubatron** [comment]
(Hell broke lose with 1.2.4, I'm also getting a freeze on shutdown that people are reporting)

**Comment by gubatron** [comment]
[Renaming completed files that still have the .bin extension](https://github.com/frostwire/frostwire/commit/a81986d2c32af49a28f0fd32d9ef94a24ff07a77#diff-5c48fc68175a09d3b1c49d8f14a3fa9dR38) seems to help

@fahimanwer If you know how to build from source, you should `git pull origin master` and give it a try to see if your problem goes away now. Seems to be working for me now, in the worst case, I can open the file from Transfers if it cannot be scanned by Android (to show up on My Files)

**Comment by fahimanwer** [comment]
Sure, let me check sir.

**Comment by fahimanwer** [comment]
Solved for me.

**Comment by fahimanwer** [comment]
Problem

**Comment by fahimanwer** [comment]
Problem is still there, if I am downloading more than 2 files in a single torrent, one of them is getting a bin extension, and I have noticed that this problem is specially with mkv extension videos

**Comment by marla-hub** [comment]
Don't know how, but the problem is solved.

**Comment by fahimanwer** [comment]
Don't know how but the problem is solved now. Downloaded more than 10 files to test.
