### ISSUE TITLE
Solution for most of the problems 

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#855]
I saw one more open source app related to frostwire and it has implemented all the features. Please check it out https://gitlab.com/proninyaroslav/libretorrent/tree/master

**Comment by gubatron** [comment]
very funny, happy new year.

That app is powered by libretorrent4j, which is a fork of FrostWire's jlibtorrent.

**Comment by fahimanwer** [comment]
Sorry I have started to learn, I don't know much.
