### ISSUE TITLE
[common] No result From SoundCloud 

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#858]
Sir, results from SoundCloud vanished again.

**Comment by gubatron** [comment]
Thanks for notifying, I'm almost done wrapping some major refactors and I'll get back to fixing search.

**Comment by gubatron** [comment]
issue confirmed

**Comment by gubatron** [comment]
[issue fixed](https://github.com/frostwire/frostwire/commit/6fbdf55a082a9a00d2ecd87be8b8900ff1a25acb)
