### ISSUE TITLE
[common] No result From SoundCloud

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#862]
No result from soundcloud again.

**Comment by gubatron** [comment]
Thanks! will fix soon

**Comment by gubatron** [comment]
can't replicate, works fine on both windows and android
![Screen Shot 2020-01-31 at 10 39 18 AM](https://user-images.githubusercontent.com/163977/73561320-03af2280-4416-11ea-9b96-cd340e0c4035.png)
