### ISSUE TITLE
[common] MagnetDL search source

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#865]
If you want to leave a mark and send this as your first patch, start by looking in `common/` at the `LimeTorrentsSearchPerformer`,`LimeTorrentsSearchResult` search performer classes and the test code at `./desktop/src/test/java/com/frostwire/tests/LimeTorrentsTest.java` to see how these are used. Then how they're integrated into the `/desktop` and `/android` project's `SearchEngine` classes.

You should end up with a new package `com.frostwire.search.magnetdl.*` with classes in the following new files:
`./common/src/main/java/com/frostwire/search/magnetdl/MagnetDLSearchPerformer`
`./common/src/main/java/com/frostwire/search/magnetdl/MagnetDLSearchResult`
`./desktop/src/test/java/com/frostwire/tests/MagnetDLTest.java`

An easy start is to copy-paste the LimeTorrents* files into the new ones and start renaming and hacking away the regular expressions.

**Comment by RosarioAleCali** [comment]
Hi, this is the first time for me contributing to a project here on GitHub! If you need some help, I can help you with this issue!

**Comment by gubatron** [comment]
Oh!, I'm afraid I just [finished this one today](https://github.com/frostwire/frostwire/commit/cf20e61f2931ed06ea8b65787529ef88a6539492)! :(

Wish I had seen your message, but please do look around the other issues and let me know if you'll tackle one of them.

Thank you for your interest!

**Comment by gubatron** [comment]
@RosarioAleCali 

This might be a great issue to look into for our next desktop release
https://github.com/frostwire/frostwire/issues/821

**Comment by RosarioAleCali** [comment]
@gubatron No worries! Yes, I can take a look at that one! It might take me a while to fix but I'll keep you posted. Is there some deadline for the next desktop release?
