### ISSUE TITLE
[android] Downloads are pausing for no apparent reason

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#87]
I've completely uninstalled FrostWire from my device, cleared all files, installed from scratch.

I'm connected on Wi-Fi full signal, no other downloads, I start downloading the latest promos, including "Steal This Show" which is a .torrent we didn't create ourselves, and pretty much all downloads go to "Paused" state after a few seconds.

I've yet to do another test by running from source on master to see if this issue has gone away with the latest jlibtorrent binaries. My initial thoughts are that this may have something to do with Session parameter tunning on android.

However, @aldenml might have a better idea what may have introduced this issue.

Fixing this should be our #1 priority this week.

**Comment by aldenml** [comment]
A few questions, since I tested right now and downloaded all the promos without any issue.
- "installed from scratch" means from Google Play?
- Even with full Wi-Fi signal, did you confirm having a smooth connectivity? HTTP is know to be very robust, but looking an online non-cached video should reveal if there are connectivity issues.
- Where you having less than 4 torrents downloading or all of them went to "Paused"?

**Comment by alejandroarturom** [comment]
Same Issue here.
I had 1 torrent downloading. After a minutes, it paused.
FrostWire Plus 1.7.0. build 9000232
Galaxy J7
Android 5.1.1.

**Comment by alejandroarturom** [comment]
I tested on two different wifi signals (at mall and at home).

**Comment by aldenml** [comment]
Interesting, @alejandroarturom  can you test FrostWire Basic (from Google Play)? Are you saving to internal storage or external? Thanks

**Comment by alejandroarturom** [comment]
@aldenml Internal storage. Let me test FrostWire Basic

**Comment by alejandroarturom** [comment]
Also, I'm not using a VPN on my Samsung.

**Comment by alejandroarturom** [comment]
FW Basic is not pausing when downloading torrents.

**Comment by gubatron** [comment]
Plus from the website isn't pausing for me. Testing from sources.

**Comment by muckachina** [comment]
I cannot reproduce this issue on FrostWire 1.7.1 (build 237) although some users are complaining about it. Tested on LG Android 5.0.2, Sony Xperia Android 5.1, Android 4.4
