### ISSUE TITLE
[android] Android App Bundle

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#871]
https://developer.android.com/platform/technology/app-bundle

**Comment by fahimanwer** [comment]
It really reduces the size of the app by 50% without any issue.

**Comment by gubatron** [comment]
I'm just wondering the acrobatics we'll have to do to distribute our app.
If we distributed installers for each architecture it would reduce even more than 50% since we include a bunch of dynamic libraries for all architectures ARM32, ARM64, x86 and x86_64

Will most likely try to get this ticket out the door for our next release

**Comment by gubatron** [comment]
Finally got this one down, indeed it reduced the app size by 50% in the best case.

**Comment by fahimanwer** [comment]
Told you.
