### ISSUE TITLE
[android] Music Wont Play

### ISSUE THREAD

**Issue by tarzar03** [frostwire/frostwire#874]
After I installed the new update I haven't been able to listen to music ever since. No matter how many times I try. When I click on a song to listen it says this:
![Screenshot_2020-03-09-08-42-18](https://user-images.githubusercontent.com/61976913/76218267-ed993c80-61e1-11ea-8816-509af43baa21.png)

**Comment by gubatron** [comment]
try either Force Stopping the app or restarting the phone
