### ISSUE TITLE
[android] Searchengine giving http error

### ISSUE THREAD

**Issue by fahimanwer** [frostwire/frostwire#876]
I tried to implement your method of mirror URLs from TPB to MagnetDL and Limetorrents, As the URL you have added in the app is blocked by my ISPs. But I am getting 503 from these URLs and they are opening in my browser.
**The Code I changed**:
public static final SearchEngine EZTV = new SearchEngine("Eztv", Constants.PREF_KEY_SEARCH_USE_EZTV) {
        private String domainName = null;
        @Override
        public SearchPerformer getPerformer(long token, String keywords) {
            if (domainName == null) {
                throw new RuntimeException("check your logic, this search performer has no domain name ready");
            }
            return new EztvSearchPerformer(domainName,token, keywords, DEFAULT_TIMEOUT);
        }
        protected void postInitWork() {
            // while this is happening TPB.isReady() should be false, as it's initialized with a null domain name.
            new Thread(() -> {
                HttpClient httpClient = HttpClientFactory.getInstance(HttpClientFactory.HttpContext.SEARCH);
                String[] mirrors = {
                        "eztv.io",
                        "**eztv.unblockninja.com**",
                        "eztv.unblocknow.icu",
                        "eztv.mrunblock.xyz",
                        "eztv.unbl0ck.red",
                };
                domainName = UrlUtils.getFastestMirrorDomain(httpClient, mirrors, 6000000);
            }
            ).start();
        }
**Console Output**:
I/System.out: UrlUtils.getFastestMirrorDomain() -> magnetdl.unblockninja.com responded in 2902ms
    UrlUtils.getFastestMirrorDomain() -> magnetdl.unblockninja.com is new fastest mirror (2902ms)
W/System.err: UrlUtils.getFastestMirrorDomain() -> thepiratebay.vip errored HTTP 403 in 4963ms
W/System.err: UrlUtils.getFastestMirrorDomain() -> magnetdl.unblocknow.icu errored HTTP 503 in 3549ms
I/System.out: UrlUtils.getFastestMirrorDomain() -> thepiratebay-unblocked.org responded in 2414ms
I/System.out: UrlUtils.getFastestMirrorDomain() -> thepiratebay-unblocked.org is new fastest mirror (2414ms)
W/System.err: UrlUtils.getFastestMirrorDomain(): www.limetorrents.info unreachable, not considered
W/System.err: UrlUtils.getFastestMirrorDomain() -> limetorrents.mrunblock.xyz errored HTTP 503 in 1635ms
W/System.err: UrlUtils.getFastestMirrorDomain(): www.magnetdl.com unreachable, not considered
I/System.out: UrlUtils.getFastestMirrorDomain() -> Winner: magnetdl.unblockninja.com 2902 ms
W/System.err: UrlUtils.getFastestMirrorDomain() -> limetorrents.unbl0ck.red errored HTTP 503 in 940ms
W/System.err: UrlUtils.getFastestMirrorDomain() -> limetorrents.proxybit.uno errored HTTP 503 in 903ms
I/System.out: UrlUtils.getFastestMirrorDomain() -> Falling back to: www.limetorrents.info

**Comment by gubatron** [comment]
those seem to be proxying services that I have a feeling are either too slow or unreliable.
