### ISSUE TITLE
Lot of hits on Virus total for Windows version

### ISSUE THREAD

**Issue by E3V3A** [frostwire/frostwire#878]
There are a lot of hit on virus total for the windows version. 
How can we deal with this? 
How can we ensure the users that these are not real? (Or are they?)

* https://www.virustotal.com/gui/file/067df9d73921b69270e13a15fb479576a435d459b79874dffbf030ac70607e0a/detection

**Comment by gubatron** [comment]
hmm, this is REALLY weird: "FrostWire 6
frostwire-6.8.4.windows.github.exe"

That file doesn't even bundle any offers, that's a clean installer which we distribute on github.com and sourceforce.com, if we put installers with bundles in such domains we would immediatly get flagged. And actually, it's been a while we don't embed anything in those installers, when you get an offer it's through a stub that then downloads the bundle free installer.

Also it seems like they might be very old reports, for instance, OpenCandy is a partner that shut down its business over 4 years ago If I remember correctly.

![Screen Shot 2020-04-16 at 5 59 56 PM](https://user-images.githubusercontent.com/163977/79517691-27910600-800c-11ea-9b17-65134c9efd31.png)

**Comment by ptanmay143** [comment]
microsoft/winget-pkgs#14072
Even trying to add Frostwire to the new Windows Package Manager is failing.
