### ISSUE TITLE
[android] Ad display UX revision / SDK updates + Integrations

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#880]
- [ ] Do not display interstitials after resuming the app, even if it's been hours, it's just a shitty experience that pisses people off. Only show interstitials after actual sustained engagement
 - [ ] Update all existing SDKs to their latest versions
 - [ ] Test that all existing SDKs/Adapters are working as expected
 - [ ] Possible Facebook Ad SDK integration
 - [ ] Remove poorly performing SDKs/Adapters

**Comment by kad3mlia** [comment]
Added all to Project: https://github.com/frostwire/frostwire/projects/8
2020 Monetization Optimizations

**Comment by gubatron** [comment]
> Remove poorly performing SDKs/Adapters

@kad3mlia: would you have any feedback with respect to this item?
Should I procede ro remove any existing SDKs/Adapters or leave as is?

**Comment by fahimanwer** [comment]
When can we expect Frostwire 3.0?
