### ISSUE TITLE
[common] idope.se support

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#885]

**Comment by gubatron** [comment]
@HimanshuSharma789 would you like to try doing this one for a bounty of USD $50? (Paid in cryptocurrency)

This one is a lot easier since you don't need to do secondary search result matching, and search results come in a lot faster since they can be parsed out as magnet links (`TorrentSearchPerformer`, see `Torrentz2SearchPerformer`)

**Comment by HimanshuSharma789** [comment]
Sure 😅.
Would love to contribute .

**Comment by gubatron** [comment]
Awesome, will assign this issue to you then.

**Comment by HimanshuSharma789** [comment]
i already started working on it
check pull request 😄

**Comment by gubatron** [comment]
You rock!

Merged
https://github.com/frostwire/frostwire/commit/0e8ccbf515d48c6708c6772848e46d2b44b35e37
