### ISSUE TITLE
[website] Remove app-ads.txt Entries from MobFox

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#887]
Here are the lines to be removed:

mobfox.com,62070,DIRECT,5529a3d1f59865be

appnexus.com,2637,RESELLER,f5ab79cb980f11d1
tremorhub.com, l85rl-uxscq, RESELLER, 1a4e959a1b50034a
video.unrulymedia.com, 3589813809, RESELLER
pocketmath.com, 29, RESELLER
appnexus.com,2850,RESELLER,f5ab79cb980f11d1
openx.com,539249210,RESELLER,6a698e2ec38604c6
pubmatic.com,156451,RESELLER,5d62403b186f2ace
rhythmone.com,3589813809,RESELLER,a670c89d4a324e47
rubiconproject.com,13132,RESELLER,0bfd66d529a55807
rubiconproject.com,17494,RESELLER,0bfd66d529a55807
xad.com,589,RESELLER,81cbf0a75a5e0e9a
aceex.io,6,RESELLER

**Comment by gubatron** [comment]
```diff
app-ads.txt.tpl
-aceex.io,6,RESELLER
-appnexus.com,2637,RESELLER,f5ab79cb980f11d1
-appnexus.com,2850,RESELLER,f5ab79cb980f11d1
-mobfox.com,62070,DIRECT,5529a3d1f59865be
-openx.com,539249210,RESELLER,6a698e2ec38604c6
-pocketmath.com,29,RESELLER
-pubmatic.com,156451,RESELLER,5d62403b186f2ace
-rhythmone.com,3589813809,RESELLER,a670c89d4a324e47
-rubiconproject.com,13132,RESELLER,0bfd66d529a55807
-rubiconproject.com,17494,RESELLER,0bfd66d529a55807
-tremorhub.com,l85rl-uxscq,RESELLER,1a4e959a1b50034a
-video.unrulymedia.com,3589813809,RESELLER
-xad.com,589,RESELLER,81cbf0a75a5e0e9a
```
