### ISSUE TITLE
[android] Review Google Policy Updates

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#888]
We've updated our Deceptive Behavior policies to emphasize functionally deceptive apps and our requirement to provide accurate disclosures and metadata.
We’ve introduced a Manipulated Media policy for apps that spread or create altered media.
We’ve updated our Malware policy. Visit the Google Play Protect site for additional information about enforcement and reporting malware.
We’ve updated our Subscriptions policy to ensure transparent communication of subscription offers.
Developers with apps currently on Google Play will have 60 days from the issuance of this notification to bring their apps into compliance with the Subscriptions policy to prevent removal.
We’ve rebranded the Ad Network Certification program to the Families Ads Program.
We’ve updated our Families policy to include disclosure of collecting personal and sensitive information from children.
We’ve updated our Families policy to provide further clarification on Bluetooth use.
We’ve updated our Families Ads and Monetization policy to prohibit ads and monetization practices that are spammy and/or manipulative.
We’ve launched our Location policy to promote transparency and limit inappropriate access to location data especially in the background.
Because compliance with the Location policy may require substantial changes to your app, affected developers will have an extended timeline to make any necessary updates. To view timelines and other updates, please visit our Help Center.
The following enforcement timelines will apply to these policies (with the exception of the Location policy):

Any new apps or app updates published after this notification will immediately be subject to the latest version of the Developer Program Policies.
Apps currently on Google Play will have 30 days from the issuance of this notification to come into compliance to prevent removal, except for the Subscriptions policy which will have 60 days.

**Comment by gubatron** [comment]
This was published on April 16, and now they say it's only 30 days (11 more days)
https://play.google.com/about/updates-resources/
