### ISSUE TITLE
[android] Update GDPR consent mechanism

### ISSUE THREAD

**Issue by Paulinka** [frostwire/frostwire#890]
GDPR incremental consent is live 

Publishers on MoPub SDK 5.11 and above can now collect GDPR Incremental Consent from users. Publishers that re-prompt users for consent enable demand partners that joined after May 25, 2018 to show personalized ads [when GDPR applies](http://s1259914507.t.en25.com/e/er?utm_campaign=MOPUB_NL_GBL_EN_April_Pub_Newsletter_200407_Version_B&utm_medium=email&utm_source=Eloqua&s=1259914507&lid=24446&elqTrackId=2E75E208DCB70CAE09EB7587A5164971&elq=971b411185a74b6f9741da6828147df9&elqaid=14467&elqat=1), given a user provides consent. This helps unlock spend from several top buyers. Be sure to update to the latest SDK to gain access to MoPub incremental consent. 
[Check out more details on incremental consent](http://s1259914507.t.en25.com/e/er?utm_campaign=MOPUB_NL_GBL_EN_April_Pub_Newsletter_200407_Version_B&utm_medium=email&utm_source=Eloqua&s=1259914507&lid=24740&elqTrackId=5CB19BA86211DDD850168D8145BAEF6F&elq=971b411185a74b6f9741da6828147df9&elqaid=14467&elqat=1)

**Comment by gubatron** [comment]
just double-checked and we already do ask for the consent dialog wherever it applies.

I'll force the dialog tomorrow to see that their new more fine-grained consent flow is working as expected.
