### ISSUE TITLE
[android] Fix Subscriptions cancelled by Google within 72hrs

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#891]
Looks like google has implemented a 'feature' in one of past versions of their billing library, where they now require every purchase to be acknowledged or else it will be refunded. 

From Google
"If you use the Google Play Billing Library version 2.0 or newer, you must acknowledge all purchases within three days. Failure to properly acknowledge purchases results in those purchases being refunded.

Google Play supports purchasing products from inside of your app (in-app) or outside of your app (out-of-app). In order for Google Play to ensure a consistent purchase experience regardless of where the user purchases your product, you must acknowledge all purchases that have a SUCCESS state received through the Google Play Billing Library as soon as possible after granting entitlement to the user. If you do not acknowledge a purchase within three days, the user automatically receives a refund, and Google Play revokes the purchase."

See more details and code examples here:
https://developer.android.com/google/play/billing/billing_library_overview#acknowledge

**Comment by gubatron** [comment]
After we migrated to 2.0 we pretty much lost every other new subscriber right away because of this change

From:
https://developer.android.com/google/play/billing/billing_library_overview#acknowledge

"If you use the Google Play Billing Library version 2.0 or newer, you must acknowledge all purchases within three days. Failure to properly acknowledge purchases results in those purchases being refunded."

There are different ways to acknowledge the purchase depending on the type.

```java
private BillingClient mBillingClient = BillingClient.newBuilder(mActivity).setListener(this).build();

AcknowledgePurchaseParams acknowledgePurchaseParams =
            AcknowledgePurchaseParams.newBuilder()
                    .setPurchaseToken(purchase.getPurchaseToken())
                    .build();

//For non-consumables:
mBillingClient.acknowledgePurchase(acknowledgePurchaseParams, new AcknowledgePurchaseResponseListener());

//For Consumables: (but I believe we'll get rid of consumables altogether and just simplify into subscriptions, users can try for free, which they cannot in the case of consumables)
client.consumeAsync(acknowledgePurchaseParams, acknowledgePurchaseResponseListener)
```
