### ISSUE TITLE
[website] Update ExpressVPN affiliate Links

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#893]
Please replace linkev.com with xvbelink.com in all of your URLs.

The new redirect domain has exactly the same behavior as linkev.com

For example:
Existing Link: https://www.linkev.com/?a_fid=1234

Changes to: https://www.xvbelink.com/?a_fid=1234

If you are using multiple landing pages or your own redirect system it might be easiest if you can write a script to replace linkev.com with xvbelink.com in all of your outgoing URL strings.

xvbelink.com will remain your unique redirect domain going forward.

Updates were suppose to be made by 16th April 2020, so we are a bit late.

**Comment by gubatron** [comment]
Fixed on website and android
