### ISSUE TITLE
[android] Network Ad Performance Review - all info in one place

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#894]
This ticket is for your information only to provide an overview of situation in one place:
- We have about 39M monthly requests
- We have about 25M monthly impressions
- Our fill rate is 63% overall 
- Our big three networks: AppLovin, Unity and MoPub have similar fills of 20-25% each.
- Unity has the worse CPMs - currently working with monetization support to improve things - stay tuned
- AppLovin has the best CPMs, but mainly for interstitials (still low $3-4), but super low for banners.
- We currently have only one tag based network active. AerServ was acquired by InMobi and they booted us because of the torrent thing, some others either dropped us or I dropped them when they stopped paying and their fill/cpm dropped so much that we were making less than $20/month for several months straight and all possibilities of improvement were exhausted. Most recently I dropped AdView because of impression reporting discrepancies, but other parts of relationship were ok.

Problems
- general fill could be higher - my achievable goal would be 80%
- interstitials reporting 6.73% fill - causes lower CPM bids and less interest in the product. It just doesn't look very appealing to buyers
- rewarded video is reporting 0.15% fill - causes lower CPM bids and less interest in the product. It just doesn't look very appealing to buyers
- very low CPM for banners - across the board - about $0.05 for the bulk of it

Solutions:
- [ongoing] conversation with Unity to improve CPM
- [Wed 4/22] conversation with AppLovin to improve CPM
- implement more advertising partners and rely more on SDK integration rather than tags
- [Implement Facebook Audience Network](https://github.com/frostwire/frostwire/issues/895)
- Consider Implementing AdView SDK - more info and links to their CodeBase and integration instructions shortly
- Consider Implementing PubMatic SDK if AdView will not work
- [Solve interstitial low fill problem](https://github.com/frostwire/frostwire/issues/896)
- [Solve rewarded video low fill problem](https://github.com/frostwire/frostwire/issues/896)
- have a discussion on best ad placement and interstitial timing

**Comment by gubatron** [comment]
oh no, moved to private tracker
