### ISSUE TITLE
[common/search] The Pirate Bay domain updated and needs correction

### ISSUE THREAD

**Issue by Frostyyyyy** [frostwire/frostwire#898]
The Pirate Bay's domain was recenlty updated and needs to be corrected in the next FrostWire release. See [here](https://thepiratebay.org)

Also, additional sources should be added in next FW update for enhanced search results. 

Two excellent ones not currently implemented are:

1)  kickasstorrents.cr
2)  1337.to

**Comment by fahimanwer** [comment]
All these domains are blocked in India, please developers find a solution. @gubatron 
![image](https://user-images.githubusercontent.com/36186398/80343240-24efa580-8883-11ea-912c-6220ad9786a1.png)

**Comment by gubatron** [comment]
This seems like an user experience solution.
IDEA: Engines like TPB should have a "Mirror's" setting and the user could decide which mirrors are on/off, and even add their own.

**Comment by gubatron** [comment]
Fixed a few releases ago, forgot to close ticket
