### ISSUE TITLE
[android] Handpicked/Partial/Selective .torrent downloads

### ISSUE THREAD

**Issue by soredake** [frostwire/frostwire#90]

**Comment by gubatron** [comment]
being able to select individual files out of a .torrent before starting a download?

(for now the way to do this, is by connecting via WiFi, when UDP is available, FrostWire for Android should attempt to fetch and query the files inside the .torrent search results and show them as individual files on the rest of the search tabs, it's not exactly what you want but it's close)

Thanks for adding this task to the list, it's a very important feature missing.

**Comment by gubatron** [comment]
@marcelinkaaa changes have been merged. Please test this new functionality throughly @muckachina.
If everything is fine please close this issue.

**Comment by gubatron** [comment]
![13063867_10154156845997863_758757601_o](https://cloud.githubusercontent.com/assets/163977/14731479/0fa14a70-080e-11e6-8ccd-6c846ee39305.png)
