### ISSUE TITLE
Lost music

### ISSUE THREAD

**Issue by musicman43** [frostwire/frostwire#900]
I have the free up to date version of frostwire and went to listen to my Playlist and 90% of the music is gone that I downloaded. What happened?

**Comment by gubatron** [comment]
did you by any chance have an SD card as your save folder, and uninstalled the app? then installed it again?

**Comment by musicman43** [comment]
As soon as I sent the email I remembered the sd card that was in the phone I had was encrypted and had to decrypt. All is good. Thank you
On Wednesday, May 6, 2020 Angel Leon <reply@reply.github.com> wrote:



did you by any chance have an SD card as your save folder, and uninstalled the app? then installed it again?
