### ISSUE TITLE
[android] Settings Screen Improvements

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#902]
1. Add 'Find FrostWire Online'
  - Link to FB
  - Lin to Twitter
  - Link to Blog
2. Add Rate Us link 
3. Add Community/Partners section
  - link to VPN provider or providers
  - find another app group of companion apps to cross promote

**Comment by fahimanwer** [comment]
Hey Devs, till when can I expect Version 3.0? I am really excited.

**Comment by gubatron** [comment]
3.0 is still a long way, but last night we released a new build.

Today working on jlibtorrent updates, which I think you're interested in.

3.0 should improve search experience in all countries.

**Comment by fahimanwer** [comment]
That's why I am waiting for 3.0

**Comment by gubatron** [comment]
[First 2.2.1 build is out today](https://blog.frostwire.com/2020/06/17/new-frostwire-2-2-1-with-libtorrent-jlibtorrent-1-2-7-is-the-fastest-version-ever/) with libtorrent/jlibtorrent 1.2.7.0

**Comment by gubatron** [comment]
First iteration done.

<img width="669" alt="Screen Shot 2020-07-13 at 11 17 46 PM" src="https://user-images.githubusercontent.com/163977/87387058-274acd00-c55f-11ea-9576-29002d8ca9cb.png">


Still gotta add links/buttons to:
-> Rate us
-> Official Blog

**Comment by gubatron** [comment]
Finished with 0e9b1177692866433b0a47a8f7e6dfabd8d61096
