### ISSUE TITLE
[android] Player - Repeat forever bug (USD $50 in cryptocurrency bounty)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#906]
Steps to reproduce.

1. Start playing a song with "Repeat forever" mode on.
2. Play the song once until the end (fast forward if you want)
3. The song will repeat, however, the second time around the player stops. If you hit next, it plays the next song.

Theory:
This suggests that when the new player instance is created it's not carrying on correctly the playback mode that was set by the previous player.

**Comment by gubatron** [comment]
@HimanshuSharma789 Maybe you'd like to get dirty with this one.

This is basically a never ending refactoring of an open source music player we integrated years ago called Apollo.

I've managed to simplify its code base greatly over the years, this is one annoying bug in playback.

**Comment by gubatron** [comment]
Will also pay $50 in BTC or ETH for this bug to be fixed.

**Comment by HimanshuSharma789** [comment]
I cannot debug it properly but figured out something.
![image](https://user-images.githubusercontent.com/32963903/88362602-b4312a00-cd9a-11ea-91e2-b5bb5d53de77.png)
Whenever the track is ended it calls duration function to fetch audio length. I works perfectly for the first time but the second time it returns -1 (as audio duration). This is causing this problem.

`mCurrentMediaPlayer != null `    ----->    but still `mCurrentMediaPlayer.getDuration();` generates error which leads to -1 from the catch block

**Comment by gubatron** [comment]
awesome find.
when it generates the error, is it by anychance some sort of invalid state for the player when that happens?

any ideas on how to go about this, which doesn't involve caching the last duration value for that track on some temporary place?

**Comment by HimanshuSharma789** [comment]
As u stated in your first comment, you might need to look into variable `mCurrentMediaPlayer` , `(mPlayer)`
I have a feeling its not holding appropriate value as it should have. It might be because these values are not updated properly.

Even though if we return a value (lets say position=1) from above function
>long result = mPlayer.seek(position);

also returns error

**Comment by gubatron** [comment]
Gotta look then into refreshing the reference to mCurrentMediaPlayer, and/or mPlayer.
Perhaps when the song ends the first time, the player is destroyed and recreated.

**Comment by gubatron** [comment]
fixed with a huge round of fixes on the player this year
