### ISSUE TITLE
[android+desktop] Dark Mode Theme (USD $250 cryptocurrency bounty for each Dark Theme implementation, one android, another in desktop)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#908]
We need help with this one.

We'd need a Dark Mode Theme and a way to change it, ideally without restarting the app with a toggle switch on the Settings screen.

If you have graphic design chops we could pay USD $250 via PayPal or crypto (BTC) on delivery.

Updated: We've added also this bounty for Desktop, another $250

**Comment by FunkyMuse** [comment]
Is this still needed?

**Comment by gubatron** [comment]
Yes.

I gave it a try and ended up in a mess, maybe you can give it a try.

**Comment by gubatron** [comment]
Updated payment to just Paypal or BTC (ETH fees make it impossible at the moment)

**Comment by FunkyMuse** [comment]
> Updated payment to just Paypal or BTC (ETH fees make it impossible at the moment)

I assume the answer is yes

**Comment by marcelinkaaa** [comment]
Created a pull request. Read it's comments. :)

**Comment by gubatron** [comment]
WOHOO!!! Checking!

**Comment by gubatron** [comment]
Linking to Pull Request
https://github.com/frostwire/frostwire/pull/1019/commits

**Comment by gubatron** [comment]
code looks clean, very cool stuff the "tint" concept.

**Comment by gubatron** [comment]
Bounty completed by @marcelinkaaa , merging to next android release 🎉

**Comment by gubatron** [comment]
Added theme switching and preference saving functionality and merged to master
https://github.com/frostwire/frostwire/commit/fc7095bad232654bea851ff64549da54257781e2
