### ISSUE TITLE
FilenameUtils.getExtension(filename) needs to be fixed !

### ISSUE THREAD

**Issue by HimanshuSharma789** [frostwire/frostwire#914]
This function **FilenameUtils.getExtension()** detects the last occurrence of a dot(.) in the filename.
It works good for filename like **"movie 420p.mp4"**, **"movie_name.mkv"**

But it does not work for filename like: (examples)
**"movie_name 420p [torrent.tt]"**
**"movie 720p [EEE.TP]"**

in above cases the we get extension like **".tt]"**, **".TP]"**     ---> which is not displayed on the search page.

**Comment by gubatron** [comment]
I think this a non issue, I'd argue that the examples you are giving are not valid file names.

If you're using that function in a context on which you are not parsing an actual file path, then you should then cleanup the string and first make it look like an actual file.

I'd basically try to clean up the returned extension, I think that case is out of the scope.

Also, the examples that you give are not showing file extensions, those look more like top domains on the internet .tt and .tp.

do you know of a file type ".tt" or ".tp" that have to do with movie file formats?

**Comment by HimanshuSharma789** [comment]
Avengers Endgame (2019) [WEBRip] [1080p] [YTS.LT]
Avengers Infinity War (2018) [BluRay] [720p] [YTS.AM]
these are some examples

I didn't mention proper because of copyright issue u stated before.
When i apply the function on these filenames it does not show the result on Search Activity

**Comment by gubatron** [comment]
yes, those are not file extensions.

**Comment by gubatron** [comment]
in those cases we can set the file extensions to be ".torrent"
