### ISSUE TITLE
[Suggestions / Edits] Some off-topic talks 😅

### ISSUE THREAD

**Issue by HimanshuSharma789** [frostwire/frostwire#917]
There are few things I want to suggest:
1.  There is no such file as run.bat in frostwire/desktop/src. Please remove the line from https://github.com/frostwire/frostwire/blob/master/desktop/README.md 
> If you are using Windows, run the project with run.bat in the src folder.

2.  Also try the Intelij IDE predefined options like:
- Optimize imports
- Code cleanup 
they really do what they say 😎👍

3.  Look at serious issues  #916 , #563 

4. Any developer should also check Discord channel 😅😄. (u guys can also install discord app - works like whatsapp).

5. Looks like desktop application is using deprecated API or something like that. So windows is preventing its install with its  "Potentially Unwanted Application protection feature" (more details in discord-general section).

**Comment by gubatron** [comment]
Did not remove the line as there is a `run.bat` file, it's just not on the `frostwire/desktop/src` folder, it's in the `frostwire/desktop` folder.

[Just fixed the line](https://github.com/frostwire/frostwire/commit/0330a72e09057f3f6f57219fd07cb26c2d549a52)

**Comment by HimanshuSharma789** [comment]
> 
> 
> Did not remove the line as there is a `run.bat` file, it's just not on the `frostwire/desktop/src` folder, it's in the `frostwire/desktop` folder.
> 
> [Just fixed the line](https://github.com/frostwire/frostwire/commit/0330a72e09057f3f6f57219fd07cb26c2d549a52)

yup, i mean the same thing.

**Comment by gubatron** [comment]
>Code cleanup

Use carefully. Some automatic code cleanups can break the codebase in unintended ways.
We've even left some comments in the code because we've seen how those warnings don't actually apply to us.

**Comment by gubatron** [comment]
4. done ([frostwire.com/chat](https://www.frostwire.com/chat))

**Comment by gubatron** [comment]
5. That was InstallCore being flagged, it's solved by talking to them and getting a new sdk from them. But yes, I think there's some stuff that's deprecated and we get the warning on startup, related to illegal reflection access, stuff that we need to change the look and feel I'm afraid (a hack).
