### ISSUE TITLE
Is this bittorrent client a FrostWire client?

### ISSUE THREAD

**Issue by SeaHOH** [frostwire/frostwire#921]
I found string "Unknown FW 6.8.5.3" in uTorren's "Peers" page "Client" column, is it a real FrostWire client?
![p](https://user-images.githubusercontent.com/8470820/88560130-5170b480-d060-11ea-9d79-f89f2e6ebaf6.png)

**Comment by gubatron** [comment]
doesn't seem like it.

**Comment by SeaHOH** [comment]
Thx!
