### ISSUE TITLE
[android] Migrate to AppCompat

### ISSUE THREAD

**Issue by TacoTheDank** [frostwire/frostwire#924]
There are currently over a thousand deprecations in the code right now. With my own tests, migrating to AppCompat brings it down by half. As I don't want to risk messing anything up (and some code changes WILL have to be made, as well as testing on several different devices), I'll let the code maintainer do this. :)

This includes removing/migrating the severely outdated PreferenceActivity (which does not exist in AndroidX preference), and migrating the deprecated preference fragments to their compat counterparts. These additional preference migrations will cut the total number of deprecations by a lot more.

**Comment by gubatron** [comment]
Thanks for bringing this up, as you've seen some parts have already been migrated, but yes, perhaps lots remain.

Perhaps you'd like to tackle migrating `PreferenceActivity`, it's not an easy feat and you will see why, would love to get a patch for this on a separate branch. `PreferenceActivity` might be a good starting point.

Then there's a lot on the Apollo Player that could be migrated as well.

**Comment by gubatron** [comment]
pull request merged, thank you so much!

**Comment by TacoTheDank** [comment]
Oh, this wasn't really related to the PR I made. Migration to AppCompat includes multiple things like:
- android.app. fragment-related classes, replace with androidx.fragment.app.*
- android.content loader-related classes (including android.app.LoaderManager), replace with androidx.loader.app.*
- androidx.preference fragment classes, replace with androidx.preference fragmentcompat classes

That's actually most of them, but some require some code changes that I'm not very confident in making.

**Comment by gubatron** [comment]
>android.content loader-related classes (including android.app.LoaderManager), replace with androidx.loader.app.*

Thanks for bringing this one up. I think I'll tackle this one.
