### ISSUE TITLE
[desktop/linux] Problem with libjlibtorrent.so 6.8.7 (GLIBC_2.27)

### ISSUE THREAD

**Issue by alpvonkri** [frostwire/frostwire#929]
The libjlibtorrent.so included in the frostwire-6.8.7.amd64.tar.gz file seems to have a problem, I had to use the libjlibtorrent.so included in the frostwire-6.8.6.amd64.tar.gz file to work without problems.

Output with the problem:

> HOSTNAME IS 15-ab126la.BlumenSisSer
> Starting FrostWire...
> Java exec found in PATH. Verifying...
> Suitable java version found [java = 15]
> Configuring environment...
> Loading FrostWire:
> os.name="Linux"
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.frostwire.gui.theme.ThemeMediator (file:/home/alpvonkri/Apps/Linux/FrostWire/frostwire.jar) to method java.awt.Toolkit.setDesktopProperty(java.lang.String,java.lang.Object)
> WARNING: Please consider reporting this to the maintainers of com.frostwire.gui.theme.ThemeMediator
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Exception in thread "main" java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
>         at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:33)
>         at com.limegroup.gnutella.gui.Main.main(Main.java:64)
> Caused by: java.lang.UnsatisfiedLinkError: /home/alpvonkri/Apps/Linux/FrostWire/libjlibtorrent.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/alpvonkri/Apps/Linux/FrostWire/libjlibtorrent.so)
>         at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
>         at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
>         at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
>         at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
>         at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:310)
>         at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:282)
>         at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2440)
>         at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
>         at java.base/java.lang.System.loadLibrary(System.java:1893)
>         at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:27)
>         ... 1 more
> 
> 
> ******************************************************************
> Something went wrong with FrostWire.
> Maybe you're using the wrong version of Java?
> (FrostWire is tested against and works best with with Sun's JRE, Java 1.7+)
> The version of Java in your PATH is:
> openjdk version "15" 2020-09-15
> OpenJDK Runtime Environment (build 15+36-suse-lp152.16.1-x8664)
> OpenJDK 64-Bit Server VM (build 15+36-suse-lp152.16.1-x8664, mixed mode)

If more information is needed, please, let me know.
Note: The same happens using Java 11.

**Comment by gubatron** [comment]
Thank you for bringing this to our attention.

This new version was compiled with a newer version of GCC, I wonder if the issue can be solved instead in making sure you have g++7 libraries in your system.

from our changelog:
`* binaries: compiler upgraded from g++-5 to g++-7`

```
Caused by: java.lang.UnsatisfiedLinkError: /home/alpvonkri/Apps/Linux/FrostWire/libjlibtorrent.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/alpvonkri/Apps/Linux/FrostWire/libjlibtorrent.so)
```

Another way to go about it would be to compile the source code in your own machine, going back to 6.8.6 binaries is probably not the best "solution" to the problem, I'm impressed it actually worked for you, I suppose at some point you will have some crashes due to missing symbols referenced by the updated Java code

**Comment by gubatron** [comment]
If you are in Ubuntu or a debian based Linux, please try the following, and try to run with the 6.8.7 libjlibtorrent.so

```
sudo apt-get install -qq g++-7 g++-7-multilib
```

**Comment by alpvonkri** [comment]
Greeting, it's with openSUSE Leap 15.2.

**Comment by alpvonkri** [comment]
Thanks for your time.
The system is openSUSE Leap 15.2, it comes with GLIBC 2.26, and I have GCC7 (gcc-c++) 7.5.0 installed.

**Comment by gubatron** [comment]
My only suggestion is to update your glibc, 2.26 is from 2017!

My Ubuntu is running 2.30 (released August 2019):
```
$ ldd --version
ldd (Ubuntu GLIBC 2.30-0ubuntu2.2) 2.30
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
