### ISSUE TITLE
[android] Expand 'Use 3G/4G for Bittorrent' to include cloud downloads

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#93]
Seems like many people 
a) don't understand the difference between BitTorrent and Cloud downloads
b) forget they are not on wi-fi when downloading
c) get kicked off wi-fi and don't notice
which causes them to unwillingly use their mobile data for downloading. 

I believe with proper messaging when disconnected from wi-fi (when 'Use 3G/4G for Bittorrent' is unchecked) we can make this more user friendly. 

A sticky notification on Transfers would probably do it :)

**Comment by muckachina** [comment]
Cool! this will reduce users complaining for 'data consumption' when 3G/4G option is disabled. 

Enhancement ticket referenced on Android QA repo too. 

Thanks!

**Comment by gubatron** [comment]
This ticket is closely related to #242 (updates to settings)

**Comment by marcelinkaaa** [comment]
I currently have no phone with a data plan to test, is this done by any chance?

**Comment by muckachina** [comment]
I already got a SIM card with data plan @marcelinkaaa 

This is the status of the issue:

> 1) Go to Settings and make sure the option "WiFi networks only" is ON

> 2) Disconnect WiFi on your device

> 3) **Both Cloud files and Torrent files are blocked to download when 'WiFi only' is activated (GREAT) :)**

**But the fix still has a tiny issue:**

> Trying to download an Audio file from SC or YT I get a message saying _"Current Settings prevents downloading when no on WiFi network"_ 

> Trying to download any other file type from Torrent sources I get a message saying: 
_"Torrent transfer will not start until you connect to a WiFi network (Check your network settings regarding 3G/4G data use)"_

> However, when trying to download video files from YT **no message is displayed and FW shows the Transfer list but the file never goes there.** The user could assume the notification at bottom _"BitTorrent is off (Data Saver On)"_ is the reason, but showing the same message as the rest of files would be appreciated 

I will close the issue in any case because is working properly preventing the Data Plan consumption.
