### ISSUE TITLE
[desktop] Stop frostwire complaining about mplayer (in linux)

### ISSUE THREAD

**Issue by demanuel** [frostwire/frostwire#932]
Hi.

Everytime we start frostwire we get the warning popup ["FrostWire requires Mplayer to play your media but I could not find it in your computer"](https://github.com/frostwire/frostwire/blob/01e44e5767d19b14f21f80911ddd65acc616c22f/desktop/src/com/frostwire/gui/player/MediaPlayerLinux.java#L28)

Although [mplayer project](http://www.mplayerhq.hu/design7/news.html) is still not dead, most of the distros moved on to the [mpv project](https://github.com/mpv-player/mpv/)

Please make it possible either to:

1-  stop this checking of happening, so we don't have this warning anymore OR
2-  Make the player configurable (changing the video player in the options, doesn't do anything regarding this warning popup).

Best regards,
David Santiago

**Comment by gubatron** [comment]
2. is pretty much impossible because FrostWire communicates with mplayer and the way it communicates with it will not work for any other player.

So let's do the first option David.

Let's add a checkbox on that dialog that says something like:
`[ ] Don't warn me again about this`

Once that's checked it will not warn you again.

Sounds cool?

**Comment by gubatron** [comment]
Also, thanks for letting me know about mpv project, perhaps the pipe interface we created to talk to mplayer will work with mpv. And we'll probably want to recompile our version of mplayer for windows and mac using the mpv project.

**Comment by demanuel** [comment]
>     1. is pretty much impossible because FrostWire communicates with mplayer and the way it communicates with it will not work for any other player.
> 
> 
> So let's do the first option David.
> 
> Let's add a checkbox on that dialog that says something like:
> `[ ] Don't warn me again about this`
> 
> Once that's checked it will not warn you again.
> 
> Sounds cool?

I'm cool with that.


> Also, thanks for letting me know about mpv project, 

No problem.

>perhaps the pipe interface we created to talk to mplayer will work with mpv. And we'll probably want to recompile our version of mplayer for windows and mac using the mpv project.

Probably. If i'm not mistaken mpv is a fork of mplayer where the devs added the missing features from mplayer2 (mplayer fork) , removed legacy code, and tried to make saner command line options. I also believe that most of the devs of both projects migrated as well to mpv.

More info about the project [here](https://github.com/mpv-player/mpv/blob/a32db637b5c66c0304147caadf02d7b28083bcee/DOCS/mplayer-changes.rst)

**Comment by gubatron** [comment]
Tested integrating mpv and the current interprocess communication protocol would not work with it.
Therefore decided to compile a fresh new version of mplayer for mac and windows, and will make sure mplayer is a dependency for the packaged version.

Will implement a "Don't ask me again" for mplayer setting, so the dialog doesn't become a nag for linux users outside .deb and .rpm distros.

https://github.com/frostwire/frostwire-jmplayer/releases/tag/frostwire-jmplayer-1.5.0-jan-2023

**Comment by peutch** [comment]
Hi,

My 2 cents here.
Would it be possible in the more or less near future to use something like MPRIS 2.2[1] to relax the dependency to a specific media player?
It exists some libraries that may help like: https://github.com/hypfvieh/dbus-java

I am not a Debian Developer but I am very confident on the state and the future of the mplayer package (based on 1.4) in Debian for instance. It is tied to an old ffmpeg (4.4.x vs. 5.1.x) version and may block its transition into the next Debian release, isn't it?  And I do not know if packaging mplayer 1.5 will solve everything.

Thanks!

[1] https://specifications.freedesktop.org/mpris-spec/latest/

**Comment by gubatron** [comment]
I think the ultimate solution will be to have FrostWire focus more on its search and download capabilities and leave things like media playback to the user's favorite player, this way we can focus more on our core functionality.

For now mplayer 1.5 seems to work.

Not sure if even communicating through DBUS to the player's process changes the fact that the commands sent and the output coming out of the player process are different (mplayer vs mpv's input/output)

It's nice to know dbus-java exists though.

**Comment by demanuel** [comment]
hi @gubatron 

I tested frostwire again today, and i still get the warning every time i open frostwire:

![Image](https://github.com/user-attachments/assets/50f708db-04d3-43b1-b187-5a6355df98e4)


I have mpv configured as player:

![Image](https://github.com/user-attachments/assets/6f69a0f5-98c1-446e-b5c8-f816672d1859)

I have version 6.14.0.


Since this was marked as completed, is this expected?

**Comment by gubatron** [comment]
Probably I closed this by mistake, thanks for reminding me of this.
Will remove the notice, so annoying, thank you.
