### ISSUE TITLE
[desktop/windows] Make sure uninstaller clears every registry key created

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#935]
Redditor reports:

[Buggy uninstaller](https://www.reddit.com/r/FrostWire/comments/jhyqvc/buggy_uninstaller/)

Instead of removing the whole program the uninstaller left lots of registry keys and contextual menu options, such bad impression from Frostwire

**Comment by Aholicknight** [comment]
Uninstalling FrostWire leaves these registry keys behind:
![image](https://user-images.githubusercontent.com/7843719/99178532-971dbf80-26d9-11eb-9c46-84f028c23d00.png)

**Comment by gubatron** [comment]
Dude, you are a god send!

Thank you.

**Comment by gubatron** [comment]
This has been fixed with our upcoming 6.8.8 build 299 installer!

The issue was that our Registry deletion was ocurrying for the old 32-bit mode FrostWire application.
Once we turned on `SetRegView 64` in our .nsis script, it worked.

All keys are now removed on uninstall.
