### ISSUE TITLE
[android] Add equalizer to Music Player

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#94]
Got several requests on Google Play to add an equalizer to the player :)

**Comment by gubatron** [comment]
For now,  FrostWire will use a System Equalizer or Default Equalizer App if installed.
Until we have the time to implement one ourself, maybe this is an opportunity to have an offer/deal with the best equalizer apps out there.

**Comment by alejandroarturom** [comment]
I agree with @kad3mlia . I tried a lot of music apps on Android and all of them have a good equalizer. In fact, they promote their apps highlighting the equalizer option.
