### ISSUE TITLE
[desktop/windows] Mozilla VPN detection

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#949]
Users report Mozilla VPN detection false negative.
Most likely an issue with windows.

**Comment by jjgalvez** [comment]
I am having the same issue on Arch with Mullvad, Fristware is reporting that I have no vpn, which should not be the case

**Comment by gubatron** [comment]
@jjgalvez Please do this:
1. Start a VPN session.
2. Open cmd.exe
3. Type:
 **netstat -r**

Please Copy and paste the output (feel free to black out all the ip addresses), I'm interested in any possible clues related to the network interface name, although this doesn't really apply to Linux and the way FrostWire detects VPN there and you mention "Arch" which I believe is a Linux distro.

**Comment by gubatron** [comment]
Closed with 
https://github.com/frostwire/frostwire/commit/ecc768dbb391a5a5151f3f0ff7459202723f9fb0

**Comment by jjgalvez** [comment]
@gubatron  yes Arch is a linux distro. running netstat -t gives the following:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
default         _gateway        0.0.0.0         UG        0 0          0 eno1
10.64.0.1       0.0.0.0         255.255.255.255 UH        0 0          0 wg-mullvad
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eno1
```
Hope it helps

**Comment by gubatron** [comment]
My guess would be that it is `wg_mullvad`

Now, what happens if you turn off the VPN Session and issue `netstat -t` once again, does `wg-mullvad` go away? (just to double check, since that's the same name of your VPN provider)

**Comment by jjgalvez** [comment]
That is correct wg-mullvad goes away

**Comment by gubatron** [comment]
do you know how to build and run frostwire from source?
I can try pushing a patch for you to try.

**Comment by jjgalvez** [comment]
yes I can build it and happy to test

**Comment by jjgalvez** [comment]
@gubatron I've done some more testing. First Mullvad can use either Wireguard or OpenVPN as the backend. I have been using Wireguard. When I switch the backend to OpenVPN frostwire is able to detect the firewall, switching back to Wireguard and detention fails, So I checked the netstat -r output:

OpenVPN
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 eno1
10.10.0.0       0.0.0.0         255.255.0.0     U         0 0          0 tun0
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eno1
```

Wireguard:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 eno1
10.64.0.1       0.0.0.0         255.255.255.255 UH        0 0          0 wg-mullvad
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eno1
```

Taking a hint from ecc768d I edited VPN.java with the following patch which allows mullvad to be detected when using wireguard:
```
desktop/src/com/limegroup/gnutella/gui/VPNs.java | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/desktop/src/com/limegroup/gnutella/gui/VPNs.java b/desktop/src/com/limegroup/gnutella/gui/VPNs.java
index 362faca69..11ce75862 100644
--- a/desktop/src/com/limegroup/gnutella/gui/VPNs.java
+++ b/desktop/src/com/limegroup/gnutella/gui/VPNs.java
@@ -71,7 +71,9 @@ public final class VPNs {
         try {
             List<EnumNet.IpRoute> routes = EnumNet.enumRoutes(BTEngine.getInstance());
             for (EnumNet.IpRoute route : routes) {
-                if (route.destination().toString().equals("0.0.0.0") && route.name().contains("tun")) {
+                if (
+                    (route.destination().toString().equals("0.0.0.0") && route.name().contains("tun")) ||
+                    (route.destination().toString().equals("0.0.0.0") && route.name().contains("wg")) ) {
                     result = true;
                     break;
                 }
-- 
```

Hope this helps, not sure if all wireguard vpn's will be detected this way but it works for mulvad

**Comment by gubatron** [comment]
Right on the spot.
I'll do a similar patch, I believe the only condition you need to OR is the route name being either "tun" or "wg" and we'll have it.

Wish I had seen this message an hour earlier to include this patch on the new build.

I'll add it to the repot though.

Thank you so much for this work @jjgalvez

**Comment by gubatron** [comment]
It's up, please git pull and rebuild to confirm it works with both your OpenVPN and via Wireguard now.

https://github.com/frostwire/frostwire/commit/67d32737df0fb11f9bc5284a31bc46e77dae74c8

**Comment by jjgalvez** [comment]
confirmed the new works with both OpenVPN and Wireguard on Mullvad,
Thanks

**Comment by gubatron** [comment]
most excellent news.

I guess now you can always run the latest by just doing:

```
git pull origin master
gradle build; ./run
```
