### ISSUE TITLE
Frozen Frostwire

### ISSUE THREAD

**Issue by thelostsheep24** [frostwire/frostwire#956]
Been encountering frozen frostwire upon starting up.
Below the screenshot using safemode.
[https://pasteboard.co/JTwMYbO.png](https://pasteboard.co/JTwMYbO.png)

**Comment by gubatron** [comment]
looks like you have a corrupted .resume file, perhaps just delete the entire `c:\Users\GTX1160\.frostwire\libtorrent` folder inside your FrostWire settings folder before starting FrostWire

**Comment by thelostsheep24** [comment]
Problems solved. Thank you so much mate!
Btw, for the resuming half way transfers, is there ways to start multiple instead of clicking one by one?
Thank you in advance!

**Comment by gubatron** [comment]
any time!
