### ISSUE TITLE
[android] Files from Archive.org cannot be saved on SD card if no prior folder 'FrostWire' exists

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#96]
To reproduce:

1) Install FW Basic or Plus from scratch (no prior versions neither prior folders of FW within internal nor external memory)

2) Select the Storage Location option and create a new folder within the SD card

3) Try to download any file from Archive.org (without downloading any other file before) and you should get the message:  “Save directory does not exists or can’t be created”

**Comment by aldenml** [comment]
Try master with this https://github.com/frostwire/frostwire/commit/9af36e626e098195309bd46a790d0e2c0562a5f0

**Comment by muckachina** [comment]
Thanks Alden, is working now on this version from git (although I still got a first .ogg file that couldn't be played) but I did 3 more tests from scratch and it worked so I guess the .ogg file not being saved properly is not a constant thing.

Closing this one.
