### ISSUE TITLE
Finding music to download

### ISSUE THREAD

**Issue by Jfastracer** [frostwire/frostwire#962]
Having trouble finding lot's of music in download

**Comment by gubatron** [comment]
[Please try our new frostwire-android-release-2.4.0-b681-plus.apk](https://github.com/frostwire/frostwire/releases/download/frostwire-android-2.4.0-build-681/frostwire-android-release-2.4.0-b681-plus.apk) -  Release sep 3. 2021 at 4:20pm EST

**Comment by Jfastracer** [comment]
Having trouble finding music to download it only list one or two song's from the group I'm looking up and I tried that new FrostWire and the something there as well
