### ISSUE TITLE
Subtitles of movies are not optional

### ISSUE THREAD

**Issue by 1meBermuda** [frostwire/frostwire#963]
Marvel's Ten Rings movie dies not give option in English.

I have no idea what language is spoken in now

**Comment by 1meBermuda** [comment]
![Screenshot_20210903-232848_FrostWire](https://user-images.githubusercontent.com/90077741/132079660-17b406c4-e5f6-4765-8eb9-5113f58d0e3f.jpg)

**Comment by gubatron** [comment]
This is not in the scope of this application.
FrostWire is just a Bittorrent client, it does not control what people share to one another.
Also, please respect your local copyright laws. FrostWire condemns copyright infringement.
