### ISSUE TITLE
no jlibtorrent-1.2.14.0 in java.library.path

### ISSUE THREAD

**Issue by jhonny-oliveira** [frostwire/frostwire#965]
Hi!

I'm getting the following error while running frostwire 6.9.5 (release tarball) on Ubuntu 20.04 (focal):

java.lang.UnsatisfiedLinkError: no jlibtorrent-1.2.14.0 in java.library.path: [.]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1909)
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:24)
	at com.limegroup.gnutella.gui.Main.main(Main.java:62)
Trying jlibtorrent.<so|dylib>...
java.lang.UnsatisfiedLinkError: no Loaded jlibtorrent.<so|dylib> (version=1.2.14.0) in java.library.path: [.]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1909)
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:32)
	at com.limegroup.gnutella.gui.Main.main(Main.java:62)

Please find attached the full log for further details: [frostwire-6.9.5.amd64.log](https://github.com/frostwire/frostwire/files/7121350/frostwire-6.9.5.amd64.log)

In there, you can also observe that upon shutdown, the program throws yet another exception (after the three empty lines).

Cheers!
Jhonny Oliveira @ xtradeb

**Comment by gubatron** [comment]
Q: does the app still work?

It's suppose to throw some of those exceptions during startup as it tries to look for the jlibtorrent library in different ways (we do this because we have different ways of searching given our multi-OS nature)

You should see, but eventually you should see that it does load the library and it should show the library version.

(Thanks for providing the full log)

and yes, I see that it does load it fine:

```
FrostWire version 6.9.5 build 308
OpenJDK 64-Bit Server VM Private Build 13.0.7 Oracle Corporation
JLibTorrent v1.2.14.0
Boost v1_73
```

**Comment by jhonny-oliveira** [comment]
Yes, the app seems to work fine.

I'm publishing it in my PPA (https://launchpad.net/~xtradeb/+archive/ubuntu/apps) and I was a bit concerned if I was packaging and starting it properly. During the testing phases I noticed the first time it is started it freezes a bit: the tabs and menus get unresponsive for a while. At this point, even closing it can be a challenge. Afterwards, everything seems to work fine.

Thank you for your assistance!

**Comment by gubatron** [comment]
oh that's so sweet! once you get it working, please let me know and we should update the README here and post something on the blog with regards to installing frostwire with apt using your PPA, if you can commit to keep it updated that is

**Comment by jhonny-oliveira** [comment]
Hi!

I'm publishing it already since the beginning of the year. In the past, I made some contributions to the now defunct GetDeb. This was one of the top downloaded packages in there.

I do intend to keep on updating all the packages in my PPAs (xtradeb: apps and play). I also plan to make available a small website to publicize my work (https://xtradeb.net). Hopefully, it will go online in a couple of days.

I would appreciate if you list my PPA as a frostwire installation source.

Thank you!
