### ISSUE TITLE
Unable to Install .deb Linux Version

### ISSUE THREAD

**Issue by brandiqa** [frostwire/frostwire#967]
Am currently using Zorin OS 16 which is based on Ubuntu 20.04.3 LTS (Focal Fossa). The installation fails because of lack of package candidates for the dependencies.

```bash
$ sudo dpkg -i frostwire-6.9.5.amd64.deb 
   
Selecting previously unselected package frostwire.
(Reading database ... 298780 files and directories currently installed.)
Preparing to unpack frostwire-6.9.5.amd64.deb ...
Unpacking frostwire (6.9.5) ...
dpkg: dependency problems prevent configuration of frostwire:
 frostwire depends on openjdk-14-jre-headless; however:
  Package openjdk-14-jre-headless is not installed.
 frostwire depends on mplayer; however:
  Package mplayer is not installed.
 frostwire depends on net-tools; however:
  Package net-tools is not installed.
```

**Comment by gubatron** [comment]
try`sudo apt-get -f install` and it should install the missing dependencies for you

**Comment by brandiqa** [comment]
I was having issue with no install candidate for `openjdk-14-jre-headless`

Managed to resolve that using the following commands:

```bash
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
```

**Comment by brandiqa** [comment]
Unfortunately, the issue hasn't been resolved. This is the error am getting. Tried `sudo add-apt-repository ppa:openjdk-r/ppa` but that didn't resolve the following issue:

```
`E: Package 'openjdk-14-jre-headless' has no installation candidate
```

**Comment by gubatron** [comment]
it's pretty weird that it's telling you to use openjdk-14, we only ask for openjdk-11

**Comment by gubatron** [comment]
Not reopening because it's not really our issue. It seems to be an issue of your Linux package manager.
The package works perfectly well on Ubuntu.

**Comment by brandiqa** [comment]
I did some digging into the deb file. Found this file called control:

```
Package: frostwire
Version: 6.9.5
Architecture: amd64
Maintainer: FrostWire Team <contact@frostwire.com>
Installed-Size: 38566
Depends: openjdk-14-jre-headless, zlib1g (>= 1:1.1.4), mplayer, net-tools, libc6 (>= 2.27)
Section: net
Priority: optional
Homepage: http://www.frostwire.com
Description: Open source file downloader and BitTorrent client
 Its BitTorrent core is based on frostwire-jlibtorrent, a java
 API wrapper around libtorrent. Needs the OpenJDK Java Runtime Environment
 (minimum version tested is OpenJDK JRE 11+)
```

**Comment by brandiqa** [comment]
I've managed to fix the issue, I did an unpack, changed version to `openjdk-15-jre-headless`, then packed it up and run the install. The installation on the fixed.deb version is now successful.

For some reason `openjdk-14-jre-headless` has been skipped when I look at available packages in synaptic

**Comment by gubatron** [comment]
Awesome, will update the control file to suggest `openjdk-15-jre-headless`.
(I totally thought we had `openjdk-11-jdk-headless` man wow!, I guess I was remembering the description but not the depends)

Our next update will feature this change, thank you @brandiqa ! 

(Hopefully most Ubuntu distros have `openjdk-15-jre-headless` will test)

```patch
diff --git a/installer_builders/linux/distro-packages/control b/installer_builders/linux/distro-packages/control
index 692a3f7..b22b60d 100644
--- a/installer_builders/linux/distro-packages/control
+++ b/installer_builders/linux/distro-packages/control
@@ -3,7 +3,7 @@ Section: net
 Priority: optional
 Maintainer: FrostWire Team <contact@frostwire.com>
 Uploaders: Angel Leon <gubatron@gmail.com>
-Build-Depends: ant, gradle, openjdk-14-jdk-headless, zlib1g, javahelper
+Build-Depends: ant, gradle, openjdk-15-jdk-headless, zlib1g, javahelper
 Standards-Version: 3.9.0
 
 Package: frostwire
(END)
```

**Comment by gubatron** [comment]
<img width="1667" alt="Screen Shot 2021-09-17 at 8 57 26 AM" src="https://user-images.githubusercontent.com/163977/133804345-5af93797-cc67-4f64-86a9-6f1147b9de28.png">

**Comment by brandiqa** [comment]
Your welcome @gubatron! Glad to have helped :)
