### ISSUE TITLE
[desktop] FrostWire 6.9.5 crash telluride on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by MacTerrassa** [frostwire/frostwire#968]
On an iMac Intel Core 2 Duo (2007) with Mac OS X 10.11.6 I don't see any problems until version 6.9.4.
When updating to 6.9.5 the program starts correctly, I get a crash message related to telluride. However, the Frostwire program is still open and seems to work.
I have only tried to download one of the advertising discs, and I have done a search that gives results and I can start downloading.
Telluride failure, is it important and what functions are related to it to check if they work or not?
Is it a compatibility issue with my system or my mac? In another more current with Catalina, I have not observed any problem.
Regards
MacTerras
[TellurideCrash.txt](https://github.com/frostwire/frostwire/files/7184979/TellurideCrash.txt)

**Comment by gubatron** [comment]
Thank you for reporting this.
Interesting to hear that this is crashing on 10.11.6. Perhaps I built it on Big Sur by mistake, or an update of my libraries on the old 10.11 machine that I have is breaking things.

Telluride is a new component we added this year that allows FrostWire to download videos from hundreds of websites.

Here's a demo
https://www.youtube.com/watch?v=fSOAhBJkWwA

Checking the crashlog

A million thanks.

**Comment by gubatron** [comment]
I think we'll have to raise the minimum requirements to Catalina if we can't find a fix with PyInstaller.

```

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   telluride_macos               	0x000000010c429c46 0x10c428000 + 7238
1   telluride_macos               	0x000000010c429e07 0x10c428000 + 7687
2   telluride_macos               	0x000000010c42ae58 0x10c428000 + 11864
3   libdyld.dylib                 	0x00007fff94c785ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000a8069b  rbx: 0x0000000000a8c42b  rcx: 0x000000000000bde8  rdx: 0x00001e0000001e00
  rdi: 0x00007fff7d2ff2a8  rsi: 0x0000000000012068  rbp: 0x00007fff537d6fb0  rsp: 0x00007fff537d6f80
   r8: 0x0000000000000040   r9: 0x00007fff7d2ff2a0  r10: 0xffffffffffffffff  r11: 0x00007fe962002620
  r12: 0x00007fe962002600  r13: 0x0000000000a8c284  r14: 0x00000000ffffffff  r15: 0x0000000000002000
  rip: 0x000000010c429c46  rfl: 0x0000000000010206  cr2: 0x00007fe962801000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     6


Binary Images:
       0x10c428000 -        0x10c430ff3 +telluride_macos (0) <21B46D6F-B65A-33AA-A8D2-B3127A52D882> /Applications/FrostWireXXX.app/Contents/MacOS/telluride_macos
```

**Comment by gubatron** [comment]
Closing, we can't offer support for 10.11, only for macOS 10.14.6 and up (and this might be going away soon)
