### ISSUE TITLE
[android] Notify FrostWire is running / 'Exit' action - The app appears on 'Running apps' after Exiting FW

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#97]
After 'Exit' FrostWire from the main menu the 'Notification message' doesn't appear on the 'slide menu' of the device, however, I can see **FrostWire is running if I select the 'Running Apps'** square button placed at the bottom bar of the device.

![screen shot 2016-02-11 at 11 01 53 am](https://cloud.githubusercontent.com/assets/1534723/13152422/1eb3700e-d63d-11e5-86b2-0790ded07431.png)

One of the processes that leave the app running behind even after 'Exiting' FW is when you do a search and then 'Exit' the app.

To reproduce:

*1) Open FW and do a search.*

*2) Open main menu and 'Exit' FW*

*3) After exiting the ads you will see FW logo at the top-left of the screen. Also if you go to your device Settings and check 'Running Apps' you will see these FW services running: 'MusicPlayBackService' and 'EngineService'.* (See image attached):

![screen shot 2016-02-18 at 12 23 48 pm](https://cloud.githubusercontent.com/assets/1534723/13152512/96663906-d63d-11e5-8079-186fac2d4fbe.png)

Ticket on qa-android: https://github.com/frostwire/qa-android/issues/78

**Comment by kad3mlia** [comment]
On my phone (Sony Xperia Z5 with Android 5.1.1), it Exits (I no longer see the notification that it is running, nor any other sign of it). If I go to Apps > Running right after shutdown, FrostWire is not there either. 
If I come back after a while (about 10min) to Apps > Running I see the app active with 1 Service and 2 Processes active. 

See screenshot
![screenshot_2016-03-01-16-57-08](https://cloud.githubusercontent.com/assets/7243139/13443425/feb79546-dfce-11e5-8f3c-1a558d62e409.png)

**Comment by gubatron** [comment]
@muckachina please take a look again to see if this issue keeps happening. Should be good now.

**Comment by gubatron** [comment]
ping

**Comment by marcelinkaaa** [comment]
I had the same thing that @muckachina was experiencing before and it persists. Currently I have the FrostWire Plus v.1.7.4 256 that was shared and upon exiting the app I can still see the app the same way as muckachina's first screenshot above. Frostwire seem to not be visible in the settings -> running apps.
![picture](https://cloud.githubusercontent.com/assets/2339972/15765359/f9232970-2901-11e6-8f46-da30d186086d.png)

**Comment by aldenml** [comment]
Well, that's the list of recent opened applications, not current running applications. As long as we are not running (or silently restarting) anymore  we are fine.

**Comment by marcelinkaaa** [comment]
Sorry I wanted to say "but it does not persists". I had it in my settings - running apps before similarly to Kademlia but not anymore. 
But for a second I thought the screenshot above is also about running apps. :/ my bad.

**Comment by gubatron** [comment]
@muckachina is this still happening with the latest release?
I think a lot of work was done to have proper shutdown, should be better now.

**Comment by gubatron** [comment]
bump.
Is this still happening after all the fixes with releasing advertisement resources on 1.7.6?

**Comment by gubatron** [comment]
@muckachina is this still happening?

**Comment by gubatron** [comment]
It seems this issue has subdued after fixes with the advertising SDKs which may have been keeping the process open or coming back.

**Comment by olivier-voutat** [comment]
Still happening in my galaxy s8 with Android pie.. Really annoying.

**Comment by gubatron** [comment]
what's happening now is a bit different and it has to do with the way FrostWire must advertise its background service to android, now it's android that says "FrostWire is Running", we'll try to see if there's a way to make this experience better by automatically shutting down the service if the user isn't actively seeding nor downloading anything.

**Comment by olivier-voutat** [comment]
Any news for this. Still happening...

**Comment by olivier-voutat** [comment]
Got worst after update from yesterday... The permanent notification from settings isn't working and I still have the running notification from Android for the frostwire app...

**Comment by gubatron** [comment]
@olivier-voutat are you sure you hit Exit from the menu, and not back all the way to go home?

Thank you for reporting, I'll take another look.

**Comment by olivier-voutat** [comment]
Yes, I am.
