### ISSUE TITLE
[android] downloads saved in directory that needs root access

### ISSUE THREAD

**Issue by MohamedToba** [frostwire/frostwire#973]
This is the path data gets saved in: /storage/emulated/0/Android/data/com.frostwire.android/files/FrostWire which cannot be accessed through regular file managers, and there is no way to change it.
I tried removing the app and installing again multiple times.
Using Android 11, with oneUI on Samsung A71.

**Comment by qyzhaojinxi** [comment]
Google reuqire this since android 11

**Comment by gubatron** [comment]
working on changes related to this and other issues after the endless changes android makes to store files every android release
