### ISSUE TITLE
[android] Download doesn't work on oppo reno 4 pro

### ISSUE THREAD

**Issue by qyzhaojinxi** [frostwire/frostwire#977]
I test frostwire 2.4.3 and other 2.4.x versions on my oppo reno 4 pro. It didn't work and the task has no speed. It has no peers. 

And then I test 2.3.1 version on the same device. It worked normally.

 My device is: Snapdragon 765G cpu, android 11.

**Comment by gubatron** [comment]
[Please test 2.4.5](https://github.com/frostwire/frostwire/releases/tag/frostwire-android-2.4.5-build-688)

**Comment by qyzhaojinxi** [comment]
Thank you. I will test it today and feedback the result here.

**Comment by qyzhaojinxi** [comment]
Hi, I test 2.4.5 and it still has no speed.

**Comment by gubatron** [comment]
is there any error output that could give us a hint? (`adb logcat | grep frostwire`)

**Comment by qyzhaojinxi** [comment]
[frostwire_log.log](https://github.com/frostwire/frostwire/files/7842923/frostwire_log.log)
Hi, it's the test log. I hope it can help. Thanks for your reply again.

**Comment by qyzhaojinxi** [comment]
Some task stuck at the error status and some at downloading. The same info is no speed and no peers.

**Comment by qyzhaojinxi** [comment]
I found this:

```
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:42)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.swig.libtorrent_jni.alert_error_notification_get(Native Method)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.swig.alert.<clinit>(alert.java:494)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.alerts.AlertType.<clinit>(AlertType.java:11)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.SessionManager.<clinit>(SessionManager.java:23)
01-11 09:16:21.872  2531  2751 W System.err: 	at com.frostwire.android.gui.MainApplication$BTEngineInitializer.run(MainApplication.java:141)

```

and this:

```

01-11 09:16:36.995  2531  2531 I chatty  : uid=10518(com.frostwire.android) ivity.java:370) identical 10 lines
01-11 09:16:37.135  1720  3929 D ConnectivityService: requestNetwork for uid/pid:10518/2531 NetworkRequest [ TRACK_DEFAULT id=16752, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ]
01-11 09:16:37.140  1720  2568 D OplusWifiNetworkFactory2: got request NetworkRequest [ TRACK_DEFAULT id=16752, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.141  1720  2650 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=16752, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.141  1720  2538 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=16752, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.141  1720  2538 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=16752, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.141  3383  3383 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=16752, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.150  1720  3929 D ConnectivityService: requestNetwork for uid/pid:10518/2531 NetworkRequest [ TRACK_DEFAULT id=16753, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ]
01-11 09:16:37.151  1720  2568 D OplusWifiNetworkFactory2: got request NetworkRequest [ TRACK_DEFAULT id=16753, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.151  1720  2538 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=16753, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.154  3383  3383 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=16753, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.154  1720  2538 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=16753, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.154  1720  2650 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=16753, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10518 AdministratorUids: [] RequestorUid: 10518 RequestorPackageName: com.frostwire.android] ] with score 79 and providerId 6
01-11 09:16:37.430  2531  2531 I chatty  : uid=10518(com.frostwire.android) ivity.java:370) identical 4 lines


```

**Comment by gubatron** [comment]
could you dig up more around here? the whole stacktrace would be awesome to see what the actual error is that's not letting the Bittorrent engine be initialized.

```
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:42)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.swig.libtorrent_jni.alert_error_notification_get(Native Method)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.swig.alert.<clinit>(alert.java:494)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.alerts.AlertType.<clinit>(AlertType.java:11)
01-11 09:16:21.870  2531  2751 W System.err: 	at com.frostwire.jlibtorrent.SessionManager.<clinit>(SessionManager.java:23)
01-11 09:16:21.872  2531  2751 W System.err: 	at com.frostwire.android.gui.MainApplication$BTEngineInitializer.run(MainApplication.java:141)
```

**Comment by qyzhaojinxi** [comment]
Sorry, I just find this and don't know why the bt engine init failed. The whole log is in frostwire_log.log file.

**Comment by gubatron** [comment]
oh thanks, I had missed that file.

However, I see that some lines have been filtered (for repetition)

bogon:~ zhaojinxi$ adb logcat | grep frostwire
01-11 09:09:53.653 30066 30066 I chatty  : uid=10518(com.frostwire.android) identical 43 lines
01-11 09:09:56.092 30066 30066 I chatty  : uid=10518(com.frostwire.android) identical 40 lines
01-11 09:10:57.113 30066 30066 I chatty  : uid=10518(com.frostwire.android) identical 19 lines
01-11 09:12:13.835 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 48 lines
01-11 09:12:14.792 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 31 lines
01-11 09:12:28.440 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 34 lines
01-11 09:12:40.111 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 10 lines
01-11 09:13:05.697 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 11 lines
01-11 09:13:20.279 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 18 lines
01-11 09:13:30.973 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 84 lines
01-11 09:13:41.916 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 37 lines
01-11 09:13:59.980 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 107 lines
01-11 09:14:15.705 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 86 lines
01-11 09:14:20.321 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 55 lines
01-11 09:14:32.388 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 22 lines
01-11 09:14:49.467 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 18 lines
01-11 09:14:51.525 32607 32607 I chatty  : uid=10518(com.frostwire.android) identical 100 lines

**Comment by qyzhaojinxi** [comment]
ok, I will test it again and grep the full log when I get this special device.

**Comment by qyzhaojinxi** [comment]
Hi, I test this device again. But it still doesn't work on  version 2.4.7. I grep the log and can't find anything useful.
[frostwire-2-4-7.log](https://github.com/frostwire/frostwire/files/8122650/frostwire-2-4-7.log)
[forstwire-2-4-3.log](https://github.com/frostwire/frostwire/files/8122652/forstwire-2-4-3.log)

**Comment by qyzhaojinxi** [comment]
Hi, I found something new. I try to change targetSdkVersion from 30 to 29. And then the dht nodes show not zero contacts.

And there is seedings and peers. All those are zero when targetSdkVersion=30. But at this time the speed is still 0. When set 
targetSdkVersion = 29, I foud some log below and it never show before.

```

2022-03-24 14:09:35.682 20885-20885/com.frostwire.android I/chatty: uid=10556(com.frostwire.android) cation.java:79) identical 29 lines
2022-03-24 14:09:35.682 20885-20885/com.frostwire.android E/Parcel: Reading a NULL string not supported here.
2022-03-24 14:09:35.684 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 192.168.1.157:39662 type:TCP
2022-03-24 14:09:35.684 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 192.168.1.157:39662 type:UDP
2022-03-24 14:09:35.684 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 10.20.117.30:39662 type:TCP
2022-03-24 14:09:35.684 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 10.20.117.30:39662 type:UDP
2022-03-24 14:09:35.685 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 127.0.0.1:39662 type:TCP
2022-03-24 14:09:35.685 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 127.0.0.1:39662 type:UDP
2022-03-24 14:09:35.696 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::77cd:436a:1a0d:190%wlan0:39662 type:TCP
2022-03-24 14:09:35.696 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::77cd:436a:1a0d:190%wlan0:39662 type:UDP
2022-03-24 14:09:35.696 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::2f43:637f:69ca:c503%rmnet_data3:39662 type:TCP
2022-03-24 14:09:35.697 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::2f43:637f:69ca:c503%rmnet_data3:39662 type:UDP
2022-03-24 14:09:35.697 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 240e:404:2601:bb38:2f43:637f:69ca:c503:39662 type:TCP
2022-03-24 14:09:35.697 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 240e:404:2601:bb38:2f43:637f:69ca:c503:39662 type:UDP
2022-03-24 14:09:35.698 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::764:9f8f:b226:5b56%rmnet_data2:39662 type:TCP
2022-03-24 14:09:35.698 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::764:9f8f:b226:5b56%rmnet_data2:39662 type:UDP
2022-03-24 14:09:35.698 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 240e:504:2612:8cc5:764:9f8f:b226:5b56:39662 type:TCP
2022-03-24 14:09:35.698 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 240e:504:2612:8cc5:764:9f8f:b226:5b56:39662 type:UDP
2022-03-24 14:09:35.699 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::8573:9cd5:223c:353e%rmnet_data1:39662 type:TCP
2022-03-24 14:09:35.699 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::8573:9cd5:223c:353e%rmnet_data1:39662 type:UDP
2022-03-24 14:09:35.699 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 240e:504:7a10:e821:8573:9cd5:223c:353e:39662 type:TCP
2022-03-24 14:09:35.699 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: 240e:504:7a10:e821:8573:9cd5:223c:353e:39662 type:UDP
2022-03-24 14:09:35.699 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::823b:8eae:c0d8:c295%rmnet_data0:39662 type:TCP
2022-03-24 14:09:35.700 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::823b:8eae:c0d8:c295%rmnet_data0:39662 type:UDP
2022-03-24 14:09:35.700 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::b033:84ff:fec3:ea99%dummy0:39662 type:TCP
2022-03-24 14:09:35.700 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: fe80::b033:84ff:fec3:ea99%dummy0:39662 type:UDP
2022-03-24 14:09:35.701 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: ::1:39662 type:TCP
2022-03-24 14:09:35.701 20885-20976/com.frostwire.android I/BTEngine: Listen succeeded on endpoint: ::1:39662 type:UDP

```

**Comment by qyzhaojinxi** [comment]
So I think it's sort of android 11 compatibility problem. Can you find solution to solve this?

**Comment by gubatron** [comment]
I don't think it's an Android 11 issue.
It must be an issue with the kernel of that device and how it handles networking security. 

We upgraded our min sdk to 24 (Android 7.0) on FrostWire 2.4.2 and made it incompatible for Android 6 and below due to changes in the network security model, Android removed `netlink` socket support for Android 11+ in favor of `ifaddr` sockets.

My guess is that the manufacturer of that device went to Android 11 but kept the old netlink sockets which are no longer supported for that sdk level, and jlibtorrent will only attempt to use netlink sockets for Android 10 and below.

The app runs perfectly well in all the Android 11 devices and emulators I have

![Screenshot_20220325-115837](https://user-images.githubusercontent.com/163977/160176775-f8b24513-71e0-49a4-a173-20e5dfb586ca.jpg)
![Screenshot_20220325-115726](https://user-images.githubusercontent.com/163977/160176782-db3933ff-11ce-4936-aa63-4bf0ccd9e9c2.jpg)
![Screenshot_20220325-115812](https://user-images.githubusercontent.com/163977/160176785-e3e06d60-e06e-488a-a02a-cbc4e21cfc7b.jpg)

**Comment by qyzhaojinxi** [comment]
Yes, I test many other android11 devices and they work well except on oppo reno 4 pro. How can I solve this problem? like try ifaddr first and if it failed then netlink.

**Comment by qyzhaojinxi** [comment]
I can understand. But I use jlibtorrent in my app and see that some users feedback about no speed all the time. I'm not sure if it's the same cause. Then I tested libretorrent  app on oppo reno4 pro and it worked well. I don't know how the libretorrent do. I think maybe it's not just one device. And I find that oppo device is in top5 of all my users. So I think it's worth to do that.

**Comment by gubatron** [comment]
perhaps you need to downgrade to 2.3.1

I cannot replicate the issue on any of my devices.

Usually complains about "no speed" is simply the torrent not having sources or issues with firewalls.

**Comment by qyzhaojinxi** [comment]
But I test the same torrent file and the same networks with libretorrent app on the oppo reno4 pro device. It really works well. And of course I can't downgrade to 2.3.1 when the target is 30 or above. It doesn't work on many android 11 devices. The only thing that I'm not sure is the coverage of devices like oppo reno4 pro. I really hope you can solve it.
