### ISSUE TITLE
Error building frostwire-6.9.8

### ISSUE THREAD

**Issue by jhonny-oliveira** [frostwire/frostwire#986]
Hi!

I get this error when building frostwire-6.9.8:

> Task :desktop:compileJava
/workspace/xtradeb/apps/frostwire/frostwire-6.9.8+dfsg/desktop/src/com/frostwire/gui/updates/UpdateMessage.java:253: error: cannot find symbol
    @Serial
     ^
  symbol:   class Serial
  location: class UpdateMessage
/workspace/xtradeb/apps/frostwire/frostwire-6.9.8+dfsg/desktop/src/com/frostwire/gui/updates/UpdateMessage.java:258: error: cannot find symbol
    @Serial
     ^
  symbol:   class Serial
  location: class UpdateMessage
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

> Task :desktop:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

Any ideas? Did I miss some dependency?

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by gubatron** [comment]
Hi, please make sure to `git pull origin master` and then try to build from the command line issuing

```
./gradlew clean build
```
<img width="1118" alt="Screen Shot 2022-04-27 at 1 06 29 PM" src="https://user-images.githubusercontent.com/163977/165601109-6adbe6fe-0b3c-4ce0-b29e-38da24473c40.png">

Please also try building with OpenJDK 18.0.1

**Comment by gubatron** [comment]
Also, If you're building with anything lower than Java 14, the `@Serial` annotation will not work.
Perhaps you have an old `javac` version in your path. Please try with Java 18.0.1

**Comment by jhonny-oliveira** [comment]
I was attempting to build with JDK11, hence the issue.
After updating the recipe to use JDK17, the problem was gone.

Thank you!
