### ISSUE TITLE
[desktop] FrostWire 6.10.0 tasks

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#999]
- [x] #998
- [x] #954 
- [x] #932
- [ ] #883
- [ ] #845

**Comment by rosoau** [comment]
OS Xubuntu 22.04, gnome-flashback session, nvidia driver 390, compiz-reloaded
from version 6.10 onwards the lower part of the window is shaking nervously.
This does not happen with versions 6.9.10 and below
I was  lucky to find this older version on sourceforge
